### ISSUE TITLE
Allow launching NTR cartridges with no banner.

### ISSUE THREAD

**Issue by GerbilSoft** [Robz8/TWLoader#100]
http://gbatemp.net/threads/twloader-ctr-mode-nds-app.448375/page-138#post-7036989

CycloDS apparently doesn't show a normal banner on 3DS. If FSUSER_CardSlotIsInserted() returns true even in this case, then we can just have it interpret this case as "Generic NTR cartridge" and launch anyway.

TODO: Need to investigate if FSUSER_CardSlotIsInserted() returns true here. I don't have a CycloDS to test this.

**Comment by Robz8** [comment]
I have a CycloDS.

**Comment by Robz8** [comment]
I'm getting "No Cartridge" with a CycloDS.
