### ISSUE TITLE
Box Art fails to download/display

### ISSUE THREAD

**Issue by NinjaBoyLao** [Robz8/TWLoader#102]
I think this is unique to 3.0. The box art for my pokemon games used to be shown, and used to download automatically. It doesn't appear now, and only shows a "?" now in the top screen. I've changed my default rom path, though, is that the source of this issue?

**Comment by Robz8** [comment]
The issue should be fixed in v3.0.2.

**Comment by NinjaBoyLao** [comment]
Oh hey when did that come out? I just checked and it wasn't there.
