### ISSUE TITLE
Update bootstrap and Update TWLoader functionality broken

### ISSUE THREAD

**Issue by NinjaBoyLao** [Robz8/TWLoader#103]
Previously, Pressing X on the settings screen would update bootstrap to latest stable, while pressing Y would update to the latest nightly, Pressing Start would update TWLoader itself, if there was an update. Now, disappointingly, all three options yield a dull error noise, a low pitched bzzt sound. At least the first and last option worked before the update. I'm sorry for opening 2 issues at once, but they seemed very different.

**Comment by Robz8** [comment]
The issue should be fixed in v3.0.2.

**Comment by NinjaBoyLao** [comment]
Testing now, I have to install manually for some reason .-.

**Comment by NinjaBoyLao** [comment]
It's fixed, thank you, sorry again, i didn't see either of these closed. my bad
