### ISSUE TITLE
switch between bootstrap.nds

### ISSUE THREAD

**Issue by adrifcastr** [Robz8/TWLoader#105]
store the official and the unofiicial on there and switch between both by like pressing x or y

**Comment by maorninja** [comment]
I agree, as this can actually make testing the latest commits alot faster...

**Comment by Margen67** [comment]
What's the difference between official and unofficial?

**Comment by Robz8** [comment]
Unofficial is the latest commit (which isn't latest right now), and official is the latest release.

**Comment by adrifcastr** [comment]
why is it closed now

**Comment by Jolty95** [comment]
I close this because this is already implemented and will be available in the next release version

**Comment by Margen67** [comment]
https://jenkins.hakujou.fr/job/3DS/job/TWLoader

**Comment by Jolty95** [comment]
@Margen67 what's wrong with jenkins?

**Comment by Margen67** [comment]
Nothing. I'm just posting it in case they need it.

**Comment by adrifcastr** [comment]
oh, I havent seen any commit implementing it. sorry then thank you.

2017-01-30 18:44 GMT+01:00 Jolty <notifications@github.com>:
