### ISSUE TITLE
White Screen After Add Game

### ISSUE THREAD

**Issue by greensad** [Robz8/TWLoader#106]
Trying to add games from my DSTWO causes TWLoader to hang on a white screen infinitely, I can however use home and power to exit TWLoader so my 3DS does not appear to have crashed. I've followed the main tutorial as well as the flashcart tutorial, is there a step I may have missed or is this not working on the latest build?

**Comment by Robz8** [comment]
Add Games is working for me.
Did you set your flashcard in settings?

**Comment by greensad** [comment]
Yes, not sure what the problem could be

**Comment by Robz8** [comment]
Try re-downloading the flashcard pack.

**Comment by chronoss09** [comment]
For me, i boot very well on my flashcard but how to add them to TWLoader menu ?

**Comment by Robz8** [comment]
If you re-downloaded and re-extracted the flashcard pack, try running "Add Games" again.

**Comment by chronoss09** [comment]
Red screen and "Guru Meditation error, data abort" when i want add a game, what does it means ?

**Comment by Robz8** [comment]
No idea.

**Comment by chronoss09** [comment]
What can i do to add my game now ?

**Comment by Robz8** [comment]
Nothing. I have no idea how to fix the bug.

**Comment by Robz8** [comment]
The red screen and "Guru Meditation error, data abort" no longer appears in v3.2.
