### ISSUE TITLE
Add game does not work for me with 3.0.2

### ISSUE THREAD

**Issue by chofstede** [Robz8/TWLoader#108]
Flashcard: R4I-SDHC 3DS RTS (r4i-sdhc.com)

- I copied the _nds folder to my 3DS SDCard
- I installed the SIDE .cia and the TWLoader .cia to sysNAND

- Copied the correct ysmenu forwarder ("for Slot-1 microSD (R4i-SDHC RTS)") to the R4i SDCard 
- Copied the _nds/twloader.nds from twloader to R4i SDCard

When i enter the "add rom" feature of the TWLoader, it boots fine to a menu where i can add my games. After selecting a game, if see that it is "downloading boxart" and "generating ini"

After restart (home-button), I have no game in TWloader. When looking onto my SD-Card, i can see a downloaded boxart, but no ini file was created.

**Comment by Robz8** [comment]
It still works for me.

**Comment by Robz8** [comment]
Did you update the flashcard pack?

**Comment by chofstede** [comment]
I downloaded the flashcard pack today from here: 

`https://www.dropbox.com/s/xxfmvikwmnvsu63/DS%20Game%20Forwarder%20pack%20%28DSTT%2C%20R4i%20Gold%2C%20R4i-SDHC%2C%20SC%20DSONE%29.7z?dl=0`

I copied the "for Slot-1 microSD (R4i-SDHC RTS)" to the R4i SDCard, since it is a R4I-SDHC 3DS RTS from r4i-sdhc.com. In TWLoader I hava selected the "DSTT/R4i Gold/R4i-SDHC....." Flashcard.
I guess thats correct ?!

**Comment by Robz8** [comment]
Yes.

**Comment by chofstede** [comment]
When I re-run "add game" and select a title, I alrady added, it's weird.
I can see "Banner Data already exist" and directly after that ".ini file created".

I can confim, banner data for that game is on the 3ds flashcart (_nds/twloader/bnricons/flashcart) but no .ini file is created on the 3ds sd filesystem.

I tried with 6 different games

**Comment by Robz8** [comment]
What's your flashcard rom folder? Check in settings.ini.

**Comment by chofstede** [comment]
I guess thats the FCROM_FOLDER = roms/flashcard/nds 

Here the full settings.ini:

`[FRONTEND]
COLOR = 0
TOP_BORDER = 1
TOP_LAYOUT = 0
COUNTER = 0
AUTOUPDATE = 0
AUTODOWNLOAD = 0
ROM_FOLDER = roms/nds
FCROM_FOLDER = roms/flashcard/nds
LANGUAGE = -1
MENU_COLOR = 0
SHOW_FILENAME = 0
CUSTOM_BOTTOM = 0
NAME = Chris

[TWL-MODE]
RAINBOW_LED = 0
TWL_CLOCK = 1
BOOT_ANIMATION = 1
HEALTH&SAFETY_MSG = 1
LAUNCH_SLOT1 = 0
RESET_SLOT1 = 1
DEBUG = -1
FORWARDER = 1
FLASHCARD = 0
TWL_VRAM = 0
LOCK_ARM9_SCFG_EXT = 1
SLOT1_KEEPSD = 0
GBARUNNER = 0
GAMESETTINGS_PATH = sd:/_nds/twloader/gamesettings/flashcard/
`

**Comment by Robz8** [comment]
Is the .ini's not in "sdmc:/roms/flashcard/nds/"?

**Comment by chofstede** [comment]
Um, that folder does not exist. It is not included in the directory structure from the 3.0.2 twloader zipfile, that should be created on the sdmc (TWLoader.7z). I'll try creating that folders and report back

**Comment by chofstede** [comment]
Okay. now it works perfectly. Didn't realize, I have to create that folder structure manually. 

Thank you for your great and quick help.

**Comment by Robz8** [comment]
Your welcome. I might fix it sometime.
