### ISSUE TITLE
Frequent crashing on QW1028 New 3DS

### ISSUE THREAD

**Issue by RubberBrony** [Robz8/TWLoader#11]
I'm not sure if this issue is specific to me, but if I:

* Attempt to exit Settings
* Attempt to scroll one or more icons down the row
* Switch from Flash Card to SD mode
* Scroll from Settings to any icon,

The application crashes. It doesn't throw any errors in ErrDisp, and nothing but hard-resetting the console by holding the power button or pulling the battery will exit. Whenever it crashes, however, it seems like one of the Box Arts is missing/misplaced. Not sure if this is the cause.

I have:

* TWLoader v1.5.3, freshly installed
* A 128 GB microSD card
* 11.2.0-35U
* Luma3DS 6.6 through A9LH
* R4i Gold v1.4 2011 (A DSTT Clone with time bomb, works with DSTT forwarders)

**Comment by Robz8** [comment]
A new version of TWLoader has been released. See if the new version fixes your problem.

**Comment by RubberBrony** [comment]
* No longer crashes after exiting Settings the first time now, but repeated exits will still crash. 
* No longer crashes when switching from SD to Flash Card.
* Scrolling still crashes as well, although it only happens when I scroll more than one game over.

It turns out the box art was just misnamed, so the "error" I saw was entirely human error, sorry.

Here's a picture of the crash. It's not very informative, but I guess it might be useful.

![Picture of the Crash](https://cloud.githubusercontent.com/assets/8754234/21123273/5071147a-c09d-11e6-82d5-1dfa8810b2bd.jpg)

**Comment by Robz8** [comment]
* Repeated exits don't happen for me.
* That's good.
* Doesn't happen for me.

Looks like you're the only one who has these problems.

**Comment by Robz8** [comment]
Is any sound effects playing? If not, that's a sign that it's crashing.

**Comment by RubberBrony** [comment]
I just installed it on my 2DS, same problems.

Also, I have yet to hear a single sound effect, are there supposed to be some?

**Comment by Robz8** [comment]
Yes.

**Comment by RubberBrony** [comment]
Oh, okay. Does it require a dump of the DSP Firm? I might've deleted my dump by accident, I'll dump it again and then see what happens

**Comment by RubberBrony** [comment]
That was the problem! I'm sorry for bothering you, it was a major derp on my part.
