### ISSUE TITLE
Plz Halp

### ISSUE THREAD

**Issue by Redswastaken** [Robz8/TWLoader#114]
I tried to use a very outdated video to try to download the loader (video here https://www.youtube.com/watch?v=bGpyu65LdUY&t=353s) I got the application twloader, but I have no clue where to put my ds roms. I've tried what feels like everywhere, but I the loader doesn't read any of my roms

**Comment by Robz8** [comment]
Try "sdmc:/roms/nds/".

**Comment by Redswastaken** [comment]
So i create a new folder called roms?

**Comment by Jolty95** [comment]
Please, do not use outdated videos. All the info you need is on gbatemp or the official wiki in github.

**Comment by Redswastaken** [comment]
Jolty95 please link me to it. I didn't want to use an outdated video, but all the guides i found were out of date.

**Comment by Jolty95** [comment]
Here it's all the info you need to run roms with TWLoader. https://github.com/Robz8/TWLoader/wiki
