### ISSUE TITLE
Downloading missing box art/ downloading OS X?

### ISSUE THREAD

**Issue by Redswastaken** [Robz8/TWLoader#115]
I downloaded my roms to the correct directory and I gave each rom there own box art image in the box art folder, but when I launch TWLoader I get this message "downloading missing boxart...    2/3

**Comment by Redswastaken** [comment]
As well As Downloading: OS X. I don't know why it's trying to download these things and it's taking a tremendously long time. Did I do something wrong?

**Comment by Robz8** [comment]
No. I think "OS?X" is the TID of one of your games.

**Comment by Redswastaken** [comment]
It has to download this even though I included box art for it? Should The download be taking a very long time?

**Comment by Robz8** [comment]
It downloads box art by the game's TID, not by nds filename.

**Comment by Redswastaken** [comment]
So do I have to name one of the pngs for the box art "OS X.nds.png"?

**Comment by Robz8** [comment]
Yes, but exclude ".nds".

**Comment by Redswastaken** [comment]
Ok thank you. You've been very helpful

**Comment by Robz8** [comment]
You're welcome.
