### ISSUE TITLE
Banner Data

### ISSUE THREAD

**Issue by Redswastaken** [Robz8/TWLoader#116]
Sorry if this is starting to get annoying. My issue for this hour of the day is that when I boot TWLoader I get the message "Now checking if banner data exists (SD Card)". Any known fix? Thanks in advance.

**Comment by Redswastaken** [comment]
The message doesn't seem to go away

**Comment by Robz8** [comment]
Does it at least show the game menu?

**Comment by Redswastaken** [comment]
no. On the top screen I see the TWLoader logo, and on the bottom I see the message

**Comment by Robz8** [comment]
Does it show a rom filename and a number below "Now checking if banner data exists (SD Card)"?

**Comment by Redswastaken** [comment]
no

**Comment by Robz8** [comment]
Try clearing the banner .bin files in "sdmc:/_nds/twloader/bnricons/" (ignore the flashcard folder).

**Comment by Redswastaken** [comment]
the only thing there is the flashcard folder

**Comment by Robz8** [comment]
Check if the SD Card isn't locked.

**Comment by Redswastaken** [comment]
im using micro sd. I have a new 3ds

**Comment by Redswastaken** [comment]
I don't think Micro sd's can be locked

**Comment by Robz8** [comment]
Nope, it can't.
Try formatting your microSD card with 32kb clusters.

**Comment by Redswastaken** [comment]
that's fat32 right?

**Comment by Redswastaken** [comment]
If that's the case I assume I have to take everything of my microsd, format it in fat32 and then put everything back on it?

**Comment by Robz8** [comment]
Yes. Format it to FAT32 with the allocation size of 32 killobytes.

**Comment by Redswastaken** [comment]
my computer is having a hard time transferring some of the files on my sd card that cant be read like nand.bin is there any other options?

**Comment by Robz8** [comment]
Other than this: http://www.codesector.com/teracopy
nope.

**Comment by Redswastaken** [comment]
Could I just try adding banner data? I'm on mac and I don't think I have anyway of making a copy of my sd card.

**Comment by Robz8** [comment]
https://github.com/Robz8/TWLoader/raw/master/gui/romfs/notextbanner
This "No Info" file will have to do.
Name them "gamename.nds.bin".

**Comment by Redswastaken** [comment]
When you say game name should I be use TID?

**Comment by Robz8** [comment]
Nope, rom name.

**Comment by Redswastaken** [comment]
Does this include the file extension ".nds"?

**Comment by Robz8** [comment]
For example, "Super Mario 64 DS.nds.bin", so yes, including ".nds".

**Comment by Redswastaken** [comment]
That wasn't working. Are you aware of any method to change the sd cards allocation size on mac?

**Comment by Robz8** [comment]
Pretty sure your SD card might be corrupted.

**Comment by Redswastaken** [comment]
Well it is now

**Comment by Redswastaken** [comment]
I just formatted it, and tried to transfer my files back over, but there's seem to have been an issue with the transfer because, none of my hacks are working. I'll try to do everything over again and see if that fixes the problem

**Comment by Robz8** [comment]
If TWLoader still stops at the message, the only alternative is [forwarders for HOME Menu](https://gbatemp.net/threads/nds-forwarder-cias-for-your-home-menu.426174/).

**Comment by Redswastaken** [comment]
When I click the floppy drive on the fowarders it says the process suceeded, but I can't find the .cia Also Can I Just skip the step where I dump my cart? I'd rather not Dump a really large 3ds game onto my card if I don't have to.

**Comment by Redswastaken** [comment]
Ok I realized that the fowarder created a file on my desktop called "generated", but when I check there theres's just a folder with a bunch of nds files. ther are no cias in the folder

**Comment by Redswastaken** [comment]
Ok I found my issue in the FAQ's, but Im not sure how to follow the instructions. "A2 (Linux and MacOS users): Execute chmod +x make_cia in the terminal on the .jar file's directory, so that make_cia gets the needed rights to be executed."

**Comment by Redswastaken** [comment]
Nevermind. I fifured it out, but now When I try to launch my games from the home menu. The ds logo comes up, then then the screen turns white and is stuck like that.

**Comment by Robz8** [comment]
Do you have bootstrap.nds in "sdmc:/_nds/"?

**Comment by Redswastaken** [comment]
yes

**Comment by Robz8** [comment]
What's in nds-bootstrap.ini?

**Comment by Redswastaken** [comment]
nothing. It's shown as a document on my computer

**Comment by Redswastaken** [comment]
It's an executable script. Like make_cia

**Comment by Redswastaken** [comment]
would it help if i sent you pictures?

**Comment by Robz8** [comment]
"nds-bootstrap.ini" is in "sdmc:/_nds/", same location as bootstrap.nds.

**Comment by Redswastaken** [comment]
yes

**Comment by Redswastaken** [comment]
_nds is on the root of my sd card and it contains "bootstrap.nds", ds-bootstrap.ini", and "ntr forwarder.ini"

**Comment by Robz8** [comment]
Send a picture.

**Comment by Redswastaken** [comment]
![screen shot 2017-01-27 at 8 23 42 pm](https://cloud.githubusercontent.com/assets/25356208/22393051/b831e2b0-e4ce-11e6-84e3-facdd05b45a8.png)

**Comment by Robz8** [comment]
What's inside "nds-bootstrap.ini"?

**Comment by Redswastaken** [comment]
I don't think I'm picking up what you're putting down. I can't check the contents of the executable.

**Comment by Robz8** [comment]
Attach the file here then, so I can look at it.

**Comment by Redswastaken** [comment]
[nds-bootstrap.ini 2.zip](https://github.com/Robz8/TWLoader/files/736609/nds-bootstrap.ini.2.zip)

**Comment by Robz8** [comment]
The rom path is "Volumes/UNTITLED/roms/nds/Sonic Rush.nds", which is invalid.
Try recreating the forwarders, but disable "Automatically set ROM path", click on the game, and set the rom path to "roms/nds/romnamehere.nds".

**Comment by Redswastaken** [comment]
Ok so I'm just recreating the cias for the roms using your instructions?

**Comment by Robz8** [comment]
Yes.

**Comment by Redswastaken** [comment]
do I have to do the dumping again?

**Comment by Robz8** [comment]
No. If you already dumped the ROM, there's no need.

**Comment by Redswastaken** [comment]
Ummm Sonic Rush works fine. Megaman ZX Advent use to show a flash a black screen with text text on the bottome screen before going completely white. Now it just goes white. Megaman ZX boots into the white screen, and then a black screen appears on the bottom that says creating save data. It then stays on a white loading screen then say "Failed to load datat. Turn off power and reinsert the game card" On both screens with a black background

**Comment by Robz8** [comment]
Take out the currently inserted Slot-1 card.

**Comment by Redswastaken** [comment]
Thanks man. everything seems to be working as planned. Youre godsent!

**Comment by Robz8** [comment]
You're welcome!

**Comment by Redswastaken** [comment]
Anyone I can giveback support? Donations page? Play testing for compatible roms?
