### ISSUE TITLE
Failed to install CIA file (0xD8E0806A)

### ISSUE THREAD

**Issue by MelvinG24** [Robz8/TWLoader#117]
I am trying to install the CIA file inside the "_nds" folder, but the following error appeard:

Failed to install CIA file.
Result code: 0xD8E0806A
Level: Permanent (27)
Summary: Invalid argument (7)
Module: AM (32)
Desc: Cert signature or hash check failed (106)

I download the file again in case that may fix the problem, but the same error appeared.

**Comment by Jolty95** [comment]
Can you tell me what CFW are you using? Emunand? Sysnand? :)

**Comment by MelvinG24** [comment]
Sorry if I do not understand your question, because I am quite new on this. However, I do not using any CFW, I just try to installe it with an custom FBI, whitch I downloaded from this link

https://gbatemp.net/threads/release-fbi-mod-with-fasthax-plus-some-maki-install-cia-legit-on-11-2-o3ds-n3ds.455713/

**Comment by GerbilSoft** [comment]
You can't use TWLoader without CFW. Even if you did manage to get it installed, you'd get an error when rebooting to TWL_FIRM because the TWL-side application isn't signed.

**Comment by Jolty95** [comment]
@MelvinG24 Oh, I understand and don't worry. You need a CFW in order to install TWLoader. Your FBI only can install legit cias, so, I recommend you to follow the guide to downgrade and install A9LH :)

**Comment by MelvinG24** [comment]
Thank you all, for your help . At least now I know what is the problem

**Comment by Jolty95** [comment]
@MelvinG24 your welcome. Closing this for now :)

**Comment by Noobie6942** [comment]
I

**Comment by Noobie6942** [comment]
I keep getting a cia with no image like the cia build is not finishing in godmode9 and then fbi fails almost instantly any ideas im getting annoyed lol. Oh and im trying to put my cartridges on the system

**Comment by Noobie6942** [comment]
T

**Comment by Robz8** [comment]
Are you trying to install the CIA from the TWLoader .7z file?
