### ISSUE TITLE
Missing elements on structs since 6e533e9

### ISSUE THREAD

**Issue by Hakujou** [Robz8/TWLoader#121]
Hi,

As you can see here : https://jenkins.hakujou.fr/job/3DS/job/TWLoader/49/console
There are few missing elements from structs, and the code cannot build. It was building fine before 6e533e9.

**Comment by Jolty95** [comment]
@Hakujou I'll create a PR soon and upload my code to my fork. When I finish fixing those error, I'll create a comment to re do the compilation job :)

**Comment by Jolty95** [comment]
Oh, just to mention. I'm using travis in my fork and there are the same errors so you can watch my travis instead of redoing every commit the job

**Comment by Jolty95** [comment]
I think is solved now. 
https://github.com/Jolty95/TWLoader/commit/d376038f617f02b88193c29a10d90767cedaa0c7
Could you test before I pr, please?

**Comment by Hakujou** [comment]
I don't redo the job manually, Jenkins automatically builds it when a new commit is pushed to the repo :)

Still broken : https://jenkins.hakujou.fr/job/3DS/job/TWLoader/54/console

**Comment by Jolty95** [comment]
I can write directly in this repo but I prefer to do in a fork in case I mess up something :P Travis has ended in my side :)
