### ISSUE TITLE
_nds/twloader/cia folder continuously being recreated after deleting

### ISSUE THREAD

**Issue by Favna** [Robz8/TWLoader#127]
Title says it all. This folder is 9000% useless once TWLNAND-side has been installed yet it is still being recreated every single time, probably through a mkdir.

**Comment by Jolty95** [comment]
That folder is needed when you plan to download an update, if it doesn't exist, twloader doesn't install nothing. I'm going to move that create code to download instead.

**Comment by Jolty95** [comment]
Done. Thanks for notice :)
https://github.com/Robz8/TWLoader/pull/126

**Comment by Favna** [comment]
Closing issue for you then
