### ISSUE TITLE
Update the volume icons

### ISSUE THREAD

**Issue by bakawun** [Robz8/TWLoader#130]
In my pr https://github.com/Robz8/TWLoader/pull/129 i modify the audio mapping to match that of a real DSi, however the volumex.png icons need to be updated to match.

The DSi has 5 volume icons
1. grey speaker and 3 grey dots. Available as volume0.png
2. black speaker and 3 grey dots. Missing
3. black speaker, 1 black wave and 2 grey dots. Available as volume1.png
4. black speaker, 2 black waves and 1 grey dot. Available as volume2.png
5. black speaker, 3 black waves. Available as volume3.png

Now twloader adds a 6th volume icon
6. DSP Firm not found. Available as volume4.png

following are the changed i suggest are made:

1. unchanged as volume0.png
2. new icon named volume1.png
3. current volume1.png renamed to volume2.png
4. current volume2.png renamed to volume3.png
5. current volume3.png renamed to volume4.png
6. current volume4.png removed and replaced with a new volume5.png.

Instead of using the black speaker with the red cross (which implies mute) i sugges that instead we simply write the text DSP? in red.
This will make it much clearer to users there is an issue with the DSP and its not the volume slider being stuck on mute.

**Comment by Jolty95** [comment]
It is not needed to create an issue and a PR both together. 
If you want to add more info, edit the PR message :)

**Comment by bakawun** [comment]
please reopen, I don't create the missing/changed icons in my PR , this ticket is so Robz8, or anyone else  an create them

**Comment by Jolty95** [comment]
Oh ok. I'll create later the new icons. For now, use the same if you wish and later I'll add the new icons :)

**Comment by bakawun** [comment]
Jolly thanks you fixed all the volume icons except for one.

Can you changet this one https://github.com/Robz8/TWLoader/blob/master/gui/romfs/graphics/volume5.png

from being a speaker with an red X to being the word "NoDSP?" in red?
if there is not enough space then just "DSP?"

**Comment by Jolty95** [comment]
Just volume5 or [this](https://github.com/Robz8/TWLoader/blob/master/gui/romfs/graphics/settings/volume4.png) too?

**Comment by bakawun** [comment]
good catch, all the icons in settings should look exactly the same as the others.

so I guess instead of black they should be white?

**Comment by Jolty95** [comment]
I use settings icons in white because I like it more. Also, settings background is dark, so, white is fine :)
Give me some minutes and I'll PR the new DSP icons

**Comment by bakawun** [comment]
just keep volume0 Grey like it is now

**Comment by Jolty95** [comment]
https://github.com/Robz8/TWLoader/pull/134

**Comment by bakawun** [comment]
If you can change these from grey speakers/waves to to white speakers/waves then all is perfect.

https://github.com/Robz8/TWLoader/blob/master/gui/romfs/graphics/settings/volume1.png
https://github.com/Robz8/TWLoader/blob/master/gui/romfs/graphics/settings/volume2.png
https://github.com/Robz8/TWLoader/blob/master/gui/romfs/graphics/settings/volume3.png
https://github.com/Robz8/TWLoader/blob/master/gui/romfs/graphics/settings/volume4.png

**Comment by Jolty95** [comment]
Them are fine just like are now and I like them more in grey than in white (because when I add the volume icon support I tested with white volume icon and I dislike the way it was)

**Comment by bakawun** [comment]
We want to have consistency here.
So in the normal menu grey means no sound and black means sound.
In the settings menu we need to do the same, one color for no sound and another for sound.

If you want to stick to grey for having sound then the no sound https://github.com/Robz8/TWLoader/blob/master/gui/romfs/graphics/settings/volume0.png should be made a different color, and all the dots in the other files should have the same color too.

**Comment by Jolty95** [comment]
Ok but nobody has complain about the color of an icon before. I'll update the texture that @Robz8 wants because I think he is the only one to say which textures should we use.

**Comment by bakawun** [comment]
The change i am trying to make here is to make the volume icons behave and look the same as they did on a real DSi.

Here is a screenshot of a real DSi settings menu, as you can see here the volume icon is white.

![Image of Dsi](https://bloguedegeek.net/wp-content/uploads/2009/04/dsiguide_settings.jpg)

**Comment by Jolty95** [comment]
Ok. I'll do volume1 to 4 in settings romfs un White but tomorrow morning. It's late in my country.

**Comment by Robz8** [comment]
The background can be easily recreate-able, so I'll fix the background.

**Comment by Jolty95** [comment]
This can be close now.
