### ISSUE TITLE
Donor Rom option has nothing that shows it's worked.

### ISSUE THREAD

**Issue by Lykie** [Robz8/TWLoader#131]
Pressing A on "Set as donor ROM" does nothing, some roms say "Default" and others have nothing under it.
edit: it looks like it does work but there's nothing telling you that it did work. Add a menu thing that tells you that it's set a donor rom?
edit2: donor rom option loaded me into the donor rom very slowly for some reason?
edit3: now my settings.ini has randomly corrupted

**Comment by Jolty95** [comment]
Should be fix in next version :)
https://github.com/Robz8/TWLoader/pull/126

**Comment by Robz8** [comment]
Version 3.2 has been released.
