### ISSUE TITLE
Error when selecting game with DSTT

### ISSUE THREAD

**Issue by FedangleBoy** [Robz8/TWLoader#132]
When I try to select a ROM in the flashcart adding selector, a red screen appears on the bottom screen where it says "Guru Meditation Error! data abort!" with lots of numbers down at the bottom. http://imgur.com/s1jAhx6

**Comment by Robz8** [comment]
Does it happen before the .ini file is created?

**Comment by FedangleBoy** [comment]
yes @Robz8

**Comment by chofstede** [comment]
Same problem here. It worked fine on Version 3.0.2. Now I upgraded to 3.1 and cannot add any game.
The new twloader.nds was put on the NDS Flashcard.

Flashcard: R4I-SDHC 3DS RTS (r4i-sdhc.com)

I tried ~5 different games. Always get "Guru Meditation! on a fully red screen.

**Comment by deadair3210** [comment]
Same problem here, worked fine until updated to latest. Guru error

Flashcard: R4i-SDHC 3DS

**Comment by Robz8** [comment]
The issue should be fixed in v3.2.
