### ISSUE TITLE
Launching Slot-1 card crashes to HOME Menu

### ISSUE THREAD

**Issue by Robz8** [Robz8/TWLoader#135]

**Comment by Jolty95** [comment]
Using CTR card crash it too

**Comment by Jolty95** [comment]
@Robz8 I found were is crashing. 
This is causing the crash:
> char game_TID[5];
> grabTID(f_nds_file, game_TID);
> game_TID[4] = 0;
> game_TID[3] = 0;
> fclose(f_nds_file);

**Comment by chronoss09** [comment]
Samething on me too :(

**Comment by Jolty95** [comment]
@chronoss09 This is already solve in repo. Next release version will fix it :)

**Comment by bakawun** [comment]
fixed with https://github.com/Robz8/TWLoader/commit/f72f59be999d729075d1e9c47c4798fdb5111f68
ticket can be closed
