### ISSUE TITLE
No start button

### ISSUE THREAD

**Issue by samualtnorman** [Robz8/TWLoader#138]
When I'm on game select screen there is no start button for selecting a game apart from on settings. I have not found anyone else who has encountered this problem, am i doing something wrong?

http://imgur.com/hWOp7Wj

**Comment by Jolty95** [comment]
@samualtnorman what TWLoader version are you using?

**Comment by samualtnorman** [comment]
The latest 3.1

**Comment by Jolty95** [comment]
The picture you send is from roms from SD or flashcard? 
Also if you can, would be great if you can add more roms to help me testing and find what is causing that strange behavior :)

**Comment by samualtnorman** [comment]
It's on the SD card and I will do, thankyou @Jolty95

**Comment by samualtnorman** [comment]
I have added 7 more games and I am still encountering the same problem.

**Comment by Jolty95** [comment]
Can you try deleting TWLoader from FBI and reinstalling? Also download TWLoader.7z latest release and put a new _nds folder in SD:\root

**Comment by samualtnorman** [comment]
Will do. Thanks again!

**Comment by samualtnorman** [comment]
I have not been using FBI, I have been using the .3dsx of twloader and placing it in 3ds in homebrew, does that matter?

**Comment by Jolty95** [comment]
That's why it wasn't working :P
.3dsx file is a DEMO aka is useless to rom loading. You need CFW and to install the .cia version in order to use TWLoader with rom loading functions :)

**Comment by samualtnorman** [comment]
Just to confirm, I use .3dsx version of cia to install .fbi version of cia

**Comment by samualtnorman** [comment]
Sorry I am noob at this

**Comment by Jolty95** [comment]
I don't understand your problem. Do you have FBI and a CFW?

**Comment by samualtnorman** [comment]
I have a CFW but I do not have fbi

**Comment by Jolty95** [comment]
You need FBI (or another program that can install cia files)

**Comment by samualtnorman** [comment]
I know but how do i get fbi? I followed this guide, http://wololo.net/2016/07/24/3ds-install-fbi-cia-files/, but i receive this error... Unsupported firmware version.

**Comment by Jolty95** [comment]
Follow the official guide for CFW http://3ds.guide/ is available also in multiple languages :)

**Comment by samualtnorman** [comment]
Thank you for putting up with me so far, I'm doing it this way and I'll get back to you tomorrow.

**Comment by samualtnorman** [comment]
Thank you @Jolty95 I have it all set up now.
