### ISSUE TITLE
Feature Request: Allow icon reordering (like on a real DSi)

### ISSUE THREAD

**Issue by bakawun** [Robz8/TWLoader#139]
On a real Dsi the direction pad has the following effects:

Left > move 1 icon to the left
Right > move 1 icon to the right
Down > nothing happens
Up > the icon moves up replacing the application name

With the icon up you can move it left/right and press down to place it in another position

Please implement this feature into TWLoader.

Here is the DSi manual entry with pictures.
http://en-americas-support.nintendo.com/app/answers/detail/a_id/3962/~/how-to-arrange-application-icons

**Comment by Robz8** [comment]
That might not be possible.

**Comment by Robz8** [comment]
I can make the icon jump up and back down with Up button, though,

**Comment by tetsuo55** [comment]
Did you close by accident?

**Comment by Robz8** [comment]
No.

**Comment by bakawun** [comment]
is there any way to create a custom order for the games?
