### ISSUE TITLE
Flashcard does not appear in list

### ISSUE THREAD

**Issue by deadair3210** [Robz8/TWLoader#14]
I have a R4i 3DS, this one does not have the RTC, and I cannot find it in the list.

Is it supported or is it in the works?

**Comment by Robz8** [comment]
It's supported. Try the www.r4i-sdhc.com one.

**Comment by deadair3210** [comment]
I'm sorry, but I don't understand, If you are referring to the r4's kernel, then I already have the latest version as of 5 days ago

**Comment by Robz8** [comment]
www.r4i-sdhc.com in the list.

**Comment by deadair3210** [comment]
Thanks for the help, worked fine
