### ISSUE TITLE
Error has occurred on N3DS V11.2.0-35U Luma CFW + A9LH

### ISSUE THREAD

**Issue by Shadowehh** [Robz8/TWLoader#140]
Every time I load a NDS file, the screen appears to start, but then I get, "**An error has occurred. Press and hold the POWER Button to turn the system off. Please refer to the Operations Manual for details.**". I currently have a N3DS on version 11.2.0-35U that has Luma CFW with A9LH. I am also on the latest version on TWLoader as well and this has been happening on every version of TWLoader. I also tinkered with the settings in hope of it fixing it, but no luck.

**Comment by Jolty95** [comment]
Have you installed TWLNand side?

**Comment by maorninja** [comment]
Sigh....

Please, Robz8, for the sake of not having as much cancer as this, please make it clear that if you didn't read the instruction, you will not get help...

At OP, **Start reading instructions!!!**

> (This step is required. An error screen will appear if this isn't installed.) Install "TWLoader - TWLNAND side.cia" that's in "sdmc:/_nds/twloader/cia/" to SysNAND (also to EmuNAND, if you have EmuNAND).

Is this step too hard? Seriously, its annoying...

**Comment by gaiaweylyn** [comment]
I just went into FBI > SD and clicked install on it. I can only assume it's working properly at that point. I can get the select few working roms to boot. It's odd, since I think I did get that error once, even after doing this. It went away after I restarted TWLoader and ran the game again.

**Comment by bakawun** [comment]
maybe there is a way to check if the twl nand side has been installed or not

**Comment by maorninja** [comment]
There is.

Go to FBI > Titles, and scroll to the blue part at the end...

**Comment by bakawun** [comment]
glancing at http://smealum.github.io/ctrulib/am_8h.html suggest we can check it nand side is installed or not and maybe even check the version.

it also looks like we can install the nand side from within the twloader gui.

so to me it seems the install process and verification can be completely automated
