### ISSUE TITLE
Add missing bootlogo and HS screens for China and Korea

### ISSUE THREAD

**Issue by bakawun** [Robz8/TWLoader#141]
The chinese DS and DSi are called IQue DS and IQue DSi
They use a completely different logo.

For both the chinese (only in simplified) and korea the HS screen is missing.

For reference here is a video showing the IQue Dsi
http://www.ique.com/DSi/intromovie_DSi.htm

**Comment by bakawun** [comment]
@Robz8 @Jolty95 

I think we should label this one as help wanted

**Comment by Jolty95** [comment]
Done

**Comment by tetsuo55** [comment]
Why did you remove Korean bootlogo from the title?

**Comment by bakawun** [comment]
Why did you remove the health and safety for china and korea from the title?

**Comment by Robz8** [comment]
I thought you meant the health and safety for china and korea doesn't exist, so I just gave the languages white screens.

**Comment by bakawun** [comment]
Oh i see now.

No what i mean exactly, is that there are H&S screens specifically for china and korea, but we don't have them.
Additionally the DS and DSi logo on the top screen is different for china

**Comment by Mayoshiroi** [comment]
![iquedshs](https://cloud.githubusercontent.com/assets/19636055/25312341/762fbad6-2849-11e7-83a4-0908af22a66a.png)
![ndsihs_kr](https://cloud.githubusercontent.com/assets/19636055/25312342/766d2e16-2849-11e7-8da8-499fc323f1a0.png)
HS screens, from online pdf mannual

**Comment by Robz8** [comment]
Nice! Thanks.

**Comment by Robz8** [comment]
@Mayoshiroi Can you find the screens in their native resolution? I tried scaling them down, but they still look horizontally blurry.

**Comment by Mayoshiroi** [comment]
Sorry for the late reply.
I just find them in pdf manual, maybe it has been scaled. I don't have Korean and Chinese version NintendoDS, so I don't know how to get their native resolution.

**Comment by Robz8** [comment]
That's okay. Since the boot screen has moved to the GUI, I won't need them in their native resolution.

**Comment by Jolty95** [comment]
Now this can be closed @Robz8 ?

**Comment by Robz8** [comment]
OK.
