### ISSUE TITLE
Feature Request: Allow (user selectable) background music (like on a real DSi)

### ISSUE THREAD

**Issue by bakawun** [Robz8/TWLoader#142]
Please add a feature to have background music playing while TWLoader is running.

This feature was just implemented in that eshop clone if you want to see how its done.

**Comment by maorninja** [comment]
Sigh.

I think that there should be an "issue" called **READ THE WIKI BEFORE POSTING!!!**

This is already a thing.

Besides, this discussion should go on GBATemp, as this is a place for issues, not a discussion place...

**Comment by bakawun** [comment]
the wiki is not shown on the mobile page.
but I found it on step8 of the install guide

this is not discussion by the way, I am working on creating feature and function parity with a real DSi

**Comment by maorninja** [comment]
There is a file called the ReadME. Its called like that for a fucking reason...

And yes, this is a discussion, as the tab says "Issues" for a fucking reason...

**Comment by GerbilSoft** [comment]
@maorninja Cut the crap. We don't need you to berate everyone who doesn't read every single thing.
