### ISSUE TITLE
Turns out this is coming this Christmas!

### ISSUE THREAD

**Issue by rpalmon** [Robz8/TWLoader#15]
https://www.youtube.com/watch?v=Pke0kalpoBU 

This is an NDS rom player. Once this becomes open source, will you implement it to your project so it will have a nice UI when choosing a rom?

**Comment by rpalmon** [comment]
https://www.reddit.com/r/3dshacks/comments/5iz5q7/nds_rom_loader_soon/ reddit thread too.

**Comment by Robz8** [comment]
Yes! I will implement it.

**Comment by rpalmon** [comment]
Cool, can't wait! Also, I'm guessing this will be version 2.0 right?

**Comment by Robz8** [comment]
Yes.
