### ISSUE TITLE
NDS partner program (flashcard-side) keeps glitching

### ISSUE THREAD

**Issue by deadair3210** [Robz8/TWLoader#150]
Updated to the latest version today, now instead of it flat out dying with a error, its doing weird things like freezing after adding one game, and showing nothing in the folder after it adds the game if it doesnt freeze

**Comment by Robz8** [comment]
That's an issue I can't seem to fix. Sorry.

**Comment by Robz8** [comment]
On second thought, I have an idea that might fix this issue.

**Comment by deadair3210** [comment]
Ok, just to let you know, the 3ds app is also randomly stuck trying to update all the time, even though its already up to date

**Comment by hectortillo** [comment]
Jolty95 already patched it out in a PR :) the next version release you should update manually by FBI and it should work properly from now on :)
