### ISSUE TITLE
Add game : freeze on a second game

### ISSUE THREAD

**Issue by chronoss09** [Robz8/TWLoader#151]
Add game work now with the last build but you can't add 2 game, the 3ds freeze and you must quite twloader for add asecond game :(

**Comment by Jolty95** [comment]
Are you using latest v3.2.1?

**Comment by chronoss09** [comment]
Not yet. I'm on 3.2 now...

**Comment by chronoss09** [comment]
Samething with the 3.2.1, freeze with the second game 👎

**Comment by hectortillo** [comment]
Do you have put all the updated files (the new ones) on the correct path? :) i havent tested it now but probably is that. :)

**Comment by chronoss09** [comment]
yes, i'm on 3.2.1 and all new file are installed :(

**Comment by hectortillo** [comment]
Then we should close this issue ? :)
