### ISSUE TITLE
3DS crashes when TWL side of app is updated by the updater

### ISSUE THREAD

**Issue by deadair3210** [Robz8/TWLoader#152]
Happens as of latest update 3.2.1

If you use FBI to install the TWLNAND side, it seems to install fine, but if you go into the app and set the app to autoupdate,and set the nds bootstrap to release, the next time the app boots it will look for updates, update the app to the newest version and then attempt to update the TWL side only to hit a error and crash the 3ds to the point that the user has to reboot
![img_20170201_203246](https://cloud.githubusercontent.com/assets/1053504/22537856/8b09603e-e8d3-11e6-9aee-9cc943453d7d.jpg)

**Comment by Margen67** [comment]
What entrypoint are you using?
Are you using emuNAND?

**Comment by Barawer** [comment]
I had the same problem, running the CIA version. using luma and no emunand.

**Comment by Jolty95** [comment]
It's solved in latest PR ;)
