### ISSUE TITLE
Add full translations

### ISSUE THREAD

**Issue by chronoss09** [Robz8/TWLoader#153]
I can help you to translate twloader in french because the french language is not completed. Tell me just why to do and i will make my best...

**Comment by bakawun** [comment]
currently the following strings are translatable
https://github.com/Robz8/TWLoader/blob/master/gui/source/language.cpp#L40

**Comment by chronoss09** [comment]
Thanks but GUI is imcomplet and i can't see NTR/TWL-mode setting...

**Comment by Jolty95** [comment]
@chronoss09  Only English is fully translate. Is in my TODO list for next release tho

**Comment by chronoss09** [comment]
So, with the next release, we can translate all menu for TWLoader ?

**Comment by Jolty95** [comment]
I'm trying to translate it, but ex, my language is spanish so other languages for me can be a bit difficult. Also atm I'm trying to fix some bugs but I hope translations get finish asap :)

**Comment by chronoss09** [comment]
Send me a txt file and i will make my best to help you with the french language

**Comment by Jolty95** [comment]
I'm working on the PR right now but when I finish I'll tell here. Also, I need help with other languages so if anyone want to help....

**Comment by chronoss09** [comment]
ok, i'm waiting for.....

**Comment by bakawun** [comment]
@Jolty95 you don't have to translate any other languages, just keep it all English for the rest and wait for people to provide translations

**Comment by chronoss09** [comment]
@bakawun : good thing 👍

**Comment by mariogamer2** [comment]
@chronoss09 Hey don't do the full translation please (or,in another word: leave me something xd).

**Comment by Valeri0p** [comment]
Emh...there is an error in the Italian translation:

`"Motivo",               	// "Language" 
	"Theme",					// "Theme"
 `
Should be:
`  "Lingua",               	// "Language"
	"Motivo",					// "Theme"
`
Anyways, I think that "Tema" is a better translation than "Motivo".

**Comment by Jolty95** [comment]
I'm going to close this because translations will be available soon.  I still need some help [here] (https://github.com/Robz8/TWLoader/issues/188)

**Comment by diegobalbine** [comment]
i can help to translate in portuguese-br
