### ISSUE TITLE
Denor Rom bouton

### ISSUE THREAD

**Issue by chronoss09** [Robz8/TWLoader#154]
It make any affect when i press A inside...

**Comment by Jolty95** [comment]
what do you mean? After pressing set/unset donor rom, it works automatically

**Comment by chronoss09** [comment]
Can you tell me if i press A to Donor Rom, what can i must see ?

**Comment by Jolty95** [comment]
If you touch/press A to set Donor Rom the dialog box autoclose. I mean that no text saying if correct/fail appear. It's all transparent.

**Comment by hectortillo** [comment]
You will see how dissapear the menu and bringa you back to Rom selection :) (that is the signal that it worked ) :)

**Comment by chronoss09** [comment]
Now it work, thanks ;)

**Comment by hectortillo** [comment]
You're welcome :)  if there is not more problems i think we should close this issue :)  @chronoss09
