### ISSUE TITLE
[REQUEST] Multiple request

### ISSUE THREAD

**Issue by chronoss09** [Robz8/TWLoader#159]
1- Is it possible to make a combo button to return to TWLoader after launching a game or after add a game to TWLoader ?

2- Make if possible a button to delete a game added on TWLoader.

3 - Possibility to switch to different bootstrap with Select boutton on the game (same boutton as Donor Rom)

4 - Make a cheat fonction for YSMenu on TWLoader with Select boutton on the game (same as Donor Rom)

For me, make a CPU Speed on default (max 133MHz) for all game in TWLoader and the change this boutton to other thing...

Sorry, i don't know how to make a request in "Pull requests" :(

**Comment by bakawun** [comment]
Pull request are used for when you write code changes and want to commit them to the project.

**Comment by Robz8** [comment]
1. No. That requires hacking TWL_FIRM, which is currently hard to do.
2. Maybe.
3. Probably not a good idea.
4. No.

**Comment by chronoss09** [comment]
Ok thanks alot :)
