### ISSUE TITLE
dependencies needed for building?

### ISSUE THREAD

**Issue by mariogamer2** [Robz8/TWLoader#16]
I already know devkitkarm,but some library still needed. I cannot build everything with it. Does it need some thing like citrus or anything?

**Comment by Robz8** [comment]
You need to install sf2lib, portlibs, sftdlib and sfillib.

**Comment by mariogamer2** [comment]
portlibs must contain what exactly? The base from sourceforge?

**Comment by Robz8** [comment]
https://github.com/xerpi/3ds_portlibs

**Comment by mariogamer2** [comment]
Can I use the "official" portlibs?

**Comment by Robz8** [comment]
You need ahezard's libnds.

**Comment by mariogamer2** [comment]
Ok thank I'll test soon.

**Comment by rpalmon** [comment]
I would like to try building it too. How do I install sf2lib, portlibs, sftdlib and sfillib?

**Comment by Robz8** [comment]
README has been updated.

**Comment by mariogamer2** [comment]
Just like this... bootstrap-dldi from sdroot/_nds folder is more long than bootstrap.nds given by building twlapp. From what does he came?

**Comment by mariogamer2** [comment]
So?

**Comment by Robz8** [comment]
So what?

**Comment by mariogamer2** [comment]
My last question.

**Comment by Robz8** [comment]
What file built bootstrap.nds?

**Comment by mariogamer2** [comment]
sdroot/_nds/bootstrap_dldi.nds (or card) is a bit shorter thatn generated twlapp/bootstrap.nds (here,I think it's not the same thing?) and generating from initial nds-bootstrap give a file longuer...

**Comment by mariogamer2** [comment]
sdroot/_nds/bootstrap-dldi.nds (or card) is a bit shorter thatn generated twlapp/bootstrap.nds (here,I think it's not the same thing?) and generating from initial nds-bootstrap give a file longuer (like + 600 kb)...

Anything?

**Comment by Robz8** [comment]
Ignore the "twlapp/bootstrap.nds" file, if it's generated. I'm not getting that file.

**Comment by mariogamer2** [comment]
So from where it come? (the sdroot/_nds/bootstrap.nds)

**Comment by Robz8** [comment]
A compiled bootstrap.

**Comment by bakawun** [comment]
If the instructions on the wiki or Readme. MD are clear enough this ticket can be closed.

if not then they should be updated. 

for the most part Travis.xml contains the most detailed requirements for building
