### ISSUE TITLE
small issue when exiting the "search" feature

### ISSUE THREAD

**Issue by capito27** [Robz8/TWLoader#166]
When backing from the "search" feature on the GUI part, you get always taken to the 3rd slot on the list, which sometimes places you outside of the list in the gui (like if you don't have any flashcard games and are on flashcard rom list), this is totally minor, but mildly annoying :)

**Comment by Jolty95** [comment]
@capito27 Sorry the delay.
I'm unable to reproduce the problem. Would you mind to write the steps to reproduce it? :)

**Comment by capito27** [comment]
sure thing, open TWLoader, select flashcard as a game location, while not having any .ini file for flashcard roms, then select the search option, press cancel, and you'll be on the third place of the bottom screen list. here is a picture of the end result (ignore the reported date on the 3ds) : http://i.imgur.com/4Av31td.jpg
let me know if you need anything else, the issue was present on the latest (3.3) version.

**Comment by Jolty95** [comment]
Oh, I see
Thanks for report ;)
Actually, search function is not implemented for flashcard side (yet) that's why the cursor is there.

**Comment by Jolty95** [comment]
https://github.com/Robz8/TWLoader/pull/174 :)
