### ISSUE TITLE
App crashes with Data Abort when source is changed

### ISSUE THREAD

**Issue by deadair3210** [Robz8/TWLoader#168]
After I deleted the settings file and let the app recreate it, the app now crashes anytime I try to change the source from SD card to Flashcard.

**Comment by Robz8** [comment]
What happens if you set FORWARDER in [TWL-MODE] to 1 in "sdmc:/_nds/twloader/settings.ini"?

**Comment by deadair3210** [comment]
Immediate Data Abort, would the crash dump help?

**Comment by Robz8** [comment]
Dunno. Please attach it.

**Comment by deadair3210** [comment]
Do you need any other files other than the dump?

**Comment by Robz8** [comment]
No, just the dump.

**Comment by deadair3210** [comment]
Uploaded
https://mega.nz/#!xUcw3LCZ!aVdGqm5hkZUFRxnFZz8KxZkdOPbeiYyGKvux-E2jEZQ

**Comment by Robz8** [comment]
Hmm, try deleting your flashcard game .ini files.

**Comment by deadair3210** [comment]
Completely deleted _nds folder, can switch fine now

**Comment by Robz8** [comment]
Good to know.
