### ISSUE TITLE
Error "Press the POWER button" when I try to update TWLoader

### ISSUE THREAD

**Issue by Clement95** [Robz8/TWLoader#173]
When I try to update TWLoader, the Nintendo error message appears, something like "Press the POWER button." My console crash precisely when TWLoader NAND Size tries to update itself, it repeats the same thing during the auto update at startup

**Comment by Robz8** [comment]
That should be fixed in the latest version, so no idea why it's happening to you.

**Comment by Jolty95** [comment]
Install latest cia version for GUI and NAND side manually. That error it's fixed in latest version.

**Comment by bakawun** [comment]
This was fixed in 3.3 but unfortunately it cannot update itself to the new version because of the bug.
Installimg manually like @Jolty95 said should solve the issue.

Issue can be closed
