### ISSUE TITLE
Unable to use "Add Games" with my Acekard 2i

### ISSUE THREAD

**Issue by capito27** [Robz8/TWLoader#177]
Hi, i've followed the initial installation guide from the wiki and the specific part for flashcards, i've dowloaded the appropriate pack for my flashcard from the list (the fourth one from the top), i've copied to my flashcard's SD card root the appropriate _nds folder and the GBArunner file, i've selected the right flashcard list from the GUI title. 
I'm able to launch titles from the 3ds SD card (Mario 64 DS namely), so it shouldn't be an installation problem. 
Whenever i try to use the  "Add Games" feature, it will boot into twlmode, do a bit of console logging on the bottom screen, and then freeze at a white screen. 
I've tried messing with the settings, changing the card slot reset option and the ARM9 CPU speed mode.
Finally, my flashcard is in working state, as i'm able to boot into it from home menu and launch games with it.

Does any of you have any suggestions as to why it doesn't work ?

Edit : I'm currently on TWLoader version 3.3.1, with the latest bootstrap (unofficial and official bootstraps are, at the time of writing, the same commit)

Edit 2 : running manually the twloader.nds file in my flashcard's SD card from the flashcard gives me access to the add games menu, but obviously, it's unable to save the ini files to the 3ds SD card.

**Comment by Jolty95** [comment]
@capito27 For the time I'm writting this, I forget to update the wiki some days ago (I was bussy to).
Follow the steps from [here](https://gbatemp.net/threads/twloader-ctr-mode-nds-app.448375/) until I update the wiki again :)

**Comment by capito27** [comment]
i've followed the flashcard secton on gbatemp, eventho it's relatively the same as the part of the wiki, i've replaced everything on my flashcard sd card with the AK2i pack and have copied the appropriate _ntr folder  to it, i've also copied the ntr_forwarder.ini file to my 3ds's sd card, in the _ntr folder. still the same issue of white screen when trying to add games.

**Comment by Jolty95** [comment]
Maybe @Robz8 can you better with this ;)

**Comment by Robz8** [comment]
It works for some users, actually, so I dunno. I don't own an Acekard 2i.

**Comment by capito27** [comment]
i may have an idea about why it may not work for me ; the AK2I had 2 HW revisions, HWID 44 and HWID 81 , per this gbatemp page : https://wiki.gbatemp.net/wiki/Updating_the_AK2i_Bootloader, i have the HWID 81 revision, according to my current card icon being "Pippa Funnell", so my theory is that the other people are using the HWID44 and working fine, yet the HWID 81 is not working properly.

Not quite sure how to do something about that tbh

**Comment by VlivesRaw** [comment]
DSTT here, same issue with the white screen - can launch previously added games though. Adding games stopped working after the update from 3.X.X to 4.1.0

**Comment by Robz8** [comment]
Install TWLNAND side from the latest 7z file.

**Comment by capito27** [comment]
just letting you know i updated everything to the latest version (twloader, GUI&TWLNAND both, i replaced the flashcard files properly and deleted the _nds folder before setting everything back up), still white screen when trying to launch "add games", after the "DSi BIOS"

**Comment by Robz8** [comment]
It takes some tries. The next release should fix that.

**Comment by NaaChill** [comment]
Seems as if the latest version broke Acekard compatibility. I suppose this ticket will be closed once support is back online.

**Comment by Robz8** [comment]
Actually, I don't think it worked in the first place.
