### ISSUE TITLE
Always shows empty battery

### ISSUE THREAD

**Issue by OctoNezd** [Robz8/TWLoader#18]

**Comment by Robz8** [comment]
Sadly, I have no idea how to fix this.

**Comment by Jolty95** [comment]
@Robz8 just an estupid question: in this line 
https://github.com/Robz8/TWLoader/blob/master/source/main.cpp#L2640
`PTMU_GetBatteryLevel(&batteryLevel)` is a value between 0-5. Shouldn't you just compare with an equal instead of a R_SUCCEEDED?

**Comment by Robz8** [comment]
Your code fixed the issue! Thanks!
