### ISSUE TITLE
Delete game add to flashcard

### ISSUE THREAD

**Issue by chronoss09** [Robz8/TWLoader#181]
For some reson, i want delete some game added to TWLoader but i can't. Is it possible to make deleting option in the news release ?

**Comment by Margen67** [comment]
You can use FBI to delete them.

**Comment by chronoss09** [comment]
How to delete them with the FBI?

**Comment by Robz8** [comment]
Press SELECT (I think) on the .ini file, and select "Delete".

**Comment by Jolty95** [comment]
https://github.com/Robz8/TWLoader/pull/262

This can be closed (at least code is there if someone wanna copy ;) )
