### ISSUE TITLE
TWLoader showing that "The sd card has been removed"

### ISSUE THREAD

**Issue by Theorvolt** [Robz8/TWLoader#184]
After updating to TWLoader 3.3.1 and nds bootstrap 0.4.0 and relaunching, it displays that the sd card has been removed. I have checked this sd card and confirm it is not corrupted. If I reinstall TWLoader, it will open and remain at TWLoader until I turn it off. This seems like a one-of probelm and not a general bug.

**Comment by Robz8** [comment]
The issue should be fixed in the next version.

**Comment by Theorvolt** [comment]
It seems that wasn't the end. After uninstalling both TWLoader and TWL side and reinstalling, it fails to install TWLoader. TWLside works but TWLoader keeps showing the following error:

Failed to install CIA file:
Result code: 0xD8E0806A
Level: Permanent (27)
Summary: Invalid argument (7)
Module: AM (32)
Desc: Cert signature or hash check failed (106)

**Comment by Jolty95** [comment]
@Theorvolt what CFW are you using?

**Comment by Theorvolt** [comment]
Luma.

**Comment by Jolty95** [comment]
Give us more details. Model of the console, your entrypoint, A9LH? Emunand?

**Comment by Theorvolt** [comment]
2ds on 11.2.0.33-E. No emunand, of course there is A9LH. Also I am installing as a cia.

**Comment by Jolty95** [comment]
I asked you because some users try to launch FBI from HBL or without A9LH in a weird configuration.
You have a problem with your SD card. Try to re-download again the .cias from release pages. If it's saying the same error, it's your SD card that's fake, damage, or doesn't have space left

**Comment by Theorvolt** [comment]
for the legitamacy of the sd card, its certainly real. I have tested it and it isnt corrupted either. Yes I have tried redownloading the cia file and reinstalling both TWLoader and the twl side cia. But still stuck on the failed to install screen.

**Comment by Jolty95** [comment]
I'm 99% sure it's your SD card or your console SD slot. If you have a New (it seems that you're using one) maybe it's your console that isn't reading correctly your SD card. If you can, try with another SD card. There is nothing more I can do from here.

**Comment by Theorvolt** [comment]
New? Im using a 2ds. Anyway, I will do more testing and contact you if anything else pops up.

**Comment by Jolty95** [comment]
Oops sorry for that. I was thinking in the SD slot and I thought it was a New. Sorry you have this problem.

**Comment by Margen67** [comment]
@Theorvolt How did you test your SD card?

**Comment by Theorvolt** [comment]
FakeFlashTester.
