### ISSUE TITLE
missing boxart

### ISSUE THREAD

**Issue by killer983** [Robz8/TWLoader#186]
Some boxart is missing in some games puts downloading and then does not show them (twloader 3.3.1)
![20170212_102808](https://cloud.githubusercontent.com/assets/25202703/22860995/0eb2e3a0-f10e-11e6-8c11-7aa432992437.jpg)
![20170212_102350](https://cloud.githubusercontent.com/assets/25202703/22861000/2c32eb28-f10e-11e6-821a-890bc532b1bb.jpg)

**Comment by hectortillo** [comment]
Which regionnare thebganesbthat havent boxart?

**Comment by killer983** [comment]
Fifa 11 europe
mario kart ds europe
New super mario bros europe
rafa Nadal tennis europe
sonic colors europe
tamagotchi conexión comer shop 2 europe
tetris ds  europe
tetris party deluxe europe

**Comment by hectortillo** [comment]
try this. change the language in settings to english. close the app and retry to open it. i had the same issue   i dont know why but it worked :)

**Comment by Robz8** [comment]
Not all box art are uploaded.

**Comment by killer983** [comment]
Ok, They are not all boxart
