### ISSUE TITLE
can I push korean translate branch?

### ISSUE THREAD

**Issue by decinc** [Robz8/TWLoader#195]
I create korean.h for korean translation.

but I dont have push branch permission.

this is header file, but I can't upload language.cpp and settings.cpp because you will be hard to diff with original source.

this is my working file for korean translate.

[korean.h.txt](https://github.com/Robz8/TWLoader/files/770158/korean.h.txt)

**Comment by Jolty95** [comment]
I can add to my PR and credit you if you want. Only @Robz8 and me have push permission to this repo.

**Comment by decinc** [comment]
yes, please add to your PR. thank you.

**Comment by Jolty95** [comment]
https://github.com/Robz8/TWLoader/pull/196
Done :)
