### ISSUE TITLE
I suggest not to make version numbers like 1.6.0b

### ISSUE THREAD

**Issue by rpalmon** [Robz8/TWLoader#20]
Hello, the reason I am asking this is because when I went to the homebr3w browser app on 3DS, when I search this app, it says that it is on the latest version which says 1.6.0.   Not 1.6.0b. I would maybe suggest changing it to 1.6.1 or 1.7.0.

I am asking this because I would like to update this app when I don't have my computer around me.

**Comment by Robz8** [comment]
I didn't have time to do any actual changes to the GUI.

**Comment by rpalmon** [comment]
Can you maybe change the version number to 1.6.1 so that homebr3w browser could see that it updated?

**Comment by Robz8** [comment]
Fixed.

**Comment by rpalmon** [comment]
For some reason homebr3w browser still says that there isn't an update.

**Comment by YodaDaCoda** [comment]
Homebr3w doesn't go by version numbers. It uses TitleDB's API, which tells when an update was last released. You can expect TitleDB to lag somewhat.
