### ISSUE TITLE
Set rom path from settings GUI

### ISSUE THREAD

**Issue by Margen67** [Robz8/TWLoader#200]
As of https://github.com/Robz8/TWLoader/commit/e926472491a9ed08f433f555f938fbd519acf6f2 to set the rom path you need to edit the settings file manually outside of the app.

**Comment by Jolty95** [comment]
@Margen67  Sorry but I don't understand your question

**Comment by Margen67** [comment]
To set the designated rom path for TWLoader to load NDS roms from you have to edit the settings.ini file outside of TWLoader.

**Comment by Jolty95** [comment]
Oh, sorry for not understanding before. The reference commit was confusing me. I can add it in settings today or tomorrow (I'm a bit bussy atm) :)

**Comment by Jolty95** [comment]
@Margen67  Something like this? (It's a WIP)

![bot_0000](https://cloud.githubusercontent.com/assets/21294047/22971108/e07203ae-f374-11e6-9301-6838594bc453.png)

**Comment by bakawun** [comment]
Yes that looks good

**Comment by Jolty95** [comment]
@bakawun  I'm on it, wait please xD

**Comment by maorninja** [comment]
> What happens when the path you want to use does not exist yet?

Maybe TWLoader can alert the user that they don't have the folder and ask them if they want to make the folder??

**Comment by Jolty95** [comment]
@Margen67 sorry the delay. https://github.com/Robz8/TWLoader/pull/210
@maorninja , I'm on it too :)

**Comment by maorninja** [comment]
@Margen67, um, no.

I didn't downvote because a) this is actually adding content, and b) you aren't pulling your "EmuNAND peasents go A9LH" way.

**Comment by Margen67** [comment]
I only tell people to go to A9LH+SysNAND using 3ds.guide because it's safer, better, AND solves their problem.

Telling by the fact that using 3ds.guide has actually solved problems MULTIPLE times
https://github.com/Robz8/TWLoader/issues/213#issuecomment-280820041
https://github.com/Robz8/TWLoader/issues/55#issuecomment-273006717
https://github.com/Robz8/TWLoader/issues/138#issuecomment-276198420

It only doesn't help them if they're stubborn, don't do any research, refuse to take good advice, and can't help themselves, like here: https://github.com/AuroraWright/Luma3DS/issues/366

Why you would _want_ them to use unsafe entrypoints such as MSET or menuhax is beyond me.
There aren't any good reasons to not install A9LH unless you're a developer, or something.
Otherwise A9LH is objectively superior.

You spreading this misinformation that "you dont need a9lh" is dangerous and will lead to people updating their sysNAND without any protection. Just stop.

**Comment by maorninja** [comment]
Lets take this on Discord PM's, as this is just going to do some stuff...
