### ISSUE TITLE
4.0 Release Instant Crash

### ISSUE THREAD

**Issue by Lykie** [Robz8/TWLoader#201]
Installed it and updated files over previous installation, booting it always leads to the Luma stack dump error screen.

**Comment by Jolty95** [comment]
@Lykie can you post here the luma stack dump? Maybe I can find anything interesting on it :)

**Comment by hectortillo** [comment]
in my 3ds it works :o probably try deleting old installation an d repeat :)

**Comment by Lykie** [comment]
[crash_dump_00000036.dmp.zip](https://github.com/Robz8/TWLoader/files/777309/crash_dump_00000036.dmp.zip)

**Comment by Jolty95** [comment]
Do you have emunand? a9lh? Anything about your configuration: if you have installed nand side, wifi on/off, etc

**Comment by Favna** [comment]
It works fine here. I upgraded by wiping the entire _nds folder on SDroot and flashcardroot as well as gbarunner on flashcard. I'm on Luma 6.6-ed8aee8 (hourly) on New3DS 11.3.0-36E

**Comment by Lykie** [comment]
A9LH no emunand, wifi off and I have installed nand side from one of the last updates.

**Comment by Jolty95** [comment]
This is your dump 
```
Processor: ARM11 (core 0)
Exception type: data abort
Current process: TWLoader (00040000047c4200)

Register dump:

r0             08003e90            r1             08003de0
r2             080a6cc4            r3             08003dd8
r4             080a6c60            r5             00000000
r6             00000001            r7             080a6cc4
r8             08003dd4            r9             08003e90
r10            080a6c60            r11            000001f4
r12            080268d8            sp             07ffff68
lr             0802dcf8            pc             00127dd0

cpsr           60000010            dfsr           00000805
ifsr           00000001            far            07ffffa0
fpexc          00000700            fpinst         eebd8ac8
fpinst2        eebd8ac8

Code dump:

  127da4:       eaffffb9        b       0x127c90
  127da8:       e3a00000        mov     r0, #0
  127dac:       eaffffa8        b       0x127c54
  127db0:       0000ffff        strdeq  pc, [r0], -pc   ; <UNPREDICTABLE>
  127db4:       00000186        andeq   r0, r0, r6, lsl #3
  127db8:       e92d4ff0        push    {r4, r5, r6, r7, r8, r9, r10, r11, lr}
  127dbc:       e1a0a000        mov     r10, r0
  127dc0:       e24ddc3e        sub     sp, sp, #15872  ; 0x3e00
  127dc4:       e5900084        ldr     r0, [r0, #132]  ; 0x84
  127dc8:       e24dd01c        sub     sp, sp, #28
  127dcc:       e590e2dc        ldr     lr, [r0, #732]  ; 0x2dc
  127dd0:       e58d0038        str     r0, [sp, #56]   ; 0x38


Stack dump:
```
But I don't know where crashes...
Try deleting TWLoader from FBI and reinstall again using the cias

**Comment by Favna** [comment]
Launched TWLoader with wifi ***off*** when having both bootstrap and twloader to auto download + deleted 2 previously downloaded box arts and it still launches so that's not related anyway.

**Comment by Lykie** [comment]
Deleting and installing TWLoader and nand side fixed the problem.
