### ISSUE TITLE
Gbarunner2 do not work in Dsi Menu :) 

### ISSUE THREAD

**Issue by hectortillo** [Robz8/TWLoader#202]
running it from Wood Theme works, Running it from R4 theme Works :) only Dsi Menu doesnt init it :) 
Also i have seen the new branch of Gbarunner (the flie explorer one) and Tried it on my flashcard :) it Runs very good :) can it be placed in the next release version? :D :) also thanks for all your hard Work :D Robz8, Jolty95 :D bakawun :D and all the others implicated on this work :)

**Comment by hectortillo** [comment]
This version (atacched archive) :) it runs a lot of games with awesome compatibility ;D not works all games but it can play very well a grown list :) :D  how it can be run from TWLoader without getting the TEST screen? :) 

it dont let me to add the archive so i let a link in mi drive with the archive :) 
https://mega.nz/#!eNFWxAJS!3DBD1np3WXunDlOgwr77S3QX71O5NCi4Ueq7NhdniC8

**Comment by Jolty95** [comment]
a231eea6eb4f85ed235606d9c7fdee6f42563326 ;)

**Comment by hectortillo** [comment]
Thanks. :D.
