### ISSUE TITLE
Stuck in reading nds file trying to add games from flashcard

### ISSUE THREAD

**Issue by Mattery** [Robz8/TWLoader#204]
Well, i own a M3 DS Real and "Add games" worked the first time i tried succesfully adding 2 games, next day i tried to add another game but it didn't work, i was using a spanish rom with some fixes so i tried another rom from emuparadise but nope, i can't find any log so i'm a bit stuck, i had the same problem some time ago and i did a fresh install in my flashcard and it fixed it but i don't think that's they way it should work.

### I can always reinstall but i thought i should report this issue here for future improvements.
-pic related
![img_20170215_231241](https://cloud.githubusercontent.com/assets/8432976/22997889/9fe05c2c-f3d4-11e6-972d-702e6681a956.jpg)

**Comment by Jolty95** [comment]
Are you using latest TWLoader.nds file in flashcard?

**Comment by Mattery** [comment]
I think so, no update was released when i did this(that was 5 days ago) and i updated today to 4.0.0, were the flashcard packs also updated?

**Comment by Jolty95** [comment]
Nop, just asking to get us more info ;)

**Comment by Mattery** [comment]
I replaced again twloader.nds in the flashcard in it's respective _nds directory but no luck

**Comment by Mattery** [comment]
well i just checked the twloader nds file and it appears that it should create a log file in sd:/_nds/twloader/ . Is that only in some cases or is it disabled? Maybe it doesn't create any error log after succesfully launching the file?

**Comment by Jolty95** [comment]
@Mattery log file is dissabled by default. To enable log, create a file and name it "log" with NO extension and put it on SD:\_nds\twloader and launch TWLoader again. It will create the log.ini file

**Comment by Mattery** [comment]
Nice, gonna check it now

**Comment by Mattery** [comment]
Nah it doesn't report anything after switching to NTR/TWL-mode

**Comment by hectortillo** [comment]
do you have selected your flash card in settings? :) into the flashcard select in Options? :)

**Comment by Robz8** [comment]
His flashcard wouldn't work, if not.

**Comment by Mattery** [comment]
Exactly :P

**Comment by Mattery** [comment]
After rebooting by holding the power button the the rainbow effect continued even in homemenu, i doubt it's intentional. Looks nice tho

**Comment by Robz8** [comment]
@Mattery If you're still getting the bug, sorry, I have no idea how to fix this.
