### ISSUE TITLE
TWLoader not saving setting.ini

### ISSUE THREAD

**Issue by Theorvolt** [Robz8/TWLoader#205]
After updating to the latest TWLoader, my nds-bootstrap started working again. However, the settings.ini file keeps on deleting itself if I try to create it for TWLoader to save to. I can't save my preferences because of this. I think you should be able to do it by deleting the settings.ini file.

Also I am using Luma + A9LH 11.2 ( No emunand) installed as a cia file.

**Comment by Robz8** [comment]
#209
