### ISSUE TITLE
[Request] Add Option to cancel auto update from startup

### ISSUE THREAD

**Issue by rpalmon** [Robz8/TWLoader#208]
Hello, I think what would be a nice feature would be able to press a button (like b) to cancel the auto update.

I know I could disable the update but sometimes I would want to update automatically for when a new version comes out. This would be convenient for me as sometimes it takes quite a while to start the application with auto updates on.

Another reason I would like this feature is because sometimes when I am playing with the app and it freezes when trying a game, I want to restart the application. But when I reboot the app, it could take longer.

**Comment by rpalmon** [comment]
There could also be a note on the bottom right of the cards when updating that could let you know you could press b to cancel.

**Comment by Jolty95** [comment]
It's a good idea that is on my TODO list, but it's a duplicated https://github.com/Robz8/TWLoader/issues/171 Anyway, I'll keep working on it :)
