### ISSUE TITLE
TWLoader deleting settings.ini

### ISSUE THREAD

**Issue by Theorvolt** [Robz8/TWLoader#209]
My settings.ini file keeps on deleting itself if I try to create it for TWLoader to save to. I tried using someone elses settings.ini but it still deletes :(

Also I am using Luma + A9LH 11.2 ( No emunand) installed as a cia file.

**Comment by Robz8** [comment]
There is no code in TWLoader that deletes settings.ini, so that shouldn't happen.
There might be a problem with your SD card.

**Comment by Theorvolt** [comment]
Okay. I will try formatting the sd card and will get back.
