### ISSUE TITLE
Run DSi System Apps?

### ISSUE THREAD

**Issue by rpalmon** [Robz8/TWLoader#21]
Hello, so I found some system apps like DSi photos and DSi sound. They were dumped as NDS and CIA from the DSi. Do you think you could make it so we could run them? You could find it on the ISO site by searching NDS system titles or something like that.

**Comment by GerbilSoft** [comment]
Some DSi system applications can be installed directly to TWL NAND, e.g. PictoChat. Camera and Sound might be installable as well.

Do note that 3DS Camera and 3DS Sound are basically the same thing, but better.

**Comment by bakawun** [comment]
@rpalmon 

adding the apps should already work
however if they work or not from bootstrap depends on bootstrap
maybe you can add your test results to the compatibility list there

this ticket can be closed

**Comment by Jolty95** [comment]
I think this can be closed
