### ISSUE TITLE
Starting a nds game turns off n3dsxl

### ISSUE THREAD

**Issue by Minxxe** [Robz8/TWLoader#213]
Topic says it all.
Installed TWLoader v4.0.3 as CIA on 11.3 with EmuNAND and Luma3DS.
Edit: @Topic game is being started from sd card.
Game i tried to start: Mario Kart DS

**Comment by Jolty95** [comment]
Have you installed NAND side in SysNAND and EmuNAND?

**Comment by Robz8** [comment]
That's not it. TWLoader will stop with a message if it isn't installed.
Try installing a clean TWL_FIRM CIA.

**Comment by Jolty95** [comment]
@Robz8 I programmed that function BUT if you're using EmuNAND and if NOT installed in sysnand, we cannot know it either....(at least that's the theory)

**Comment by Minxxe** [comment]
@Jolty95 How can i install it in sysnand? because it has no valid certificate.

**Comment by Jolty95** [comment]
@Minxxe Do you have FBI injected in SysNAND? I don't have emunand but iirc you need to launch FBI from sysnand and install nand side there too :)

**Comment by Minxxe** [comment]
@Jolty95 i wasn't able to inject fbi into sysnand smh i tried it with via homebrew with fasthax but it just said its not using a valid certificate.

**Comment by Jolty95** [comment]
@Minxxe AFAIK using FBI with fasthax only works with legit cias

**Comment by Margen67** [comment]
@Minxxe Are you using A9LH?

**Comment by Minxxe** [comment]
@Margen67 "Installed TWLoader v4.0.3 as CIA on 11.3 with EmuNAND and Luma3DS."

**Comment by Margen67** [comment]
Why are you using emuNAND?

**Comment by Minxxe** [comment]
@Margen67 Because i didn't really knew about a9lh until i was done with my emunand.

**Comment by Margen67** [comment]
Follow this guide http://3ds.guide/

**Comment by Minxxe** [comment]
well how can i get rid of emunand?

**Comment by Robz8** [comment]
Like @Margen67 said, follow the guide.

**Comment by Minxxe** [comment]
@Robz8 I didn't saw the information about emunand at the bottom mb.

**Comment by Margen67** [comment]
At a certain part of the guide it has you move your emuNAND to your sysNAND.

**Comment by Minxxe** [comment]
So, after about 3h im now using A9LH (i did not move my emunand because it hadn't much important stuff) and i can say TWLoader is Working :)

**Comment by Robz8** [comment]
Good! Enjoy TWLoader!

**Comment by Margen67** [comment]
@maorninja Why would you downvote the guide?
He's already installed A9LH so you're way too late, anyway.
