### ISSUE TITLE
Update compatibility list?

### ISSUE THREAD

**Issue by CuconWo** [Robz8/TWLoader#215]
Has there been any upgrade to the compatibility list of games? The only one that I have seen roaming the -internet it´s one from  v0.4.0 so it´s outdated and I don´t know if there has been any update to the loader itself to be more compatible. Thank you for your work and I hope that in the future this evolves to a stable DS loader. There are so many gems!

**Comment by Barawer** [comment]
The compatibility list is not for TWLoader, its for nds-bootstarp. TWLoader uses nds-bootstrap in order to boot nds games. the latest nds-bootstrap version is 0.4.0, so its updated.
link to nds-bootsrap: https://github.com/ahezard/nds-bootstrap/releases

**Comment by Margen67** [comment]
How do I edit the compatibility list?

**Comment by Robz8** [comment]
Did you request access?

**Comment by CuconWo** [comment]
Oh okay, I understand but, now that they are working in "tandem" you could say, maybe they could update the compatibility in a near future.

**Comment by Margen67** [comment]
@Robz8 Yes.

**Comment by Jolty95** [comment]
Since compatibility is users responsibility to keep it updated and doesn't belong to TWLoader, I'll close this :)
