### ISSUE TITLE
kanji sonomama rakubiki jiten

### ISSUE THREAD

**Issue by namanix** [Robz8/TWLoader#220]
Hi There,

I know this isn't the right way to contact you but i could not find a way other than this to reach you.
In the NDS-Bootstrap google docs it states that you tested: kanji sonomama rakubiki jiten and concluded that picochat is not working. I need the tool for japanese study but it does not function at all. 

The game gives a red attention window that roughly translates to: Data could not be read. Please turn off the power and insert the card again.
See screenshots.

Is there anything i can try to fix this? I'm out of idea's.

Kind regards,
Kevin Walter
![20170219_202603](https://cloud.githubusercontent.com/assets/1583377/23105600/1a5ede82-f6e2-11e6-8929-cad43ba9f46c.jpg)
![20170219_202610](https://cloud.githubusercontent.com/assets/1583377/23105603/1a6058c0-f6e2-11e6-8529-1a35ea003e0b.jpg)
![20170219_202618](https://cloud.githubusercontent.com/assets/1583377/23105601/1a602d6e-f6e2-11e6-95bd-6a1e042ed5b5.jpg)
![20170219_202740](https://cloud.githubusercontent.com/assets/1583377/23105602/1a603016-f6e2-11e6-8e9b-e08923941321.jpg)

**Comment by Robz8** [comment]
Try taking out the currently inserted slot-1 card.

**Comment by namanix** [comment]
That actually worked. Thank you soo much!
