### ISSUE TITLE
TODO: split 3dsx version to another branch

### ISSUE THREAD

**Issue by Jolty95** [Robz8/TWLoader#222]
@Robz8 if you want, I can split 3dsx code to another branch (first on my repo, and if you like the idea, later send the PR here as always)
I think we can improve a bit more twloader if we don't send user a frankenbuild with a lot of code that won't never be used (3dsx version inside cia) and I don't mind to update 3dsx version branch at all. Also, cia size (and 3dsx too) will be a lot smaller with less code and also, it will make it a lot better to manage the code because now some parts of code are a bit unreadable.

If you like the idea, lock the conversation (or reply me back), if not, close it, that's all :)

**Comment by Robz8** [comment]
Yes.

**Comment by Jolty95** [comment]
Since Rosalina have introduced a new way to handle 3dsx homebrews, 3dsx version don't need to be a demo dummy mode anymore, so I don't think this need to be done at the end :P
