### ISSUE TITLE
Crashing to HOME Menu with latest devkitARM and libctru versions

### ISSUE THREAD

**Issue by Robz8** [Robz8/TWLoader#225]

**Comment by Robz8** [comment]
It either crashes at making the directories, or loading the fonts.

**Comment by Robz8** [comment]
Yep, either crashes at "sftd_init" or loading the fonts.

**Comment by Robz8** [comment]
I found the real problem why it crashes. It's the text drawing code.

**Comment by tetsuo55** [comment]
We should switch to this method for drawing the text
https://github.com/devkitPro/3ds-examples/tree/master/graphics/printing/system-font

**Comment by bakawun** [comment]
We should switch to this method for drawing the text
https://github.com/devkitPro/3ds-examples/tree/master/graphics/printing/system-font

**Comment by Jolty95** [comment]
@Robz8 do you know how to solve it or do you want an helping hand?

**Comment by bakawun** [comment]
@Jolty95 i cannot say if he has, but the link i gave that explains how to use system font with citro3d could solve it. Also it would fix the font corruption issue we have.

**Comment by Robz8** [comment]
Problem is, I don't know how to implement it.

**Comment by bakawun** [comment]
i think we can.
But we should stop using the sf libs altogether

**Comment by tetsuo55** [comment]
@Robz8 @Jolty95 @GerbilSoft 

I asked xerpi about it and we really have to convert our code using the example above

**Comment by Jolty95** [comment]
You don't need to use multi account. We've read the first time btw

**Comment by bakawun** [comment]
Oops i keep posting with someone elses account (shared computer)

**Comment by Jolty95** [comment]
@Robz8 this can be closed afaik
