### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by killer983** [Robz8/TWLoader#229]
White screen in games that go well in twloader 4.0 now do not work in 4.1.0 For example: mario kart ds
boostrap official 0.4.0 and unofficial 56746a3

**Comment by Robz8** [comment]
Update the unofficial bootstrap.

**Comment by killer983** [comment]
I have already updated the unofficial bootstrap and do not go mario kart ds

**Comment by Robz8** [comment]
Is TWLNAND side updated? Try also re-setting your donor rom, if you have one set.

**Comment by killer983** [comment]
Twlnandsize not updated when updating twloader

**Comment by Robz8** [comment]
Try downloading the latest release on GitHub, then install TWLNAND side included in the 7z file.

**Comment by killer983** [comment]
Now work
