### ISSUE TITLE
Is there any way to upload boxarts to the place that the app downloads them from

### ISSUE THREAD

**Issue by deadair3210** [Robz8/TWLoader#230]
Figured I would try to help if I can by filling in the missing games' boxart

**Comment by Robz8** [comment]
This is the place: http://www.gametdb.com/
You might have to register for an account.

**Comment by deadair3210** [comment]
Ok thanks!

**Comment by deadair3210** [comment]
I can't seem to find anything on that website about DS at all, only 3DS, Gamecube, Wii, and PS3

**Comment by Robz8** [comment]
Did you register an account?

**Comment by deadair3210** [comment]
Yes, it changed nothing as far as I can tell other than adding a Upload Artwork button to the pages of games

**Comment by deadair3210** [comment]
![vfdvfd](https://cloud.githubusercontent.com/assets/1053504/23171736/fe700ef2-f818-11e6-9b4e-3c26f7621e1b.PNG)

**Comment by Robz8** [comment]
Try contacting them.

**Comment by deadair3210** [comment]
I just filled out the form to contact them, thanks

**Comment by Robz8** [comment]
No problem. Hope you can upload DS box art soon.
