### ISSUE TITLE
I need help!

### ISSUE THREAD

**Issue by Tempest1012** [Robz8/TWLoader#232]
Hi, i've just downloaded the latest version of TWLoader, and i need help with 2 things. Starting with the easy bit, where can I find the twl side file? Now the hard bit is that i can go normally on TWLoader, without getting any errors messages. The issue comes in when i try to start one of my DS Games, because as soon as I start one, the system switches completely off! I've tried games from the list and games that weren't in the list but nothing worked. Beofore you ask, i'm on cfw 11.35 and i'm using A9LH, plus i don't think it's because of that side file because i don't get any errors at all. Thanks for your time.

EDIT: Progress made, thanks guys, now the system doesn't switch off anymore, but when it loads the game, both screens go white after the classic DSi Health and Safety thing. Any suggestions for that?

**Comment by Jolty95** [comment]
NAND Side file is on SD:\_nds\twloader\cia
Install that file file and try again if you have any doubt. :)

**Comment by Robz8** [comment]
https://3ds.guide/troubleshooting: DSi / DS functionality is broken after completing the guide

**Comment by Jolty95** [comment]
Oh, yeah sorry. I understood you were finding nand side -facepalm-
Follow the guide above instead :)

**Comment by Tempest1012** [comment]
EDIT: Progress made, thanks guys, now the system doesn't switch off anymore, but when it loads the game, both screens go white after the classic DSi Health and Safety thing. Any suggestions for that?

**Comment by Margen67** [comment]
What game are you trying to play?

**Comment by Tempest1012** [comment]
I've tried  New Super Mario because i know it's in the list of the checked games, then i tried to play Inazuma Eleven 2 Blizzard and sadly none of them worked, so i think there is something more i need to do, since the first one is in the list of the working games.

**Comment by Robz8** [comment]
It also tells you what games work and don't work.

**Comment by Tempest1012** [comment]
Ok, i didn't know that, where can you see if a game works or not? Also, if the screens stay white without loading the games it's because they don't work?

**Comment by Robz8** [comment]
Scroll left to see "Compatibility".
Also, mostly yes.

**Comment by Tempest1012** [comment]
On the very left i've got the Settings, which don't mention anything regarding compatibility. But i know for sure that New Super Mario Bros. runs on TWLoader because it's in the list. https://docs.google.com/spreadsheets/d/1M7MxYQzVhb4604esdvo57a7crSvbGzFIdotLW0bm0Co/edit#gid=0

**Comment by Robz8** [comment]
You mean nds-bootstrap. TWLoader is just a frontend for nds-bootstrap.
Also "Compatibility" is in the list. Next to it is "Other Notes" and "Tested by".

**Comment by Tempest1012** [comment]
I have no idea about what you said in the first line, consider me a newbie regarding CFW, sorry for that.

When i open TWLoader, what i see in the menu are just the settings and my games, and for some reason a cartdidge whith the game i've got in the 2DS. I can't see anywhere "Other Notes" and "Tested By". Perhaps this has to do with the issues i have? How does the program react when you start a non-compatible game? Does it give you a message or it simply hangs up? I've also tried Pokemon Platinum now and although it's in the list, i get the same issue.

**Comment by Robz8** [comment]
"Compatibility", "Other Notes", and "Tested By" is in the compatibility list, not TWLoader.

**Comment by Tempest1012** [comment]
Oh F me! I'm feeling very dumb right now... Thanks for your time guys, and especially you Robz, it makes me very happy to see that developers themselves help the community. So i guess the list gets updated occasionally and new games get added in. 

BTW, i'm not pirating those games, i'd like you to know that because i know that it's not right towards the developers. It might sound weird but since i recently moved, i left the sachet in which i had all my DS games in Italy, so yeah... unlucky...

**Comment by Robz8** [comment]
nds-bootstrap (the SD rom loader itself) will be updated in the future to support more games, so check this thread: https://gbatemp.net/threads/nds-bootstrap-loader-run-commercial-nds-backups-from-an-sd-card.454323/
If there's a new version released in it's GitHub page, go into Settings in TWLoader, then press X. Make sure Bootstrap is set to Release.
