### ISSUE TITLE
Every single game hangs on a white screen

### ISSUE THREAD

**Issue by TheMCNerd2017** [Robz8/TWLoader#235]
Self-explanatory issue. After updating TWLoader and nds-bootstrap to the latest official versions available, every single game I attempt to launch hangs on a white screen almost every time unless I go in and toggle the DS boot screen on and off every time I launch the app. I am not sure why this happens, so I thought I would bring up this issue.

**Comment by Margen67** [comment]
What entrypoint are you using?
Are you using an emuNAND?

**Comment by Robz8** [comment]
Did you update the bootstraps and TWLNAND side?

**Comment by TheMCNerd2017** [comment]
Yes, TWLNAND side was updated correctly. I am using CFW, so I run it directly from the home menu. I do not have an emuNAND installed.

**Comment by Jolty95** [comment]
@TheMCNerd2017 can you re-set the donor rom?

**Comment by TheMCNerd2017** [comment]
What do you mean by resetting the donor rom? Do I really need to use one of my physical DS game carts for saving now?

**Comment by Jolty95** [comment]
@TheMCNerd2017 No. I mean to click on "Set as donor rom" in a working rom like Mario kart DS

**Comment by TheMCNerd2017** [comment]
I don't get an option anywhere to set it as a donor rom. Does it have to be dumped, or can I use the physical cart?

**Comment by Jolty95** [comment]
@TheMCNerd2017 open TWLoader and find a working rom (before I said a really good example ;) ) and press START(or SELECT don't remember right now) and press "Set as donor rom".
After that, try to run your white screen games. Now should work :)

**Comment by TheMCNerd2017** [comment]
I try to do that, but it always gets stuck on tthis screen.
![img_1038](https://cloud.githubusercontent.com/assets/25375242/23264667/2a68afbc-f9b0-11e6-9418-1b9b1b920c78.JPG)

**Comment by TheMCNerd2017** [comment]
That is with every game.

**Comment by Jolty95** [comment]
Is LOCK arm9 off?
What's about the per-game settings?

**Comment by TheMCNerd2017** [comment]
The lock arm9 was on, but games were working before with that on. i turned that option off. I also pressed select on the Sonic Rush prototype which brought a menu up. I pressed set as donor and proceded to launch one of the roms. It finally loaded up and started working again.

**Comment by Jolty95** [comment]
lock arm9 needs to be off since some bootstrap releases ago.
Can I close this now? :)

**Comment by TheMCNerd2017** [comment]
No need. I can close it. They should work on making the arm9 lock compatible though.
