### ISSUE TITLE
GBA

### ISSUE THREAD

**Issue by hectortillo** [Robz8/TWLoader#24]
Can be used gbaemu4ds instead of gbarunner for better compatibility? I will try it. But i dont know mucho of programing (excuse me for my bad english)

**Comment by hectortillo** [comment]
It doesnt run. I will close this. Its a bad idea. Excuse me.  And thanks :D thanks for your hard work :D

**Comment by maorninja** [comment]
> It doesnt run.

https://docs.google.com/spreadsheets/d/1M7MxYQzVhb4604esdvo57a7crSvbGzFIdotLW0bm0Co/edit#gid=1412086532 It actually does now.

**Comment by hectortillo** [comment]
Thanks maorninja :) :D :)
