### ISSUE TITLE
App hangs when exiting settings

### ISSUE THREAD

**Issue by deadair3210** [Robz8/TWLoader#246]
Freshly formatted sd card, placed twloader package contents and arm9loaderhax.bin file, nothing else. Turned on 3ds and let it make its folders, then installed both normal and twl side. app opens but when i go to open the settings and even without changing anything back out, the app causes the 3ds to crash and restart

**Comment by Jolty95** [comment]
what theme do you have set for twloader?

**Comment by deadair3210** [comment]
default, cant change any settings without it crashing. I just got done formatting the sd card, and placed the sd files on the root of the sd card

**Comment by Jolty95** [comment]
maybe it's not related but...
create in SD two folders like this:
SD:\roms\nds
SD:\roms\flashcard\nds

and tell me back if that solves the problem :)

**Comment by deadair3210** [comment]
I think that fixed it, its working fine now after I added some games

**Comment by Jolty95** [comment]
Can this be closed? :)

**Comment by deadair3210** [comment]
This should be fixed though, either through having dummy folders in the archive, or by having the app create it when it notices that they are missing

**Comment by Jolty95** [comment]
[Wiki](https://github.com/Robz8/TWLoader/wiki/Installation-and-upgrade) said you need to move your `.nds` backups to `SD:\roms\nds` so at least that folder needs to be created by user first.

**Comment by deadair3210** [comment]
Perhaps put a notice somewhere a little more noticeable if possible? People don't always go to the wiki
