### ISSUE TITLE
Games not loading

### ISSUE THREAD

**Issue by Redswastaken** [Robz8/TWLoader#251]
I installed twloader on a friends 3ds (he has the original model), and one of the games dont appear on the menu (megamanzx advent). Also only one of the games actually start when selected (sonic rush). The 3 other games I downloaded either get stuck on a black or white screen.

**Comment by Robz8** [comment]
Is MegaMan ZX Advent in the same directory as Sonic Rush?

**Comment by Redswastaken** [comment]
yup. there all in sd/roms/nds

**Comment by Robz8** [comment]
Did you try switching pages?

**Comment by Redswastaken** [comment]
What?

**Comment by Robz8** [comment]
If you have more than 20 roms in the folder, you can press L or R to switch pages.

**Comment by Redswastaken** [comment]
there are only 5 roms

**Comment by Robz8** [comment]
What's the exact filename extension for the MMZXA rom?

**Comment by Redswastaken** [comment]
.nds

**Comment by Robz8** [comment]
That's weird. It should have appeared if it's correct.
What's the exact filename of the rom?

**Comment by Redswastaken** [comment]
MegZX Advent.nds

**Comment by Robz8** [comment]
Can you upload a PC screenshot of your rom list?
