### ISSUE TITLE
Anyone else have the constant update loop?

### ISSUE THREAD

**Issue by harveytj03** [Robz8/TWLoader#254]
I know this is known but im just wondering who has it working fine and ones that are also having the issue.
You may close this issue. But i just made it for anyone just wanting to say its fine for them or they're having the issue.

**Comment by Robz8** [comment]
Pretty sure everyone will have this issue if the auto-update option is on.

**Comment by harveytj03** [comment]
Anyway to reset it?

**Comment by Robz8** [comment]
Turn off wifi, then go to the TWLoader settings screen, and turn off Auto-update TWLoader.

**Comment by Margen67** [comment]
Unless the problem has been fixed the issue shouldn't be closed.

**Comment by Robz8** [comment]
The issue is still open here: #167
