### ISSUE TITLE
Hello!!

### ISSUE THREAD

**Issue by Akino94** [Robz8/TWLoader#255]
Hello, good afternoon, will work someday the world end whit you patched to Spanish in this application? I need to play :(

**Comment by Robz8** [comment]
The World Ends Without You won't be playable for a while.

**Comment by Jolty95** [comment]
@Akino94 The World Ends With You aún no funciona con nds-bootstrap, así que aún queda un buen rato de espera para poder disfrutar de ese juego (ya somos dos :P )
Cuando TWEWY sea compatible, habrá que esperar un poco más para que sean compatibles las hackroms ya que de momento, las hacksroms de juegos compatibles (por ejemplo de Mario Kart DS) tampoco son compatibles :sweat_smile:
