### ISSUE TITLE
white screen

### ISSUE THREAD

**Issue by JustanOrdinary** [Robz8/TWLoader#257]
I'm trying to boot rhythm heaven DS. Any suggestions or any way to test it out to see if it works? It's just a white screen

**Comment by Robz8** [comment]
If it's white screen for a while, then the game's incompatible.
Also, wrong repository. This is for the frontend/GUI of TWLoader.
Here's the backend that does the actual ROM loading/running.
https://github.com/ahezard/nds-bootstrap

**Comment by JustanOrdinary** [comment]
oops sry closing
