### ISSUE TITLE
Date from TWLoader

### ISSUE THREAD

**Issue by DD2XAlpha** [Robz8/TWLoader#259]
Hello I want to know how to change the date of TWLoader. I changed the date from 3ds system settings but on TWLoader it doesn't change

**Comment by Jolty95** [comment]
@DD2XAlpha Are you using sysnand+emunand?

**Comment by DD2XAlpha** [comment]
I'm using Luma3ds 7.0

**Comment by Jolty95** [comment]
@DD2XAlpha I think you haven't notice about my edit :P

**Comment by DD2XAlpha** [comment]
On the DS profile is only the mesaage and color options

**Comment by Robz8** [comment]
@DD2XAlpha Are you using SysNAND+EmuNAND with Luma?

**Comment by Jolty95** [comment]
@DD2XAlpha I think you're using sysnand+emunad just I said before and @Robz8 

If yes, boot to SysNAND and change date there too

**Comment by DD2XAlpha** [comment]
I'm using ARM9Lh I have the Autoboot on Luma Settings.  The problem is that. Meloetta Distribution Demo Rom from 2013 works great but the problem is the date

**Comment by Jolty95** [comment]
That is a different problem and is related with nds-bootstrap not with TWLoader afaik.

**Comment by DD2XAlpha** [comment]
Ok thanks
