### ISSUE TITLE
Getting Error Message "Unable to read data. Turn the power off and reinsert the Game Card."

### ISSUE THREAD

**Issue by Kazutto** [Robz8/TWLoader#260]
I am trying to play Mario Hoops 3 on 3, but I always get the error message "Unable to read data. Turn the power off and reinsert the Game Card". I am using the correct version and the game should be compatible according to nds bootstrap list.

**Comment by Robz8** [comment]
Did you set a Mario Kart DS ROM as a donor ROM?
If not, in the TWLoader GUI, if using the DSi-Menu theme, move the cursor to the MKDS ROM, press SELECT, then select "Set as donor ROM".

**Comment by Kazutto** [comment]
Wait am I supposed to download Mario Kart

**Comment by Kazutto** [comment]
Ok the game is working now. Thanks :D
