### ISSUE TITLE
N3DS turns off while loading a game

### ISSUE THREAD

**Issue by frankyfife** [Robz8/TWLoader#261]
FW 11.3.
latest TWLoader (4.3.1), bootstrap 0.4.1

games r listet (super mario ds) in the selection menue, confirm the selection turns off my N3DS (screen goes black and the blue power led turns off). i'm pretty new to the whole 3ds/cfw topic, so i'm not sure if this is really a bug. from what i understand the loader reboots in a kind of 3ds mode.

**Comment by Robz8** [comment]
Try following this part of the guide: https://3ds.guide/troubleshooting#twl_broken

**Comment by frankyfife** [comment]
you're right. Following the guide you mentioned did the trick for me. thank you.

**Comment by Robz8** [comment]
You're welcome. :)
