### ISSUE TITLE
Font not centered correctly

### ISSUE THREAD

**Issue by RinMaru** [Robz8/TWLoader#263]
I heard this issue in another thread that was closed but it's still a thing the font is not centered as it should be

**Comment by anuserlol** [comment]
Yes,i have that problem too.I don't know if this is because i use it in spanish or what,but if you can,please fix it. Thanks.

**Comment by Jolty95** [comment]
It's not a problem of language and it's a well-known bug. I'll fixed soon too :)

**Comment by anuserlol** [comment]
ok thanks

**Comment by Jolty95** [comment]
Next release version will have all (or almost all) text strings centered ;)
