### ISSUE TITLE
An error has occured

### ISSUE THREAD

**Issue by WildWester** [Robz8/TWLoader#264]
an error has occured
press and hold the POWER button
to turn the system off

Luma v. 7.0.4
n3ds emunand 11.3 (sysnand unused on 11.4)
Regular DS cartridges work DSI ware does not work
Game: super princess peach

video of the error:
https://www.youtube.com/watch?v=NnrqH3DI3xg 

*edit
also when booting a cartridge from twloader it also gives the error screen

**edit legend of zelda four swords from eshop does not work either i will try https://3ds.guide/troubleshooting#twl_broken 

*update dsi apps are still not working even after trying all the troubleshooting guides i could find.

UPDATE
installing the bootstrap on sysnand fixed the issue!!! yay

**Comment by Robz8** [comment]
Did you inject FBI into SysNAND H&S?

**Comment by WildWester** [comment]
Nope i seem not even be able to do so as it gives me an error, (same error occurs when dumping hs.app)
slotkey0x25keyX not set up

**Comment by WildWester** [comment]
UPDATE
installing the bootstrap on sysnand fixed the issue!!! yay

**Comment by Robz8** [comment]
You mean TWLNAND side? bootstrap is just on the SD card.

**Comment by Jolty95** [comment]
@WildWester how have you "installed bootstrap to sysnand"? o.o 
I think you wanna say: TWL_FIRM, right?
Bootstrap is on SD and can not be "installed" haha

**Comment by maorninja** [comment]
Actually, you can install the bootstrap as a cia but it has to be compiled by yourself... But what he means is the TWL side cia

Sent from my iPhone

On May 5, 2017, at 4:19 PM, Jolty <notifications@github.com<mailto:notifications@github.com>> wrote:


@WildWester<https://github.com/WildWester> how have you "installed bootstrap to sysnand"? o.o
I think you wanna say: TWL_FIRM, right?
Bootstrap is on SD and can not be "installed" haha

**Comment by edgelord9000** [comment]
Yes I ment the TWL Nand side thingy sorry for the confusion

**Comment by edgelord9000** [comment]
redardles thanks for your help on the issue

**Comment by edgelord9000** [comment]
*regardless (I am typing on my phone)
