### ISSUE TITLE
French.h not used in the release 4.3.1 ?

### ISSUE THREAD

**Issue by daffyb** [Robz8/TWLoader#265]
Hello, 
After updating twloader to 4.3.1 it seams the last French translation has not been included into the release. 
Any one comfirms ?

**Comment by Jolty95** [comment]
french is on 4.3.1 too. Check again in settings but I've tested now and I can switch to french without issues.

**Comment by daffyb** [comment]
French is working but it is not the one with the corrections I made (not the last one, same as on 4.2)

**Comment by Jolty95** [comment]
@daffyb oh I see. I'm using my PR's latest commit and it's showing your corrections. Maybe @Robz8 forget to sync his local repo before compiling 4.3.1? :)

**Comment by daffyb** [comment]
Yep, it's a possibility ;)

**Comment by Jolty95** [comment]
This can be closed :P
