### ISSUE TITLE
Fallback region is not working for european roms

### ISSUE THREAD

**Issue by Jolty95** [Robz8/TWLoader#267]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [x]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x]  A9LH + Sysnand
- [ ]  A9LH + Emunand
- [x]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [ ]  Latest release
- [x]  I've compiled myself _[65f0423]_
- [ ]  Old release

### Expected behaviour

Boxarts for European/Spanish roms should download ES boxarts *OR*  EN boxarts (by fallback)

### Actual behaviour

Fallback region is not working for European/Spanish roms (at least)

### Steps to reproduce

1. Find a spanish/eur rom like this: YKGP (Kingdom Hearts 358/2 Days)
2. Try to get boxart for ES first. http://art.gametdb.com/ds/coverS/ES/YKGP.png (fails, that's ok)
3. Try to get boxart for EN http://art.gametdb.com/ds/coverS/EN/YKGP.png (it exist, should be downloaded!
4. Watch everytime you open TWLoader how boxart doesn't download (?)

### Stack trace and console log

```
Message: <Downloading boxart for TID> 	Additional info:<AMCP>
Message: <Downloading boxart for TID> 	Additional info:<APDP>
Message: <Downloading boxart for TID> 	Additional info:<APHP>
Message: <Downloading boxart for TID> 	Additional info:<ARGP>
Message: <Downloading boxart for TID> 	Additional info:<ASMP>
Message: <Downloading boxart for TID> 	Additional info:<AWLP>
Message: <Downloading boxart for TID> 	Additional info:<BH2P>
Message: <Downloading boxart for TID> 	Additional info:<BK9P>
Message: <Downloading boxart for TID> 	Additional info:<BSLP>
Message: <Downloading boxart for TID> 	Additional info:<C2SP>
Message: <Downloading boxart for TID> 	Additional info:<C3JS>
Message: <Downloading boxart for TID> 	Additional info:<C6PP>
Message: <Downloading boxart for TID> 	Additional info:<IRAS>
Message: <Downloading boxart for TID> 	Additional info:<IRBS>
Message: <Downloading boxart for TID> 	Additional info:<IRDS>
Message: <Downloading boxart for TID> 	Additional info:<IRES>
Message: <Downloading boxart for TID> 	Additional info:<YKGP>
Message: <Downloading boxart for TID> 	Additional info:<YLTS>
```
PS: Some of them doesn't exist on EN neither but most of them exist as `http://art.gametdb.com/ds/coverS/EN/%.4s.png` but are not downloading. 
Seems to me like a problem in 
`static const char *getGameTDBRegion(u8 tid_region, const char **pFallback)`
PS2: I haven't notice this problem before because I've always used custom boxarts
PS3: I love how this issues templates looks.

**Comment by Robz8** [comment]
I had to make it only use EN for Pokemon Black and White 1&2.

**Comment by Jolty95** [comment]
I don't mean that :P
I'm saying that by fallback, it should download this for example:
http://art.gametdb.com/ds/coverS/EN/YKGP.png
But isn't doing that when http://art.gametdb.com/ds/coverS/ES/YKGP.png doesn't exist

**Comment by Jolty95** [comment]
@Robz8 I found the problem!

In some minutes I'll send a PR fixing this :)

**Comment by Jolty95** [comment]
Done ;) 
https://github.com/Robz8/TWLoader/pull/269
