### ISSUE TITLE
TWLoader selecting non-existant icons.

### ISSUE THREAD

**Issue by Gauchecoder64** [Robz8/TWLoader#270]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [X]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [X]  A9LH + Sysnand
- [ ]  A9LH + Emunand
- [ ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [X]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [X]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

The "START" selector box should be on the gamecart icon, and I shouldn't be able to move past the bracket.

### Actual behaviour

The "START" selector box is on the right bracket, and I can move past it as much as I want by pressing right.

(If I go to the left of the bracket, I can't re-select the bracket without reproducing the glitch. This might mean TWLoader is trying to select a third icon even though there isn't one, i'm not sure.)

[Picture 1](http://i.imgur.com/PQlwif1.png) - [Picture 2](http://i.imgur.com/x74hmfZ.png) - [Picture 3](http://i.imgur.com/rbgJcgJ.png)

### Steps to reproduce

1. Remove all the roms from TWLoader until all you have are the settings and gamecart icons.
2. Go to Settings.
3. Press B.

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by Jolty95** [comment]
@Gauchecoder64 Are you having this problem with SD roms, FC, or both? :)

**Comment by Jolty95** [comment]
OK, I've found the problem ;)

**Comment by Gauchecoder64** [comment]
@Jolty95 I've only tried it on SD.

**Comment by Jolty95** [comment]
https://github.com/Robz8/TWLoader/pull/271 :)
