### ISSUE TITLE
Black Screen in SM64DS after opening the lid

### ISSUE THREAD

**Issue by sethreign8103** [Robz8/TWLoader#274]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ X ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ X ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [ X ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [ X ]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [ X ]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Tell us what should happen
After a game (in this case Super Mario 64 DS) is started and the lid is closed and opened to resume the game should be able to resume.

### Actual behaviour

Tell us what happens instead
When playing a game (in this case Super Mario 64 DS) after the lid is closed then opened there is no video.

### Steps to reproduce

1. Load game.
2. Close lid.
3. Open lid.

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by Robz8** [comment]
That happens, because you have TWL clock speed set for this game. In TWLoader's DSi Menu, press SELECT on Super Mario 64 DS ROM, then change CPU speed to 67mhz(NTR).

**Comment by sethreign8103** [comment]
Yep that was it. Thanks. Also really good job getting this to run as good as it does now.
