### ISSUE TITLE
exiting settings returns to the interface on top of right bound border guard

### ISSUE THREAD

**Issue by TiredKorok** [Robz8/TWLoader#275]
### Your 3DS

Tell us which console do you have:

- [ 1]  Old 3DS XL

### CFW and configuration

Tell us which CFW do you have:

- [1 ]  Boot9Strap (SigHax) **luma latest stable release

### Console version

Tell us which version do you have:

- [ 1]  >= 11.4

### TWLoader version

Tell us which versions you are using:

- [ 1]  Latest release

### Expected behaviour

Exiting settings returns to the main interface on the leftmost icon.

### Actual behaviour

Exiting system settings returns to the main interface on the right border guard. Using the left d-pad button to move off of this works but then, like normal, you can not move back on top of it.

### Steps to reproduce

1.enter settings
2.hit b

As shown in this- https://drive.google.com/open?id=0B0IP4vJYHKjreFF6czJPelJkb2c

### Stack trace and console log

no crash

**Comment by Jolty95** [comment]
Thanks for the complete report but I fixed that some days ago :P
Just to be sure, I'll test it again before clossing ;)

**Comment by Jolty95** [comment]
Yeah, it's solved in latest commits :P

**Comment by Robz8** [comment]
@Jolty95 Hope you can fix the update issues, so it gets another release.

**Comment by Jolty95** [comment]
@Robz8 Which ones? :P Do you mean nand side updates with .json too?

**Comment by Robz8** [comment]
Yep.

**Comment by Jolty95** [comment]
I'm working on it rn ;)
