### ISSUE TITLE
Automate TWLoader-Update repo

### ISSUE THREAD

**Issue by mariogamer2** [Robz8/TWLoader#277]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [ ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [ ]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [ ]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```
I'm not sure, but I heard travis can do commands like push to a repo. If not,we could search for another bot.

**Comment by mariogamer2** [comment]
I know this may take time, but it will be better than always updating manually.

**Comment by Jolty95** [comment]
I not agree to update TWLoader-update repo ussing a bot. We are only ussing prebuilds from that repo, so we don't need to update that submodule either too frequently (it's quite rare to update it tbh) and if one day we need to update the submodule, it's just one git command so I don't see the point to have a bot for that (also, we have an script to push nightlies rn too)

I'll keep this issue open in case @Robz8 isn't agree with me :P

**Comment by Robz8** [comment]
I agree with @Jolty95.

**Comment by maorninja** [comment]
@Jolty95 

> I'll keep this issue open in case @Robz8 isn't agree with me :P

doesn't*

/me runs
