### ISSUE TITLE
Change issues_template and contributing files

### ISSUE THREAD

**Issue by mariogamer2** [Robz8/TWLoader#278]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [ ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [ ]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [ ]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```
Some issues are not "issues", only new feature and request. Those files should be changed according to this.

**Comment by Jolty95** [comment]
issues_template say to remove the template if you are requesting a "request" ;)
