### ISSUE TITLE
Roms on SD card load very slowly

### ISSUE THREAD

**Issue by SaltfishAmi** [Robz8/TWLoader#279]
I'm using a New 3DS XL on 11.3 with B9 + Luma + Sysnand. I checked the compatibility list and found that my roms are all green. However when I boot the roms or scene changes in the game there're long lags up to a minute or two, making them unplayable. Does anyone know the reason? Thank you

**Comment by Robz8** [comment]
Your SD card isn't using 32kb cluster size.

**Comment by SaltfishAmi** [comment]
@Robz8 Reformatted but unsolved. Is there any requirements for the card?

**Comment by Robz8** [comment]
Besides having 32kb clusted size, nope.
What games are you playing?

**Comment by SaltfishAmi** [comment]
@Robz8 
Mario Kart EUR, Super Mario 64 DS USA.

**Comment by Robz8** [comment]
Mario 64 DS will work just fine.

**Comment by SaltfishAmi** [comment]
@Robz8 but it didn't...well I think I'll just use my flashcart instead.

**Comment by melgarsrain** [comment]
Arm 11 just freaking press the d pad while booting your es. And have the old ds logo load on tw loader
