### ISSUE TITLE
2.1.1 bug?

### ISSUE THREAD

**Issue by hectortillo** [Robz8/TWLoader#28]
Crashes at start (after dldi download)

**Comment by Robz8** [comment]
How many .nds files you have?

**Comment by Robz8** [comment]
Did you download the CIA in the Settings screen? I just now put up the right CIA for download.
If it still crashes, download the release here.

**Comment by hectortillo** [comment]
im going to uninstall twloader and delte older folders and will try again . in a few minutes i will report :)

**Comment by hectortillo** [comment]
it continue crashing, im not sure if its a failure in my 3ds or something (older versions had perfect functionality)

**Comment by hectortillo** [comment]
now it works
i found the problem, i had gbarunner2 in the nds roms folder, possibly it crashes when dont found any nds icon, excuse me for the inconvenience :o excelent work Robz8 :D thank you for all your hard work :) should i close this issue? and open another with the new issue problem? :o

**Comment by Robz8** [comment]
Actually, if there's no icon, a question mark is used in place.

**Comment by hectortillo** [comment]
im going to try again putting my older nds roms

**Comment by hectortillo** [comment]
now all works good it have worked again after i have delted my older nds roms and i have tryed every single old archive to verify the problem but i cannot find anything, i will try again but excuse , now all works perfectly, sorry again, thank you very much for your hard work Robz8 :)

**Comment by Robz8** [comment]
You're welcome. :)
