### ISSUE TITLE
Crash updating nds-bootstrap, then crash on TWLoader boot afterwards

### ISSUE THREAD

**Issue by aj-m** [Robz8/TWLoader#282]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [x]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [ ]  >= 11.4
- [x]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

TWLoader should download and install the latest version of nds-bootstrap and start normally.

### Actual behaviour

TWLoader crashes after starting the nds-bootstrap update, then after rebooting the console, crashes after displaying the splash screen when starting from the home menu.

### Steps to reproduce

1. Update TWLoader to the latest version by pressing start in the settings menu.
2. After the update is finished, start TWLoader and update nds-bootstrap official by pressing X in the settings menu. Confirm update by pressing A.
3. Crash.
4. Reboot DS.
5. Launch TWLoader.
6. Crash.

### Stack trace and console log

```An exception occurred
Processor: ARM11 (core 0)
Exception type: data abort
Current process: TWLoader (00040000047C4200)

R0    001E5220    R1    08015110
R2    08015140    R3    0801DAE8
R4    00000030    R5    00726576
R6    00000004    R7    08014988
R8    00000005    R9    080144E8
R10   00000000    R11   0000000E
R12   00000008    SP    08007950
LR    0801DB3C    PC    00156138
CPSR  20070010    FPEXC 00000005
```
[crash dumps zip](https://github.com/Robz8/TWLoader/files/1058483/dumps.zip)

**Comment by Jolty95** [comment]
Bug is fixed in latest nighty's :)
https://github.com/Robz8/TWLoader/pull/283

**Comment by nicolo01** [comment]
This still happens

**Comment by Clement95** [comment]
Same for me :/

**Comment by aly1339yi** [comment]
same here

**Comment by MatDaniel** [comment]
This is an Error of Nintendo, you have to disable the automatic Update Feature

How to do:
- open the settings file of TWLoader sdcard:\_nds\twloader\settings.ini
- change AUTODOWNLOAD and AUTOUPLOAD to 0
- give feedback if this had worked for you

sorry for my english, i'm german
