### ISSUE TITLE
TWLD.twldr not found

### ISSUE THREAD

**Issue by Jan200101** [Robz8/TWLoader#287]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [x]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [X]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [ ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [X]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [X]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

the selected game should start normaly

### Actual behaviour

Before launching the game it returns

sd:/_nds/twloader/TWLD.twldr 
not found.

Press B to return to
HOME Menu.

**Comment by Jolty95** [comment]
This is not a bug. Download TWLoader.7z from release page and put TWLD.twldr from 7z in `SD:\_nds\twloader\`

**Comment by Jan200101** [comment]
Well maybe TWLoader should download it automaticly when updating...
but hey ¯\_(ツ)_/¯

**Comment by Jolty95** [comment]
It actually do it. But only from version >5.0.0
