### ISSUE TITLE
Saves could not be loaded

### ISSUE THREAD

**Issue by DatRobinPlays** [Robz8/TWLoader#288]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [x ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ x]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [ ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x ]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [ x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Tell us what should happen
Game should load
### Actual behaviour

Tell us what happens instead
Game loads and says "save could not be read".
This happens on every new game I copy
### Steps to reproduce
1.Copy game to roms/NDS
2.Start game

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by Robz8** [comment]
Did you set a donor ROM?

**Comment by DatRobinPlays** [comment]
On some yes on others no.
A few are working without donor rom but say that they can't read the saves.
Others only work with donor rom and they say the same.

**Comment by DatRobinPlays** [comment]
Btw you are doing great work! <3

**Comment by Robz8** [comment]
Is Mario Kart DS set as donor ROM?
If yes, games that say "save could not be read" should be fixed in a future bootstrap version.

**Comment by DatRobinPlays** [comment]
Wow. It was really that easy. Thank you sooo much!!
