### ISSUE TITLE
[Untested on v5.2.1] TWLoader crashes on startup

### ISSUE THREAD

**Issue by Robz8** [Robz8/TWLoader#289]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [x]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [ ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

ROM selection screen should appear.

### Actual behaviour

For some users, it crashes with an exception from Luma.

### Steps to reproduce

1. Start TWLoader.
2. Wait for stuff to load.
3. That's all.

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by Margen67** [comment]
Does it crash with wifi on or off?

**Comment by Robz8** [comment]
Doesn't crash with WiFi on or off.

**Comment by PokeCaptain** [comment]
Same issue over here. Attached is a log and a dump for your viewing pleasure.
[TWLoader Crash.zip](https://github.com/Robz8/TWLoader/files/1073000/TWLoader.Crash.zip)

**Comment by Robz8** [comment]
Thanks, but I already found the issue.
It's the DS/DSi boot screen fade-to-black code causing the crash.

**Comment by PokeCaptain** [comment]
Is that in dsbootsplash.cpp?

**Comment by Robz8** [comment]
Yes. I tried fixing the bug in the latest commit.

**Comment by Dysproh** [comment]
This seems to be happening to me (o3ds/b9s/11.4)

**Comment by Robz8** [comment]
Fixed in the latest version.
