### ISSUE TITLE
Translation doesn't show up correctly (French)

### ISSUE THREAD

**Issue by Clement95** [Robz8/TWLoader#295]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [x]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1. Start TWLoader
2. At the selection screen, "TWLoader Settings" is displayed as "Unknown Cartridge" in French Language and maybe other languages

![top_0001](https://user-images.githubusercontent.com/21959693/27149280-4d8bce30-5143-11e7-9155-641a7764debd.png)
![bot_0001](https://user-images.githubusercontent.com/21959693/27149279-4d847914-5143-11e7-800b-5e1b772cdede.png)

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by Jolty95** [comment]
What language do you have TWloader? (in settings I mean)

**Comment by Clement95** [comment]
Sorry for title, I have French language

**Comment by Jolty95** [comment]
Have you checked other languages?

**Comment by Clement95** [comment]
It happens only with system (french) and french language on TWLoader settings, I tried also with italian in System Settings and on TWLoader, it doesn't show "Unknown Cartridge", when I change to french language, it still happens

**Comment by Jolty95** [comment]
That helps me a lot :P I'll take a look now :)

**Comment by Jolty95** [comment]
French.h file is OK and is not missing any comma so, I don't know yet why is not showing that string correctly.

**Comment by Clement95** [comment]
Nice ! This problem happens since 6 months I think but I always forgot to report this, and now I thought you doesn't would understant because I'm french and I speak little english

**Comment by Jolty95** [comment]
Don't worry for your English :) I'm spanish and can understand your english fine xD
I'll keep testing this, so I'll edit title and tag this issue :)

**Comment by Jolty95** [comment]
I'll need more steps to reproduce the problem. Is there something more you can tell me to help finding the problem?

**Comment by Clement95** [comment]
Okay :D Thank you !

**Comment by Clement95** [comment]
All my issues seem strange XD

**Comment by Clement95** [comment]
Start TWLoader, set language to french in TWLoader Settings, press B to exit Settings, and now you can look "Cartouche inconnue" in english "Unknown Cartridge"

**Comment by Jolty95** [comment]
Fixed @Clement95 sorry the delay >.< Really small bug to find it :P
