### ISSUE TITLE
DSTT "reset slot-1" inconsistent behavior

### ISSUE THREAD

**Issue by greensad** [Robz8/TWLoader#297]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [X]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [X]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [X]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [X]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [X]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Game should launch or "add game" function should boot consistently with "Reset Slot-1" enabled

### Actual behaviour

Reset Slot-1 works to launch a title or the add games function a single time, after which any title or the add games function results in a white screen. When checking the settings, "Reset Slot-1" is still enabled but the functionality of the toggle doesn't seem to persist. To launch any future games or use the add games function I am forced to toggle "Reset Slot-1" off- exit the menu and then re-enable the option.

### Steps to reproduce

1.Enable "Reset Slot-1" for the first time
2.Launch any game or add games function, exit to the home menu and re-launch TWLoader
3.Launch any game or add games function for a second time without touching any of the settings.
4.White screen

**Comment by Robz8** [comment]
Reset Slot-1 is never used with DSTT, unless launched directly.
A white screen will happen sometimes, so keep trying.
