### ISSUE TITLE
Nintendo DS Logo Plays At Half Speed

### ISSUE THREAD

**Issue by RinMaru** [Robz8/TWLoader#303]
Updated 7/28/17

New 3DS XL Black
Class 10 128GB Micro SD
SysNand Ver. 11.4  
Boot9Strap Ver. 1.2 
Luma3DS Ver.  8.1
TWLoader (CIA) Ver. 5.4.2

Note- Last Known Working Version TWLoader 5.2.0

The 3D Nintendo DS boot screen runs at half speed for some reason and even a fresh install dont seem to fix it. I think this started after 5.2.1

**Comment by Robz8** [comment]
I don't know why that's happening, as it plays at the correct speed for me.

**Comment by jerrytheberry126** [comment]
I have been having the same issue and I have not been able to run any ds games (even the ones that are listed as compatible.  I have updated my system to 11.4 using boot9strap and luma 3ds. I have followed this  tutorial perfectly https://3ds.guide/installing-boot9strap-(homebrew-launcher). And I have installed all of the cia files. Could it be that I have a bad rom? They worked well in a pc ds emulator

**Comment by Robz8** [comment]
The ROM you're using has nothing to do with the boot screen.

**Comment by RinMaru** [comment]
if you could plz test 5.2.0 and 5.4.2 they have speed differences in how smoothly the Logo plays

**Comment by jpmac26** [comment]
I agree, the logo appears to play unnaturally slowly on 5.4.2, I'm using a New 3DS XL, Luma 8.1, and I have my Luma's settings configured to boost non-N3DS games to the native N3DS CPU speed of 804MHz.

**Comment by HeroLarcio** [comment]
I've noticed that it only acts slow for me when a 3DS game is inserted into slot 1 (namely, Animal Crossing New Leaf). If a DS game or nothing is inserted at all, it plays at fullspeed. (This still applies to the latest version)

**Comment by RinMaru** [comment]
thats strange but ejecting a 3ds game fixes it like @HeroLarcio said

**Comment by OdnetninI** [comment]
I can confirm this too.
If a ds game, flashcard, or none is inserted, it plays at normal speed.
With any 3DS game, it runs near to half speed.

**Comment by Robz8** [comment]
Noticed that yesterday. Weird.

**Comment by OdnetninI** [comment]
The only idea I have is: getting 3DS Game information is forcing to waste more cicles than expected.
But I'm not really sure, but it sould be related to reading 3DS Card Information, propably:  'gamecardPoll' ?

**Comment by Robz8** [comment]
Fixed in the next version!
https://github.com/Robz8/TWLoader/commit/30abc3aaa3e6e158ff2afcf8f5293d5e6a9ddd25
