### ISSUE TITLE
TWLoader crashes when auto-updating on CFW 3ds

### ISSUE THREAD

**Issue by ssboss** [Robz8/TWLoader#304]
Twloader crashes when doing an auto-update or updating in general from the 3ds It worked on the previous versions, but now every time I try to update TWloader or nds-bootstrap from the 3ds, it crashes and gives me a dump file. My 3ds is an Old3ds using Luma3ds 8.0 and TWLoader cia.

**Comment by Robz8** [comment]
I'm not getting this bug. Updating bootstrap works fine for me.

**Comment by ssboss** [comment]
Nevermind. What happened was FBI wasn't loading TWNAND side part 2 for some weird reason.

**Comment by Robz8** [comment]
That's weird.

**Comment by jotebe** [comment]
I'm still getting this bug with all three cias reinstalled. It crashes with a "Data Abort" and dumps. It's during the Auto update of TWLoader, if the wifi connection is off it will not crash, and boots normally.

I've saved the dump files, should I upload them somewhere?

**Comment by Robz8** [comment]
That's fixed in the next version.
