### ISSUE TITLE
Please bring us back the original DS boot screen.

### ISSUE THREAD

**Issue by Antonio2311** [Robz8/TWLoader#306]
This is just an opinion
Hi, i love TWLoader but in one of the latests updates, the classic DS boot screen was changed, the old one is the original boot screen but the new one is different and i dont like it; like another people i only want the classic screen.
Thanks @Robz8  for creating TWLoader :)

**Comment by Robz8** [comment]
Technically, it's still the original, but improved with 240p resolution and 3D depth.
What is it that you don't like about the improved boot screen?

1. The higher resolution?
2. The 3D depth?
3. All of the above?

If I bring back the original, then there will be a bit more space clutter than usual, the frame rate will be 30fps, and the iQue DS logo, and the Chinese and Korean H&S messages won't be included.
The improved boot screen fixes all those issues.

**Comment by Antonio2311** [comment]
Thanks for your answer! I dont like the 3d depth.
I never imagined that changing something like this would have so much repercussion. :O
