### ISSUE TITLE
French DS boot screen text goes past the bottom screen

### ISSUE THREAD

**Issue by debilausaure** [Robz8/TWLoader#307]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [x]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour (as seen in NTR Launcher 3D)

![top_screen_ntr_launcher_3d](https://user-images.githubusercontent.com/4697676/27520470-a588f122-5a0c-11e7-8ec5-e451588fe146.png)
![bottom_screen_ntr_launcher_3d](https://user-images.githubusercontent.com/4697676/27520474-a97ed990-5a0c-11e7-9036-dda8a789bcf0.png)

### Actual behaviour (on TWLoader)

![top_screen_twloader](https://user-images.githubusercontent.com/4697676/27520480-c561fdc2-5a0c-11e7-8e67-810cbe0799f1.png)
![bottom_screen_twloader](https://user-images.githubusercontent.com/4697676/27520482-c8bf7e22-5a0c-11e7-8d01-c72bdcc97c0b.png)

### Steps to reproduce

1. Launch TWLoader to get to the DS boot screen

### Message
I am reporting this because @Robz8 said that ntr launcher 3d was already included in TWLoader [here](https://gbatemp.net/threads/ntr-launcher-3d-bring-back-that-classic-ds-boot-screen-for-your-ds-games-in-3d.474979/).
Yet we can see that ntr launcher 3d handles perfectly the french ds boot screen while twloader doesn't.

Also, there are a few typos inside the french ds boot screen, can I contribute to change that ?

Thank you for your work, let me know if you need anything else

**Comment by debilausaure** [comment]
For some reason it doesn't happen everytime.
Just booted my 3DS, and for some reason the bottom screen appeared just like it should.
Top screen still cropped though.

**Comment by Robz8** [comment]
You can disable the black bars in the settings screen.

**Comment by debilausaure** [comment]
Ah yes, I am sorry I did not understand what OAR meant...

**Comment by Jolty95** [comment]
This should be fixed in 52822faa6a77731f0534406c8c7ee6fd335915ce ;)
