### ISSUE TITLE
Load games in (small) original resolution by default (menu option)?

### ISSUE THREAD

**Issue by theKKCD** [Robz8/TWLoader#308]
There should be an option to have games loaded in the smaller, original NDS resolution rather than loading in the 3DS's terrible nearest-neighbor scaled resolution. This could be an option in the menu, to load by default, or if you press a different button to load a game than [A].

**Comment by Margen67** [comment]
Related: https://github.com/AuroraWright/Luma3DS/issues/434

**Comment by Clement95** [comment]
Just before loading the game hold the SELECT key and the game will be
in original NDS resolution

**Comment by Clement95** [comment]
The SELECT button*

**Comment by Margen67** [comment]
@Robz8 Why was this issue closed?

**Comment by Robz8** [comment]
The issue in Luma pretty much explains it.
