### ISSUE TITLE
Black screen while trying to run NDS games TWLoader

### ISSUE THREAD

**Issue by therockers** [Robz8/TWLoader#312]
So when I'm in the TWLoader menu, I am able to look at the titles such as the settings, Slot 1, and my other games like Pokemon Diamond and Pokemon Pearl. Once I click on say Pokemon Pearl, it leads me to the Health And Safety instruction screen and I click on the screen. After that, it says "Creating save file". Once that is done, the screen basically goes black like it's turned off. Not the black screen with light in the background, but just pure black screen as if it was turned off. Looking at my 3DS, the power light (blue) is still on, the 3D (green) light is on, wifi light (golden yellow) is on, and the light that indicates one of your friend is on is also on, but it's flashing rainbow colors like red, green, light yellow, cyan, blue, orange, .etc.

Can anyone help me figure out what is going on?

I have a regular old 3DS running in Gateway Firmware 11.2.0-35U and I'm also running TWLoader 5.4.2.

**Comment by Robz8** [comment]
Follow this guide. https://3ds.guide/troubleshooting#twl_broken

**Comment by Robz8** [comment]
Also, I don't think Gateway allows NTR/TWL mode.

**Comment by Robz8** [comment]
Also, Pokemon Diamond and Pearl don't work from SD card yet.

**Comment by therockers** [comment]
@Robz8 Still doesn't work. But I think you might be right. Gateway might not allow NTR/TWL mode. I don't want to try Luma on my 3DS due to the recent ban wave and I already own a Gateway so it really makes no sense to use Luma on it. I really want to play NDS games on my 3DS, but I guess my best bet is to buy an R4i for NDS games. Thanks for your help.
