### ISSUE TITLE
 TWLD.twldr not found

### ISSUE THREAD

**Issue by Cheees** [Robz8/TWLoader#315]
I already have TWLD.twldr on my sd card but it still gives me this error message.

https://www.youtube.com/watch?v=oF4oXV7WX0s

How can i fix it?

**Comment by maorninja** [comment]
Where did you put the file?

**Comment by Cheees** [comment]
@maorninja i put it into sd:/_nds/twloader/TWLD.twldr

**Comment by Cheees** [comment]
i think for some reason, it just can't be detected or direct the twld to twloader

**Comment by Robz8** [comment]
Is TWLD.twldr a folder or a file?

**Comment by Cheees** [comment]
@Robz8 it's a file

**Comment by Robz8** [comment]
Strange. Try searching for it in FBI, and see if it's there.

**Comment by Cheees** [comment]
@Robz8 yes 
It is there 
I can see it in FBI

**Comment by Robz8** [comment]
Might be your SD card having issues.

**Comment by panicbit** [comment]
Same issue here

**Comment by Robz8** [comment]
Use a nightly for now.
https://github.com/Jolty95/TWLoader-update/blob/master/beta/TWLoader-beta.cia

**Comment by panicbit** [comment]
The beta did nothing for me, however, I noticed that the `TWLD.twldr` for some reason ended up in the parent folder of were it is supposed to be.

**Comment by panicbit** [comment]
Ouch, I definitely extracted the wrong subfolder.

**Comment by Jolty95** [comment]
@panicbit That beta autodownload missing files ;)

**Comment by Cheees** [comment]
thanks, i will try in no time

**Comment by Cheees** [comment]
@Robz8 
if i install the beta version, do i need to install the side.cia as well?

**Comment by Robz8** [comment]
Use the latest stable version, and it'll install it for you.

**Comment by Cheees** [comment]
Robz8,

it still the same error shown :( 

probably this is just me in one-in-a million chance of getting this problem

**Comment by Jolty95** [comment]
@Cheees delete TWLD.twldr from SD, then with an active Internet conection, open TWLoader again and tell us if twld.twldr is still missing :)

**Comment by Cheees** [comment]
@Robz8 

And now this happens

![whatsapp image 2017-07-13 at 12 26 19 am](https://user-images.githubusercontent.com/29776403/28128346-04778d76-6762-11e7-8a50-e62bb20522c2.jpeg)

**Comment by Cheees** [comment]
I change the Twloader system language to English in setting, the  'Exception Occured' error is gone and 

now it is 

![whatsapp image 2017-07-13 at 12 30 48 am](https://user-images.githubusercontent.com/29776403/28128521-8d015d8e-6762-11e7-9ab6-2ac961cf3f1b.jpeg)

**Comment by Robz8** [comment]
Check if your SD card has any issues.

**Comment by Cheees** [comment]
what kind of tools do you recommend ? i haven't done it before

**Comment by Cheees** [comment]
could it maybe Im using a micro sd card ?

**Comment by mariogamer2** [comment]
H2testw on windows.

**Comment by Jolty95** [comment]
Why don't you just do the steps I've said you...?

**Comment by Cheees** [comment]
@Jolty95 

I did.  But it didn't solve the problem.

**Comment by Jolty95** [comment]
Show your log.ini file after doing my steps

**Comment by Testoftest** [comment]
I had the same problem but I only notice if this helps,Eye that is not served with the recent version
![1](https://user-images.githubusercontent.com/30124335/28129722-09f88cae-66fa-11e7-9360-019e1fa447e6.png)
![2](https://user-images.githubusercontent.com/30124335/28129731-1191313c-66fa-11e7-901f-335357deeaf3.png)
![3](https://user-images.githubusercontent.com/30124335/28129734-155337ac-66fa-11e7-95ee-1c1c59eed9f3.png)
![4](https://user-images.githubusercontent.com/30124335/28129740-1d6a16c2-66fa-11e7-9781-4ad7aadca6ce.png)
![5](https://user-images.githubusercontent.com/30124335/28129743-21f7982c-66fa-11e7-9c23-234584880dd0.png)
![6](https://user-images.githubusercontent.com/30124335/28129836-7bffb7f0-66fa-11e7-918c-afd623faa460.png)

**Comment by Cheees** [comment]
@Jolty95 

Where can I find the log?

**Comment by Jolty95** [comment]
@Cheees Create a file called "log" in sdmc:/_nds/twloader/log. Later, open TWLoader, let it fail and them, in same location, there will be sdmc:/_nds/twloader/log.ini

**Comment by Cheees** [comment]
@Jolty95 

![log](https://user-images.githubusercontent.com/29776403/28130751-6746daf8-676a-11e7-992e-b5de67664b14.jpg)

**Comment by Jolty95** [comment]
@Cheees can you reach this location with your browser?
https://github.com/Jolty95/TWLoader-update/blob/master/TWLD.twldr?raw=true

PS: Please, next time, post here the file, please

**Comment by Jolty95** [comment]
No reponse in 15 days, so we assume issue is fully solved.
