### ISSUE TITLE
Add an option to update every TWLoader file (?)

### ISSUE THREAD

**Issue by mariogamer2** [Robz8/TWLoader#321]
Even if TWLoader itself is updated.... Also it would be great to check TWLoader nandside version as well to be sure it is updated as well.

(By every file I mean most file in the _nds folder)

**Comment by Jolty95** [comment]
@mariogamer2 TWLoader autoupdate the files it need automatically. ATM, we don't have any way to check ONLY nand side version but I don't think there will be any soon.
