### ISSUE TITLE
New Super Mario Bros. Should be patched?

### ISSUE THREAD

**Issue by XperiencedLutz** [Robz8/TWLoader#325]
### Console

Which Console do you have?
- [X]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [X]  Luma3DS
- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [X]  = 11.3
- [ ]  >= 11.4

### TWLoader version

Tell us which versions you are using:

- [X]  Latest release 5.5.1 with updated bootstrap
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Tell us what should happen

NSMB should launch and be playable with little freezing between menus or loading.

### Actual behaviour

Tell us what happens instead

NSMB goes to a white screen forever.

### Steps to reproduce

1. Launch New Super Mario Bros.
2. Click past Nintendo DS screen
3. Profit

### Notes
I downloaded the rom off of the internet, maybe it is a bad rom. How do I get it directly from the gamecart. I have godmode9, maybe FBI would work too.

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

Where do I find the latest log files at? I found some at the root of my SD Card, but I believe those are from 5.4.0

**Comment by Robz8** [comment]
Is Mario Kart DS set as donor ROM?

**Comment by XperiencedLutz** [comment]
Does that mean I have to download mario kart DS and set it as donor ?

**Comment by Robz8** [comment]
Yes.

**Comment by XperiencedLutz** [comment]
I think you just saved my life let me try that, I didn't know what it meant by that

**Comment by XperiencedLutz** [comment]
Thank you :D
