### ISSUE TITLE
Screen dim bug

### ISSUE THREAD

**Issue by XperiencedLutz** [Robz8/TWLoader#326]
### Your 3DS

Tell us which console do you have:

- [X]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [X]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [ ]  >= 11.4
- [X]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [X]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Tell us what should happen

When you go to settings icon, enter it and press B rapidly it should go back to twloader home screen.

### Actual behaviour

Tell us what happens instead

It dims the screen in twloader only. The rest of the 3DS (home menu, other apps) is not dimmed. You cannot exit to the twloader menu without leaving the app.

### Steps to reproduce

1. Launch TWLoader
2. Click the settings icon and immediately click B rapidly
3. profit

**Comment by Jolty95** [comment]
@XperiencedLutz Closing this for now since new future release will have changed a lot of code and maybe will be solved
