### ISSUE TITLE
Cannot play game

### ISSUE THREAD

**Issue by midniteday** [Robz8/TWLoader#327]
### Your 3DS

Tell us which console do you have:

- [ ]  New 3DS

### CFW and configuration

Tell us which CFW do you have:

- [ ]  A9LH
- [ ]  Luma3DS

### Console version

Tell us which version do you have:

- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [ ]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Megaman Battle Network 5 Double Team should be loading from my SD card

### Actual behaviour

The box art appears in TWLoader and if i selected it, everything turns black, then turns white screen
### Steps to reproduce

1.Enter to TWLoader
2.Choose Megaman Battle Network 5 Double Team
3.

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by Robz8** [comment]
For now, you have to set Mario Kart DS as donor ROM, then set MMBN5 to force-use set donor ROM.

**Comment by midniteday** [comment]
i set Mario Kart as the Donor rom and change Megaman to force-use, but i am still stuck on white screen

**Comment by midniteday** [comment]
never mind,it is working now
