### ISSUE TITLE
Can I play Mario Kart DS in Wiimmfi using TWLoader?

### ISSUE THREAD

**Issue by Antonio2311** [Robz8/TWLoader#333]
Hi, Im very happy with the last update because finally i can play New Super Mario Bros; I love TWLoader because i don´t have a flashcard.
But I have a big question: in the latest version of TWLoader is possible to play online races in Mario Kart DS through Wiimmfi?
Thanks.

**Comment by Robz8** [comment]
Yes, it should work with online play with AltWfc and Wiimmfi.

**Comment by Antonio2311** [comment]
Alright! :D
