### ISSUE TITLE
Bug on the roms path

### ISSUE THREAD

**Issue by hectortillo** [Robz8/TWLoader#334]
Tell us which console do you have:

- [ X ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ X ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [ ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [ X ]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [ X ]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour
When loading GBArunner should keep sabed the roms path for loading the path of the nds games that i have configured to root:/roms/nds.   But when i reset TWLoader now it load the roms from the path 
root:/_nds

### Actual behaviour
 It load the roms path different from the one i have input before.   It load from root:/_nds

### Steps to reproduce

1.Open TWLoader and go to setings and input a different path than root:/_nds

2.On TWLoader press START and initialize GBArunner2. 
3.Press home button and opem TWLoader. And now it loads rom path from a different one than the one you've input. 

Also many thanks to all the devs involved on all the awesome  things. :D

**Comment by Robz8** [comment]
Will be fixed in the next version.

**Comment by hectortillo** [comment]
Thnks. :)
