### ISSUE TITLE
The Music of TWLoader.

### ISSUE THREAD

**Issue by Antonio2311** [Robz8/TWLoader#335]
Finally I'm going to ask this...
I watch a Youtube video of an old version of TWLoader and in that video when you are in the TWLoader menu I can hear a extended version of the music that play's when you select TWLoader in the 3DS home menu.
Can you give that music please?
(Yes this is so offtopic) xD
Thank you.

**Comment by Robz8** [comment]
It's in the first post. Find "Music files".
https://gbatemp.net/threads/twloader-ctr-mode-nds-app.448375/

**Comment by Antonio2311** [comment]
Finally! thanks dude.
