### ISSUE TITLE
DS Firmware in TWLoader

### ISSUE THREAD

**Issue by Antonio2311** [Robz8/TWLoader#336]
Is there any way to execute the DS firmare (firmware.bin) in TWLoader?

**Comment by Robz8** [comment]
No. There's a .nds file of it, but it only works for DS and DSi consoles.

**Comment by Antonio2311** [comment]
Oh ok, do you have a link for that?  :)

**Comment by Jolty95** [comment]
You cannot request copyright material here

**Comment by Robz8** [comment]
No he isn't. He's asking for a way to run it on TWLoader, not for a link to it.
