### ISSUE TITLE
Having trouble loading specific working titles on latest version

### ISSUE THREAD

**Issue by lukehurtig** [Robz8/TWLoader#338]
- [ ]  New 3DS XL

- [ ]  Boot9Strap (SigHax)
- [ ]  Luma3DS

- [ ]  >= 11.4

- [ ]  Latest release

### Expected behaviour

It should be loading Pokemon Diamond and Pearl, Animal Crossing Wild World, Yoshi Touch and Go, and Wario Ware Touched off of the sd card

### Actual behaviour

It takes forever to create a save file and it stays on the white screen even though they seem to be functional on the compatibility list

### Steps to reproduce

1.Load TWLoader
2.Force-use the Mario Kart DS donor rom
3.Select any of the listed non-working games above

### Stack trace and console log

I don't know how to access stack trace and console log from the white screen

**Comment by Robz8** [comment]
This is more of a bootstrap then a TWLoader issue.

What region are your Pokemon Diamond and Pearl, Animal Crossing Wild World ROMs?
Also, Yoshi Touch and Go, and WarioWare Touched are broken in bootstrap for now.

**Comment by lukehurtig** [comment]
The region for all three of those roms are NTSC-U

**Comment by Jolty95** [comment]
@lukehurtig is your console SD card formated in FAT32 and 32kb cluster size?

**Comment by linouxis9** [comment]
Same issue, can't confirm the SD card cluster layout right now but it is indeed formatted in FAT32.

**Comment by Robz8** [comment]
If you're unsure about the cluster size, format it anyways.

**Comment by NinjaBoyLao** [comment]
does the formatting of the SD card affect this? having the same issue with just pokemon diamond

**Comment by Robz8** [comment]
If it's not working, then it should help.

**Comment by NinjaBoyLao** [comment]
While we're here, what's the difference between platinum and diamond? I mean, aside from a bit more content and a few minor changes here and there, what makes diamond work and platinum not?
