### ISSUE TITLE
Console crashes when attempting TWLoader update

### ISSUE THREAD

**Issue by Niklink** [Robz8/TWLoader#339]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [x]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [ ]  >= 11.4
- [x]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [ ]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [x]  Old release

### Expected behaviour

TWLoader updates to latest version

### Actual behaviour

Console crashes almost immediately, get taken to 'An exception ocurred' error screen, console shuts down after pressing any button.

### Steps to reproduce

1. Open TWLoader settings (Ver 5.4.2)
2. Select 'Update TWLoader'

### Stack trace and console log

Actual file format should be .dmp but github doesn't let me attach those...

[crash_dump_00000000.txt](https://github.com/Robz8/TWLoader/files/1167745/crash_dump_00000000.txt)
[crash_dump_00000001.txt](https://github.com/Robz8/TWLoader/files/1167744/crash_dump_00000001.txt)
[crash_dump_00000002.txt](https://github.com/Robz8/TWLoader/files/1167743/crash_dump_00000002.txt)

**Comment by Jolty95** [comment]
I changed update file in v5.4.3, so any TWLoader <5.4.3 will crash when attempting to update TWLoader. You'll need to manual update

PS: I had to change that in order to make all new versions works (no more update crashes after changing that ;) )
