### ISSUE TITLE
Built in FTP Server for File Transfer?

### ISSUE THREAD

**Issue by rpalmon** [Robz8/TWLoader#34]
Hello, as a New 3DS XL owner, it is a pain having to unscrew the back of the new 3ds xl to get to the microSD card, especially when not having a microSD card reader around me some times.. 

It would be great if you had an option for an FTP server so I could transfer homebrew to my microSD card with the default location to where the folder for where the NDS files go.

**Comment by Robz8** [comment]
You can just use 3DS System Settings, and go to "Data Management>microSD Management".

**Comment by rpalmon** [comment]
I know. It would just be more convenient.

**Comment by Koopzington** [comment]
@rpalmon no need for such a thing when there already is https://github.com/mtheall/ftpd

**Comment by bakawun** [comment]
@Robz8 if you have no intention of allow remote installs through ftp then this can be closed with

**Comment by weirdal3333** [comment]
Make sure it uses port 5000 by default! (like every other homebrew app)
