### ISSUE TITLE
Launching Game Takes me to White Screen

### ISSUE THREAD

**Issue by Mikaphewn** [Robz8/TWLoader#341]
Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [X]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [X]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [X]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [X]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [X]  Latest release
- [ ]  I've compiled myself 
- [ ]  Old release

### Expected behaviour

Tell us what should happen
The game should load
### Actual behaviour

Tell us what happens instead
Leads to a white screen. Tried doing the fixes in the FAQ but still getting a white screen.
### Steps to reproduce

1.Launch Meteos rom
2. Get past DS warning 
3. White Screen'd

**Comment by Robz8** [comment]
Meteos is broken for now.
