### ISSUE TITLE
missing TWLD.twldr file 

### ISSUE THREAD

**Issue by DragonKaze** [Robz8/TWLoader#343]
Hi, even thought  the file is where it is supposed to be, it doesn't recognize it, when i lunch the game (Advance Wars Dual Strike, wich is compatible says the list) it says that the specified file is missing. also when using the Hombrew version, it won't recognice the boostrap or the game won't start (white screen). So what should i do?
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [*]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [*]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [*]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [*]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Load the game and being able to play.

### Actual behaviour

sends an error saying that the TWLD.twldr file is not there 

### Steps to reproduce

1. Just lunch TWLoader and start advance wars dual strike
2.
3.

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by Robz8** [comment]
Is WiFi access on?

**Comment by Jolty95** [comment]
Upload a screenshot and your log file please.
To create a log file, create a file called "log" on SD:\_nds\twloader folder. Then run TWLoader, and after exiting, in same location you'll find log.ini file

**Comment by DragonKaze** [comment]
I have tried it with both, on and off, and i have not seen a single change, as for the log file and the screenshot i will be uploading it in a moment

**Comment by DragonKaze** [comment]
![20517722_1426067970775762_1791407828_o](https://user-images.githubusercontent.com/30514639/28757282-8e09a3e0-7544-11e7-871b-34718ed7cb30.jpg)

so i tried creating the log.ini file 'cause  it did'nt created as you said it will, however it is empty, i will attach it.

[log.zip](https://github.com/Robz8/TWLoader/files/1185998/log.zip)

**Comment by Jolty95** [comment]
Can you show your 'SD:/_nds/twloader' folder please?

**Comment by DragonKaze** [comment]
sure, 
![17968160_1426104987438727_510877906_o](https://user-images.githubusercontent.com/30514639/28757535-e6c5f154-754a-11e7-9b16-34cfd1de7ec4.jpg)
here it is

**Comment by Jolty95** [comment]
Rename log.txt to just "log" with no extension, than, log.ini file won't be empty :)

**Comment by DragonKaze** [comment]
the thing is, that the log.txt file is just named like "log", but i can't take it's extencion, the computer saves it by default as log.txt :c

**Comment by Jolty95** [comment]
You can use GodMode9 iirc to rename it if you want and I think you can do this too with FBI

**Comment by DragonKaze** [comment]
nop, already tried changing the name, and it didn't work, log.ini is still empty :c

**Comment by DragonKaze** [comment]
let me atach it
[log.zip](https://github.com/Robz8/TWLoader/files/1186046/log.zip)

**Comment by Jolty95** [comment]
Ummm....maybe your sd card is damaged. Try checking in on your PC

**Comment by DragonKaze** [comment]
you mean sccaning it for virus or corrupted, files? if so i already did it and it is perfectly fine :/ and it is baced up by the fact that only the TWLoader "app" isn't working, everything works fine.

**Comment by Jolty95** [comment]
It's formated in FAT32 and 32kb cluster?

**Comment by DragonKaze** [comment]
it is FAT 32, the 32kb cluster idk, sorry that term is new to me

**Comment by DragonKaze** [comment]
how to i check it?

**Comment by Jolty95** [comment]
You can test to backup first, format it in that cluster size and put back the files later. If not, I'm out of ideas now :( Maybe Robz can helps more

**Comment by DragonKaze** [comment]
ok, aside of that i don't know preciely what happened but the log.ini file has actualy some weight

**Comment by DragonKaze** [comment]
give me a second

**Comment by DragonKaze** [comment]
[log.zip](https://github.com/Robz8/TWLoader/files/1186059/log.zip)
here it is finaly, hope you get the necesarry info from it

**Comment by Jolty95** [comment]
Yeah, TWLoader gui code it's not the problem at least :P

**Comment by Jolty95** [comment]
Also TWLD.twldr is been recognized by GUI too. Last idea I have is, can you delete your TWLD.twldr file, open TWLoader with Internet conection active and then paste again the log file please?

**Comment by DragonKaze** [comment]
okey, give me a moment

**Comment by DragonKaze** [comment]
As for what happens in the 3ds it just stays in a white screen, but it doesn't move on to the game.
[log.zip](https://github.com/Robz8/TWLoader/files/1186075/log.zip)
here is the log.ini

**Comment by Robz8** [comment]
Advance Wars Dual Strike is broken for now.

**Comment by DragonKaze** [comment]
crap man what a let down, but well, anyway thanks a lot for your help, and if it is not much of a trouble could you please let me know as soon as it gets playable again? (btw it seems like super mario bros 64 ds is as broken as AWDS cause i get the same result)

**Comment by Robz8** [comment]
Is nds-bootstrap up-to-date with v0.5.1b?
If so, format your SD card to FAT32 with 32kb cluster size/allocation size.

**Comment by DragonKaze** [comment]
It is up to date, and Okey, i'll try it

**Comment by Cheees** [comment]
i am having the same problem and i sort of give up solving it

**Comment by Jolty95** [comment]
@Cheees we had https://github.com/Robz8/TWLoader/issues/315 open for 15 days without answer. 
ATM, we are not able to reproduce the TWLD.twldr problem.
Is mario kart ds working? That game is working at 100% speed without issues

**Comment by Jolty95** [comment]
@DragonKaze I don't see nothing wrong on that log file neither

**Comment by Robz8** [comment]
@DragonKaze Also, did you fix the issue?

**Comment by DragonKaze** [comment]
Not working even after formating the sd

**Comment by DragonKaze** [comment]
Even though is not whitr screen, is the black one now, and still unable to play :/

**Comment by Robz8** [comment]
Not even SM64DS?

**Comment by Robz8** [comment]
If no white screen appears at all, try this part of Plailect's guide: http://3ds.guide/troubleshooting#twl_broken

**Comment by DragonKaze** [comment]
Okey I will givi it a shot, and as for your question yes even in SM64DS

**Comment by Jolty95** [comment]
@DragonKaze can you test to put this TWLD.twldr file and test?
[Version A.zip](https://github.com/Robz8/TWLoader/files/1191698/Version.A.zip)
[Version B.zip](https://github.com/Robz8/TWLoader/files/1191699/Version.B.zip)

Test with version A. If it is still missing, test version B
You tell me :)

**Comment by DragonKaze** [comment]
Sure, just guve me a pair of days Cause of familiar stuff and no pc/lap/etc

**Comment by EverythingIsProgramming** [comment]
The same happens to me on Mario Kart DS

**Comment by Robz8** [comment]
Are you able to connect to the internet on your 3DS?

**Comment by EverythingIsProgramming** [comment]
I fixed it. I deleted the entire _nds folder and replaced it.

**Comment by Jolty95** [comment]
@DragonKaze Have you tried it?

**Comment by Jolty95** [comment]
No answer for a long time.
