### ISSUE TITLE
Black screen on boot with nds game in slot 1

### ISSUE THREAD

**Issue by SHAX321** [Robz8/TWLoader#346]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [x ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [ ]  >= 11.4
- [x ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x ]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Pressing power should boot to 3ds menu

### Actual behaviour

Power light comes on, screen stays black, Wi-Fi light does not come on. Have to hard reset. Only happens with nds game in after installing twloader with ndsbootstrap. After taking the game out the 3ds starts fine every time.

### Steps to reproduce

1.Get my setup. (Newest Luma/B9S/twloadwr/ndsbootstrap. MKds and SM64DS installed. )
2.Turn off 3ds with nds game in slot (Professor Layton and the Diabolical Box exactly)
3. Try to turn 3ds back on and get black screen, no Wi-Fi light.

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```unsure how to check a log like this
```

**Comment by Robz8** [comment]
That isn't a TWLoader issue.
