### ISSUE TITLE
Remove demo version, scripts and only keep rosalina 3dsx version

### ISSUE THREAD

**Issue by Jolty95** [Robz8/TWLoader#348]
Title says all. Demo version is fully useless now. I suggest deleting it from repo, all gui code, batch scripts and all in general, and only keep rosalina working version instead. After deleting demo version, I'll update the nightly script to make it create nightlies for rosalina version and CIA too

**Comment by Robz8** [comment]
There are still people who doesn't use CFW+Rosalina.

**Comment by Jolty95** [comment]
But I'm talking about that dummy 3dsx version that doesn't load games

**Comment by Robz8** [comment]
Yeah, I know.

**Comment by Margen67** [comment]
Maybe you could remove the demo branch and add permission checks so if no kernel etc privileges are detected it will automatically go to demo mode
