### ISSUE TITLE
Getting sent back to the 3DS home menu when selecting a rom

### ISSUE THREAD

**Issue by DelxHQ** [Robz8/TWLoader#349]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [x]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Load the supported ROM I selected

### Actual behaviour

Sent to the 3DS home menu after pressing or touching the screen on the DS boot screen

**Comment by Robz8** [comment]
That issue occurs on the 3DSX version, but does not occur on the CIA version.

**Comment by DelxHQ** [comment]
I am not using the 3DSX version. Im using the CIA version.

**Comment by Robz8** [comment]
Does an error message appear?

**Comment by DelxHQ** [comment]
When i select the rom the system appears to restart with no error messages

**Comment by DelxHQ** [comment]
Sorry, this was a issue on my side. Following the steps <p><a href="https://3ds.guide/troubleshooting#twl_broken">here</p>
helped me solve the issue

**Comment by Robz8** [comment]
Ah, okay.
