### ISSUE TITLE
Random game crash [Mario Kart DS]

### ISSUE THREAD

**Issue by CCF100** [Robz8/TWLoader#350]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [x]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [ ]  >= 11.4
- [x]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release nds-bootstrap 3a076f3b
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Mariokart DS plays normaly

### Actual behaviour

Game randomly crashes during eyerock battle

### Steps to reproduce

1. Start missions
2. Play eyerock mission, and try to hit him a second time by breaking and hitting him in the eye the second he opens his other hand.

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
https://mega.nz/#!lYJRBAxS!wpDXOC6eG78vtrj23TxV6AkE7UnI9U1YwTM3CT-qilk
```

**Comment by Robz8** [comment]
It's an nds-bootstrap issue, not a TWLoader issue.

**Comment by CCF100** [comment]
I created an issue on nds-bootstrap with the same title referencing this one.Is that ok?

**Comment by Robz8** [comment]
Yes.
