### ISSUE TITLE
Can TWLoader load save from cart and load rom from TF card?

### ISSUE THREAD

**Issue by FlameBeam** [Robz8/TWLoader#351]
### Your 3DS

Tell us which console do you have:

- [*]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [*]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [*]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [*]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [*]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [*]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Can TWLoader load save file from the NTR/TWL game cart, but load the rom from SD/TF card?
(like HANS in HBL, but load the whole .nds file)

**Comment by Robz8** [comment]
No.
