### ISSUE TITLE
[Question] How do I use the read LEDs?

### ISSUE THREAD

**Issue by CCF100** [Robz8/TWLoader#353]
I noticed in the latest commit of nds-bootstrap @Robz8 added code to use the power and wifi LEDs as read LEDs, how do I enable that?

**Comment by Robz8** [comment]
It's DSi-exclusive, so it can't be used.

**Comment by CCF100** [comment]
Could you possibly implement it for 3ds using status led?

**Comment by Robz8** [comment]
Nope, not possible.
