### ISSUE TITLE
20 game limit on adding games from the flashcart

### ISSUE THREAD

**Issue by PhineasT** [Robz8/TWLoader#355]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [X]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [X]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [X]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [X]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

I have 25 games on my R4iDSN flash card.  When I try to add more than 20 TWLoader only shows the first 20 in alphabetical order

### Actual behaviour

I would expect to see all the games added

### Steps to reproduce

1. Continue to more than 20 games.
2.
3.

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by Jolty95** [comment]
Have you pressed L button in TWLoader? @PhineasT

**Comment by PhineasT** [comment]
Damn... left and right work... I couldn't find that documented.  Thanks.

**Comment by Jolty95** [comment]
@PhineasT Don't worry :P

**Comment by PhineasT** [comment]
Quick question... hopefully.  When I start a nds image from TWLoader from the Flashcart after the Nintendo DS screen I see a quick flash of the Wood screen then the ROM starts.  Is that expected behavior?

**Comment by Jolty95** [comment]
@PhineasT Yes, it is. TWLoader first load wood (or whatever kernel you have on your FC) and then, it quickly switch to the desired game you want to start :)

**Comment by PhineasT** [comment]
Ok, thought so.  When I run wood from the flashcart it also does the same thing but doesn't start a game.  I changed the skin in __rpg to be void and in _wfwd to dr_who_tardis so I only see a skin once.  :-)

**Comment by PhineasT** [comment]
Hi Jolty,

So with everything working fine I created a forwarder for a DS game.  It worked perfectly, however when I run TWLoader and try to start a different game it starts the game from the forwarder.  Ever see ths?

Phineas

**Comment by Robz8** [comment]
You mean a CIA forwarder?

**Comment by PhineasT** [comment]
Yes.  I used Forwarder3-DS to create a forwarder for for a DS game.

**Comment by PhineasT** [comment]
Hi all,

Let me explain my full configuration.  I'm using the R4iDSN card.  __rpg folder's lastsaved.ini points to abpathsetter.nds, and the UI is set to void (copied from _wfwd).  _wfwd is where the lastsaved.ini is changed to point to the game to launch.  Its theme is set to dr_who_tardis.  :-) .  When I run a game I see a black screen (void theme) then "Loading" then some text appears on the screen in a blink, then the themed menu appears, then goes to loading and starts the game.  When adding games the same sequence occurs.

So to my eye it looks like the menu runs twice, then runs the game.  When I start the DS flashcart from the Home Menu it does the same thing except stops at the themed menu so I can use it normally.

Is this the expected behavior on the R4iDS?  I dont have ysmenu installed at all.

Phineas T.

**Comment by PhineasT** [comment]
BTW I'm writing a program to walk a directory structure and make all the appropriate INI files.... like a bulk import.  Let me know if it's valuable.

**Comment by Robz8** [comment]
Make sure that it also extracts banner data.

**Comment by PhineasT** [comment]
Yup... simple VBS script.  Almost done with the first version.

**Comment by PhineasT** [comment]
This vbs will walk all subdirectories and create the ini file in the current folder.  It stores the rom and the banner ID.  best to run it in an empty folder pointed to the directory on the flashcart's SD CARD
save the code to a file nds.vbs.


Set objFSO = CreateObject("Scripting.FileSystemObject")
NumGames = 0
WScript.Echo "Begin"
Set objSuperFolder = objFSO.GetFolder(WScript.Arguments(0))
Call ShowSubfolders (objSuperFolder)
WScript.Echo CStr(NumGames) + " processed."
WScript.Echo "End"
WScript.Quit 0

Sub ShowSubFolders(fFolder)
    Set objFolder = objFSO.GetFolder(fFolder.Path)
    Set colFiles = objFolder.Files
    For Each objFile in colFiles
        If UCase(objFSO.GetExtensionName(objFile.name)) = "NDS" Then
            CreateIniFile objFile.Path, Replace(objFile.Name,"." & objFSO.GetExtensionName(objFile.Path),"")	
        End If
    Next
    For Each Subfolder in fFolder.SubFolders
        ShowSubFolders(Subfolder)
    Next
End Sub

Sub CreateIniFile(fNDSFilePath, fNDSFile)
    Set objFile = objFSO.CreateTextFile(fNDSFile + ".ini",True)
    objFile.WriteLine "[FLASHCARD-ROM]"
    objFile.WriteLine "NDS_PATH = " + GetGamePath(fNDSFilePath)
    objFile.WriteLine "TID = " + GetGameCode(fNDSFilePath)
    objFile.Close
    NumGames = NumGames + 1
End Sub

Function GetGameCode(fNDSFilePath)
    Set oFile = objFSO.GetFile(fNDSFilePath)
    With oFile.OpenAsTextStream(1, 0)
        readBinary = .Read(18)
        .Close
    End With
    For x = 13 to 18
	GetGameCode = GetGameCode + Chr(Asc(Mid(readBinary, x, 1)))
    Next     	
End Function

Function GetGamePath(fNDSFilePath)
    GetGamePath = Replace(Right(fNDSFilePath, Len(fNDSFilePath) - 3), "\", "/")
End Function

Run it by creating a placing it in an empty folder and type "cscript nds.vbs <full directory name on SD card>" e.g. "cscript nds.vbs d:\nds_roms.

**Comment by PhineasT** [comment]
Rats... I'm getting 'No Info' where I just added the ini file.  I know what you mean now by banner data.
