### ISSUE TITLE
pp2d misuse

### ISSUE THREAD

**Issue by BernardoGiordano** [Robz8/TWLoader#357]
* You're [redefining pp2d_draw_texture_blend and pp2d_draw_texture_scale](https://github.com/Robz8/TWLoader/compare/pp2d#diff-61c81de68443c5b4d38842509475f759R3) which are already included in pp2d
* [pp2d_draw](https://github.com/Robz8/TWLoader/compare/pp2d#diff-a842eea4b751307a859724f88a73ae43R1662)_on is already called in pp2d_draw_begin
* [textures are freed automatically](https://github.com/Robz8/TWLoader/compare/pp2d#diff-a842eea4b751307a859724f88a73ae43R5291) when you call pp2d_exit
* pp2d_begin_draw can be called once per frame at the beginning of the frame, not everytime you need to draw something

Consider joining https://discord.gg/zqXWgsH !

**Comment by Jolty95** [comment]
@BernardoGiordano thanks for your notes! 
I'm still learning how to use pp2d and I know I've added some mistakes to code. Tomorrow morning I'll try to fix all the mistakes I'm doing :)

**Comment by Jolty95** [comment]
I don't understand what this mean: pp2d_begin_draw can be called once per frame at the beginning of the frame, not everytime you need to draw something

Would you mind to explain me what it mean, please?

**Comment by BernardoGiordano** [comment]
https://github.com/Robz8/TWLoader/blob/pp2d/gui/source/main.cpp

You're calling pp2d_begin_draw more times per frame, when you only need to call it once.

For instance, the way it should be handled should be:

```
while(true) {
  pp2d_begin_draw(...);
  // draw your things
  pp2d_end_draw();
} ```

Instead, you're doing:

```
while(true) {
  pp2d_begin_draw(...);
  // draw thing 1
  pp2d_end_draw();

 ...

  pp2d_begin_draw(...);
  // draw thing n
  pp2d_end_draw();
} ```

This behaviour includes subfunctions, too.

Using pp2d_draw_on multiple times per frame is allowed, but begin and end should be called only once per frame.

**Comment by Jolty95** [comment]
@BernardoGiordano So, if I've understood correctly, only one pp2d_begin_draw( *whatever screen*) at the begining of the first while loop in main.cpp, some pp2d_draw_on if I need to change screen and only one pp2d_end_draw(); before closing the main while will do all the trick?? If so, THAT'S F*** AWESOME

Btw, how to render 3d images? I don't know how to display images in 3D and thanks you for your help >.<

**Comment by BernardoGiordano** [comment]
that's correct! and, regarding 3D images, pp2d doesn't support left and right targets for 3D images, as for now

**Comment by Jolty95** [comment]
IMHO I think we can omit 3D renders for now until pp2d support it. What do you think, @Robz8 ? :)
And thanks again @BernardoGiordano I'll modify again main.cpp file to modify that :)

**Comment by BernardoGiordano** [comment]
please let me know and send me a build when the job is done, I'm curious!

**Comment by Jolty95** [comment]
Yes, sure! If I haven't make any mistakes (or at least too bad), after rewriting main.cpp, adding the missing includes TWLoader should compile. I'll send you a build in discord :)

**Comment by Jolty95** [comment]
@BernardoGiordano 
[TWLoader.zip](https://github.com/Robz8/TWLoader/files/1272530/TWLoader.zip)
This is the very first version of TWLoader with pp2d. It crashes after some renders but that easy to fix :P 
Do you want me to send you screenshots when I finish the bugfixes?

**Comment by Robz8** [comment]
I'll be closing this, since everything works with pp2d properly.
