### ISSUE TITLE
TWLoader whitescreens after update to 0.6.0 on any game.

### ISSUE THREAD

**Issue by AlexS2412** [Robz8/TWLoader#360]
### Your 3DS

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [X ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ X]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [ ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [× ]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [ ×]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

For the compatible titles to boot normally.

### Actual behaviour

They hang on whitescreen after updating to 0.6.0

### Steps to reproduce

1.Use Latest TWLoader
2.Update Bootstrap to 0.6.0
3.Run any title

**Comment by AlexS2412** [comment]
Ive also tested on my old 3ds as well.

**Comment by mariogamer2** [comment]
Did you tried to follow TWL fix step here? https://3ds.guide/troubleshooting

**Comment by AlexS2412** [comment]
This is with only the newest bootstrap. And its a whitescreen not a blackscreen as stated in the issue.

**Comment by Robz8** [comment]
What games did you test?

**Comment by Robz8** [comment]
Try turning on Console output "(with Debug)".

**Comment by AlexS2412** [comment]
Ive tested all the compatible games like Super Mario 64 and the Megaman games.

**Comment by AlexS2412** [comment]
It worked after turning on console output somehow...

**Comment by AlexS2412** [comment]
Actually i just found out that it somehow downgraded my bootstrap version to 0.5.0 after some checking...

**Comment by Robz8** [comment]
What about unofficial?

**Comment by AlexS2412** [comment]
Havent tested yet but the console output disappears way too fast for me to see what it said.

**Comment by Robz8** [comment]
Is it set to "On (with Debug)"?

**Comment by AlexS2412** [comment]
White screen on both. Ive also tested on more than one console. Is there a nand side cia i need to update?

**Comment by AlexS2412** [comment]
Im still using 5.5.1 of twloader

**Comment by Robz8** [comment]
Your TWLoader is up-to-date.
Try formatting your SD card to FAT32 with 32kb cluster/allocation size.

**Comment by AlexS2412** [comment]
It already is ffs

**Comment by AlexS2412** [comment]
Its a 64gb sd card that im POSITIVE is not the issue.

**Comment by AlexS2412** [comment]
As i stated before it works completely nornally with both 0.5.0 and 0.5.1. The issue os with the newest bootstrap

**Comment by Robz8** [comment]
Well then I'm out of ideas. It works fine for me. :(

**Comment by AlexS2412** [comment]
What is your discord?  Minenis Alex S#8291. We can discuss this over dms

**Comment by Robz8** [comment]
I'm unable to send any DMs to you.

**Comment by AlexS2412** [comment]
You have to send me a friend request on discord

**Comment by Robz8** [comment]
sent

**Comment by Robz8** [comment]
Since the new bootstrap version 0.6.1 fixed your issue, this can be closed.
