### ISSUE TITLE
[Request] Action Replay Codes

### ISSUE THREAD

**Issue by PlasticJustice** [Robz8/TWLoader#363]
Even though it's possible thru copying your save from TWLoader to a PC and playing your save thru DeSuME with AR codes enabled, it would be nice if you could have and enable AR codes within TWLoader like [NitroHax](https://github.com/chishm/nitrohax) and use them on roms.

**Comment by Robz8** [comment]
Already on the todo list. ;)

**Comment by PlasticJustice** [comment]
Ok, hopefully it doesn't cause you much trouble implementing.
