### ISSUE TITLE
Wiki QR Codes not installable via FBI

### ISSUE THREAD

**Issue by willowsnow** [Robz8/TWLoader#364]
The QR codes currently on the wiki do not work with FBI, as ?raw=true will return a 404 to browsers that cannot handle the response (i.e. FBI's download client).

I have created new QR codes that work flawlessly

TWLoader GUI:
![twloader_gui](https://user-images.githubusercontent.com/29696963/30257272-5d320660-9676-11e7-8a9b-17041fbc2f62.png)

TWLoader NAND Part 1
![twloader_nand_1](https://user-images.githubusercontent.com/29696963/30257280-6d026800-9676-11e7-92c8-c6d81d80e588.png)

TWLoader NAND Part 2
![twloader_nand_2](https://user-images.githubusercontent.com/29696963/30257285-766a38aa-9676-11e7-8d66-362ccc9be775.png)

**Comment by Robz8** [comment]
Fixed.

**Comment by Jolty95** [comment]
@Robz8 sorry but this issue is invalid. As I say some days ago on discord, there was an error on FBI, that was fixed (https://github.com/Steveice10/FBI/issues/389) and also, I fix them before you edited wiki again (and I told you too on discord's....)

**Comment by willowsnow** [comment]
Direct links should be better supported than a redirect to said direct link.

**Comment by Jolty95** [comment]
@willowsnow my qr codes were direct link to official update repo.

**Comment by willowsnow** [comment]
@Jolty95 they were direct links to redirects via ?raw=true. My QR codes direct link to the official update repo via raw.githubusercontent. It's the same thing, just without redirect.
