### ISSUE TITLE
[Request]Dsi Menu "Jump to" effect on TWLoader menu

### ISSUE THREAD

**Issue by BobMarleyisapokemoninLOZ** [Robz8/TWLoader#365]
Would it be possible to include the jump to effect from the DSi Home Menu in TWLoader?
https://youtu.be/EAJtRrRAFn8

**Comment by Robz8** [comment]
That's already possible, but touching the icon after the next icon, just jumps to the next icon.

**Comment by BobMarleyisapokemoninLOZ** [comment]
It's feels wrong in it's current state.
