### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by christianfirecup** [Robz8/TWLoader#366]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [ ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [ ]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [ ]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by Robz8** [comment]
Can you explain what happens?

**Comment by 18Phoenix** [comment]
New 3DS XL + latest v11.6 + latest Luma3DS 8.1.1 + latest TWLoader 5.5.1

Exiting a game with L+R+B+down always crashes, doesn't matter which type of menu design is chosen :(

**Comment by Bullzone** [comment]
@18Phoenix The same thing happens to me. When I'm using TWLoader and I'm playing MegaMan ZX Advent every time I accidentaly press those button combinations.

**Comment by Robz8** [comment]
Try unofficial bootstrap.
With that, If L+R+DOWN+B is held for 2 seconds, then it'll reboot into SRLoader, if installed.
