### ISSUE TITLE
Cant get Twloader working! An error has occurred

### ISSUE THREAD

**Issue by ems1260** [Robz8/TWLoader#367]
### Your 3DS

Tell us which console do you have:

- [● ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [● ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [ ●]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [ ●]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

To run nds games

### Actual behavior

When i try to start super mario 64 ds the screen goes black and the "an error has occorred" menssage and i need to restart the system.
Ive tried to install boot9strap;
Follow the troubleshot guide with the cias folder;
Just don't know what to try now...

### Stack trace and console log

"An error has occurred"
```
```

**Comment by Robz8** [comment]
Are you using EmuNAND?

**Comment by ems1260** [comment]
Nop.
Sysnand only

**Comment by Robz8** [comment]
Did you install the TWLNAND side CIAs?

**Comment by ems1260** [comment]
For some reason, i cant config internet connections anymore.
Yes i've installed, part 1 and 2.

**Comment by ems1260** [comment]
I've also installed the .cias this guide:  https://3ds.guide/troubleshooting#twl_broken
I've put it to install and delete cias, but once the process is over and the success screen appears, the cias are not deleted( idk if it has something related to the problem thought, so im just reporting)

**Comment by Robz8** [comment]
Sounds like you have a corrupted TWLNAND.

**Comment by ems1260** [comment]
There is a solution for that?

**Comment by Robz8** [comment]
Might have to get a TWLNAND partition from a NAND backup.
iirc, it's possible to read a NAND backup in GodMode9.

**Comment by ems1260** [comment]
Are there any tutorials I can follow to do that?

**Comment by Robz8** [comment]
idk

**Comment by CCF100** [comment]
First thing on https://3ds.guide/troubleshooting

**Comment by Robz8** [comment]
Isn't that what @ems1260 already followed?

**Comment by CCF100** [comment]
Yeah, I derped.
lol sorry

**Comment by ems1260** [comment]
Lol all right dude, thanks for the advice thought. 
So i've been doing a reseach and it seems that its possible to dump and inject a working twlnand on the 3ds via decrypt9/godmode, but it appears to be done in a different way, via an gm9 script called TWL Fix, but I need a working twln.bin, twlp.bin and a twlbr.bin files to do that.
Saddly, idk anyone with a modded 3ds around here that can send me those files. I've searched the file on the infamous "that iso site" but i've found only one of these files and the link is not working anymore.
I've messed up things now :/

**Comment by Robz8** [comment]
Did you ever make a NAND backup before the issue happened?

**Comment by ems1260** [comment]
Sadly not, the mod was made by a store from a nearby city. They gave me the console with this issue and not connecting to the internet, and then they said it was 'normal'. I was a noob on 3ds modding at the time so I believed them.

**Comment by Robz8** [comment]
Seems like you're out of luck for now. :(
