### ISSUE TITLE
Exiting a game with L+R+B+down always crashes

### ISSUE THREAD

**Issue by 18Phoenix** [Robz8/TWLoader#368]
Hello there :)
my 3DS:  New 3DS XL + latest v11.6 + latest Luma3DS 8.1.1 + latest TWLoader 5.5.1

Exiting a game with L+R+B+down always crashes, doesn't matter which type of menu design is chosen :(
I'm loading the roms from SD.

**Comment by Robz8** [comment]
Does a Luma crash screen appear?

**Comment by 18Phoenix** [comment]
I don't know, here's the error message :
 ![tw_exit_crash](https://user-images.githubusercontent.com/31387801/31334742-dce26500-acef-11e7-86d7-f1912c9c8eb9.jpg)

**Comment by Robz8** [comment]
lol, that is the Luma crash screen.
Is it a Luma nightly?

**Comment by 18Phoenix** [comment]
No, the standard release v5.5.1 from the github page.

**Comment by Robz8** [comment]
I said Luma, not TWLoader nightly.

**Comment by Robz8** [comment]
I said Luma, not TWLoader.

**Comment by Robz8** [comment]
I can't help you, then. :(
Works fine for me.

**Comment by josevitorn1** [comment]
I've just updated luma and twloader like a few minutes ago, but this same crash problem is happening to me. Do any of you guys have the solution or it still hasn't one?

**Comment by Robz8** [comment]
No solution, as it always works fine for me.

**Comment by Exagone313** [comment]
I'm concerned by this, I get the exact same screens.
I use an O3DS with everything up-to-date to *releases* (no unstable version), I installed everything today.
I found this post by looking for a way to exit games without going back to the home menu each time.
