### ISSUE TITLE
Compiled the latest release's gui and got a glitched screen 

### ISSUE THREAD

**Issue by ThisIsDaAccount** [Robz8/TWLoader#369]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [x]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [ ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [ ]  Latest release
- [x]  I've compiled myself _[I compiled the latest release myself]_
- [ ]  Old release

###The Problem:
I tried compiling 5.5.1's gui myself with my linux machine. I got a TWLoader.cia after running "make" in the directory, but the .cia froze on a screen with glitched graphics (picture below). I used the latest release of devkitARM on Ubuntu Linux.

![photo oct 08 8 48 22 pm](https://user-images.githubusercontent.com/25249795/31324905-40b6d9fa-ac6c-11e7-9408-25fb318fcf0d.jpg)

**Comment by Robz8** [comment]
5.5.1 used old libs.
