### ISSUE TITLE
The everlasting black screen

### ISSUE THREAD

**Issue by Zisisis** [Robz8/TWLoader#372]
Hello to ya all.I have an old 3ds running boot9strap and luma3ds,both updated to the latest version and the console version is 11.6E.I just installed the latest release of TWLoader using this guide https://github.com/Robz8/TWLoader/wiki/Installation-and-upgrade 
and I tried to run super mario 64 ds and fire emblem shadow dragon,both supported according to his list
https://docs.google.com/spreadsheets/d/1M7MxYQzVhb4604esdvo57a7crSvbGzFIdotLW0bm0Co/edit#gid=0
But i get in both cases an everlasting black screen with light after the ds screen.And then i have to hard reset the 3ds.
Any suggestions will be appreciated.Thank you in advance.

**Comment by Robz8** [comment]
See if this fixes the issue: http://3ds.guide/troubleshooting#twl_broken

**Comment by Zisisis** [comment]
Yep,fixed! Thank you.

**Comment by Robz8** [comment]
No problem. :)

**Comment by hellomynewfriend** [comment]
I tried the same thing but it doesn't works. Pls help.

**Comment by Robz8** [comment]
If you're using a9lh, follow this guide: https://3ds.hacks.guide/a9lh-to-b9s

**Comment by hellomynewfriend** [comment]
Alright, lemme try
