### ISSUE TITLE
How to prepare IDE and 3DS

### ISSUE THREAD

**Issue by thenets** [Robz8/TWLoader#373]
Hi.

Can you help me to setup my PC and 3DS to help to develop this project?
I don't know if is possible but can't learn how to work with TWLoader + nds-bootstrap on Citra.

If you have tutorial will help me a lot.

(I already have installed everything from "contributing.md" guidelines.)

Thanks.

**Comment by Robz8** [comment]
nds-bootstrap won't work with Citra, only TWLoader.
To compile, you'll need to install devkitPro.

**Comment by thenets** [comment]
Hm, so I can only test the TWLoader front-end functions?

**Comment by Robz8** [comment]
Yes.

**Comment by thenets** [comment]
Ah, ok. Sorry about it.
