### ISSUE TITLE
Crash when switching game location to flashcard

### ISSUE THREAD

**Issue by Doriag** [Robz8/TWLoader#380]
### Your 3DS

Tell us which console do you have:

- [x ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x ]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x ]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

In the menu you access with start you can switch game location

 to flashcard
### Actual behaviour

Twloader crash
### Steps to reproduce

1. Launch Twloader
2.Switch game location from sdcard to flashcard
3.Crash

```
```

**Comment by Robz8** [comment]
Try deleting `SD:/_nds/twloader/settings.ini`, and see if the issue persists or not.

**Comment by Doriag** [comment]
It still crash

**Comment by Robz8** [comment]
No clue, then.
Works fine for me.
