### ISSUE TITLE
Some games show "No Info"  and not running properly

### ISSUE THREAD

**Issue by Zakkious** [Robz8/TWLoader#382]
### Your 3DS

Tell us which console do you have:

- [x ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [ ]  >= 11.4
- [x ]  < 11.4 (11.3 SysNand)

### TWLoader version

Tell us which versions you are using:

- [x ]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Show the normal game title instead of no info and run the game properly 

### Actual behaviour

Games showing no info in their titles and not running even when they are compatible

### Steps to reproduce

1.Run TWLoader
2.See the game titles
3.Run them

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by Robz8** [comment]
Press SELECT on the "No Info" titles. What are the filenames you see?

**Comment by Zakkious** [comment]
0434 - New Super Mario Bros. (U)(Psyfer).nds

**Comment by Robz8** [comment]
That game works. Try setting Mario Kart DS as donor ROM.
Follow steps 3-6 of the instructions here: https://gbatemp.net/threads/twloader-ctr-mode-nds-app.448375/

**Comment by Zakkious** [comment]
Already did that and it didn't work at all

**Comment by Zakkious** [comment]
And Super Mario 64 doesn't work anymore after the update, it freezes before the "star" appears on touchscreen

**Comment by Robz8** [comment]
Try updating both bootstraps.

**Comment by Zakkious** [comment]
It didn't work... Just made a fresh install and re formatted my SD card as the guide says : Fat32 and 32kb cluster. I don't know why the new version don't work anymore.

**Comment by NightYoshi370** [comment]
@Zakkious send me your files for those 2 games.

(not here though, in email. Send it to this specific email: maorninja@outlook.com)

**Comment by Zakkious** [comment]
Already fixed it,the problem was my SD card.
