### ISSUE TITLE
Fixes Needed For New Release?

### ISSUE THREAD

**Issue by NWPlayer123** [Robz8/TWLoader#383]
I know y'all have a build system for nightlies but I'm sure other people are waiting for a new "stable" release since you've switched over entirely to pp2d, I'm assuming there's still stuff to implement on that end before you can? Seems like a pretty big milestone worthy of a release (e.g. 5.6.0/6.0.0)

**Comment by Robz8** [comment]
A 6.0.0 is planned.
We already fixed everything for pp2d.
