### ISSUE TITLE
Possible to run TWLoader flashcart roms from home menu?

### ISSUE THREAD

**Issue by ismailhasannnnnn** [Robz8/TWLoader#384]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ X]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [ X]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [X ]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [ X]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

Is it possible to make a 3ds forwarded cia of a TWLoader flashcart rom? That way it's running in DSi mode. I have an R4i Gold RTS card, and I can't get some roms to run without lag, and from the home menu. I'd like to know if it's possible please!

**Comment by Robz8** [comment]
There's an application to make forwarders for DS ROMs on either the SD card or flashcard.
https://gbatemp.net/threads/nds-forwarder-cias-for-your-home-menu.426174/

**Comment by ismailhasannnnnn** [comment]
Right, and i’m trying to use that’s to basically make short cut to a
flashcart rom on TWLoader, so i can’t get rid of lag as well. is it
possible to do that?

**Comment by Robz8** [comment]
Try setting NTR_CLOCK to 0 in sd:/_nds/ntr_forwarder.ini.

**Comment by ismailhasannnnnn** [comment]
I’ve heard that doesn’t work with an R4i Gold RTS, am i wrong?

**Comment by Robz8** [comment]
No, you're right.
Sadly, you'll need to use TWLoader for getting rid of the lag.
