### ISSUE TITLE
Unset donor rom not working on new twloader 6.0.1

### ISSUE THREAD

**Issue by meepingsnesroms** [Robz8/TWLoader#386]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [x]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

It should unset and the pressing start should show "set donor rom"

### Actual behaviour

The menu just closes and if you press start it still says "unset donor rom" so you cant set a new one

### Steps to reproduce

1. Set donor rom
2. Try to unset donor rom

### Stack trace and console log
Not a crash.

**Comment by Robz8** [comment]
That's normal.
To set donor ROM, press select on the ROM, then select "Set as donor ROM".
