### ISSUE TITLE
DS Download Station Freeze

### ISSUE THREAD

**Issue by Torchic09** [Robz8/TWLoader#387]
### Your 3DS

Tell us which console do you have:

- [x]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [ ]  >= 11.4
- [x]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

It should be able to run and create a download station signal.

### Actual behaviour

It freezes trying to make the signal.

### Steps to reproduce

1. Load the rom
2. Press A when it says you can.
3. Basically freezes, but you can press the home button to go back.

### Stack trace and console log

I do not have any crash logs for some reason.

```
```

**Comment by Torchic09** [comment]
i didnt realize there already was one....

**Comment by Torchic09** [comment]
nvmd its a different situation

**Comment by Robz8** [comment]
That's an nds-bootstrap issue.
TWLoader is just a frontend for bootstrap.

It's because wireless doesn't work in general in nds-bootstrap.
