### ISSUE TITLE
Stack dump on running TWLoader

### ISSUE THREAD

**Issue by jotebe** [Robz8/TWLoader#388]
### Your 3DS

Tell us which console do you have:

- [X]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [X]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [X]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [X]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [X]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Open TWLoader
displays updating bootstrap (release)
loads app

### Actual behaviour

Open TWLoader
displays updating bootstrap (release)
crashes 3DS, displaying An exception occurred, & stack dump.

### Steps to reproduce

1. Open TWLoader
2. Wait for update
3. Crash

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

[img_20171120_000801](https://user-images.githubusercontent.com/7555197/33009798-d044baa6-cd8c-11e7-81c7-6be69beb8877.jpg)

[img_20171120_000808](https://user-images.githubusercontent.com/7555197/33009815-e3217ede-cd8c-11e7-83c4-f9072e225b22.jpg)

[crash_dump_00000033.dmp.zip](https://github.com/Robz8/TWLoader/files/1486968/crash_dump_00000033.dmp.zip)

This is the unaltered .dmp file, just added zip extension to make github happy.

```
```

**Comment by Robz8** [comment]
Try turning off wireless, and turn off auto-updating bootstrap.

**Comment by jotebe** [comment]
I did, before the update this worked, but after the latest update it crashed with or without wireless.

I deleted the settings.ini and it is not crashing on startup anymore. I'm not sure if this is a general issue or just a local one, so I will close the issue.
