### ISSUE TITLE
Unable to unset or set new donor ROM after first setting up one

### ISSUE THREAD

**Issue by Kaedalus** [Robz8/TWLoader#389]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [X]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [X]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [ ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [X]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Selecting "unset donor ROM" would allow a new donor ROM to be set.

### Actual behaviour

The "Unset donor ROM" option appears on every game's menu option. Selecting it, on any game, apparently does unset the ROM (since games that needed it stop working). However, all games still show only "Unset donor ROM" as an option on the menu, and I'm unable to set a new one, or even the old one back.

### Steps to reproduce

1. Run TWLoader.
2. Set a ROM as Donor (in my case, Mario Kart DS).
3. Run another DS game.
4. Close TWLoader.
5. Run TWLoader again.
6. Open a game's options menu with Start.

### Stack trace and console log

No crash.

**Comment by Robz8** [comment]
You can actually overwrite the set donor ROM with a new one, using the "Set as donor ROM" option.

**Comment by Kaedalus** [comment]
That is the problem. As I mentioned in the post, every single game shows "Unset donor ROM" in their menus, and they don't have the option to set them as donors.

**Comment by Robz8** [comment]
You press SELECT on the game to pick the "Set as donor ROM" option.

**Comment by Kaedalus** [comment]
Well, that was stupid of me then! Sorry for bothering with that.

This does seem a bit counterintuitive though, so maybe it would be interesting to have both options on the same menu for clarity. :)

Thank you and sorry again!
