### ISSUE TITLE
Homebrew cant access sdcard? 

### ISSUE THREAD

**Issue by The1andONLYdave** [Robz8/TWLoader#39]
Tried with: tyrian 0.3 ( http://gamebrew.org/wiki/OpenTyrian_ds ) 
Or do I have to put the files, which the homebrew looks for in sdcard root, in some of TWLoader's subfolders? 

Other roms work fine, tried a dumped version of a non-homebrew game. 
11.0.2-35 EU
Latest TWLoader (both cia installed) 
Latest Luma and a9loader

**Comment by Robz8** [comment]
Try the unofficial build of bootstrap.

**Comment by The1andONLYdave** [comment]
Thank you, working fully with unofficial build 👍 And thank you for this great Launcher.
