### ISSUE TITLE
"Checking WiFi Status" causes TWLoader to freeze.

### ISSUE THREAD

**Issue by Radtendo** [Robz8/TWLoader#393]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [x]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour
It should be booting up with no freezes.
### Actual behaviour
When I first started up the app, it did the WiFi checking thing just fine and booted up, but other times I've tried booting it up past that have just resulted in the app freezing at the "Checking WiFi Status" message.
Tell us what happens instead

### Steps to reproduce

1. Boot up N3DSXL
2. Start up TWLoader (CIA version)
3. App just freezes when checking wifi status, no other steps than that from what I can tell.

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by Radtendo** [comment]
Should mention that I am indeed on the latest release, 6.0.1

**Comment by Robz8** [comment]
There's a message below "Checking WiFi Status".
