### ISSUE TITLE
DSTT Flashcard initialization not working

### ISSUE THREAD

**Issue by Tux-Prowess** [Robz8/TWLoader#399]
### Your 3DS

Tell us which console do you have:

- [x ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x ]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x ]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

TWLoader should boot into the FC firmware and create ini files of games.

### Actual behaviour

White screen

### Steps to reproduce

1. Start TWLoader
2. Select "Add Games" on any menu skin.
3.

**Comment by Robz8** [comment]
Did you extract the flashcard pack?

**Comment by Tux-Prowess** [comment]
Yes, I have. Put it in the right place.

**Comment by Robz8** [comment]
Did you set the flashcard in the settings screen?

**Comment by Tux-Prowess** [comment]
Yes

**Comment by Robz8** [comment]
What exactly did you extract?

**Comment by Robz8** [comment]
Make sure the flashcard is correctly inserted.
If it is, then I'm out of ideas :(

**Comment by Tux-Prowess** [comment]
For some very weird reason, the DSTT started booting properly for the first time. I swear it's a recurring string of miserable luck.
