### ISSUE TITLE
[Future Requests] Two small folder restructures

### ISSUE THREAD

**Issue by Favna** [Robz8/TWLoader#40]
1. Do not make TWLoader create the `_dsttfwd` and `_dstwofwd` folders automatically as empty folders. Many people in the community care about an as clean as possible SD card, especially root. Having a tool consistently create two empty folders that otherwise completely useless to them is very frustrating. I'm saying hey are useless to them because they are only useful to the person that has either dstwo or dstt and then even if someone has either of those they likely do not have the other. If you insist these folders have to stay please move them inside /_nds at least.

2. Have /roms be in /_nds. While I can see there are a handful of people who already had a roms folder for emulator and such, considering the extreme bulk blindly follows plailect's guide they are likely to not have it. (not to mention that emulators are basically deprecated due to VC injection)

**Comment by NinjaBoyLao** [comment]
Even better: leave all 4 folders as their own separate entities, just shove them all inside /TWLoader. Many apps can't seem to agree which folder to use, /3ds/data/ or /AppName, so just go with the majority here

**Comment by Favna** [comment]
I see this was partially covered in 12b779f4f9523ab988e66bc4d23b26478703a26c but that still leaves the /roms folder
