### ISSUE TITLE
DSOrganize non-functional.

### ISSUE THREAD

**Issue by frozenLake** [Robz8/TWLoader#400]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [*]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [*]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [*]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [*]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [*]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

DSOrganize should at the very least start up.

### Actual behaviour

Error message is given that I do not have the bootstrap. However, rips of cartridge games like Mario Kart DS and Pokemon Diamond boot properly without this error, so I do have the bootstrap. I also have changed LOCK_ARM9_SCFG_EXT to 1 in the ini, to no avail.

**Comment by Robz8** [comment]
You'll need hb-bootstrap.nds from TWLoader.7z, and put it in "sd:/_nds".

**Comment by frozenLake** [comment]
Managed to get it to boot, but now it freezes part way through loading. Not sure if this is on the bootstrap or if I need to set up the files differently, though.

**Comment by frozenLake** [comment]
Is anyone else having problems getting DSOrganize to run?

**Comment by frozenLake** [comment]
The present version gets stuck while initializing settings, if that helps matters at all.

**Comment by frozenLake** [comment]
After asking again on the discord, I learned that supposedly, homebrew only works on bootstrap v0.5.1b.

And with that, I figure this issue is basically "solved", so I'm gonna close it.
