### ISSUE TITLE
New Super Mario Bros. (USA) White Screen

### ISSUE THREAD

**Issue by GuyWhoBreathes** [Robz8/TWLoader#402]
I am currently using a New 3DS XL running Boot9strap with Luma3DS 8.1.1, my firmware version is 11.6.0-39U. I have the latest release of TWLoader installed currently (Ver. 6.1.1). The problem is that New Super Mario Bros (USA) doesn't seem to load up, yet all my other rom's do load up perfectly. I have tried both reinstalling TWLoader (with side cia) and reinstalling the rom. But all I get is a white screen after the DS boot animation. I have waited for it to load for more than even 10 minutes, and still nothing but a white screen on the top and bottom screen of my 3DS. This rom is compatible with TWLoader with the version I am running apparently. Any reason why this isn't working?

**Comment by Robz8** [comment]
Mario Kart DS may not be set as donor ROM.

**Comment by hiperion14** [comment]
I mean it can not be configured as a donor ROM but in another post you said you had to set it up as donor ROM

**Comment by hiperion14** [comment]
![Image of Yaktocat](https://i.ytimg.com/vi/co5KByP8LTo/maxresdefault.jpg)

**Comment by Robz8** [comment]
Is MKDS set as donor ROM, or NSMB?
If the latter, it should be MKDS.
