### ISSUE TITLE
NDS Homebrew not working

### ISSUE THREAD

**Issue by WeZ423** [Robz8/TWLoader#404]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [x ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x ]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x ]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Launch homebrew

### Actual behaviour

White screen
### Steps to reproduce

1.Launch TWLoader
2.Launch NDS Homebrew
3.Crash

**Comment by Robz8** [comment]
A white screen will sometimes happen. Keep trying.
