### ISSUE TITLE
Game stuck on black screen after entering sleep mode

### ISSUE THREAD

**Issue by SirNapkin1334** [Robz8/TWLoader#407]
Tell us which console do you have:

- [ ]  Old 3DS
- [x]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x] SaltMode9 Bootloader [commit f157dcd542f75287bb080fe77642b8fbdc4fdd4a]
- [x]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4 [11.6]
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

After opening the 3DS again, the screen should show whatever was there before sleep mode.

### Actual behaviour

It shows a black screen. Everything works, I can select options (blindly, of course), I hear music, but the screen is black.
The home button shows the "would you like to quit to the home menu?" dialogue and it works.

### Steps to reproduce

0. Boot TWLoader
1. Load ROM.
2. Enter sleep mode
3. Black screen.

### Stack trace and console log
no crash

It should be noted that this is quite similar to #408

**Comment by Robz8** [comment]
Solved in #408.
