### ISSUE TITLE
Pressing Home while in a game causes black screen

### ISSUE THREAD

**Issue by SirNapkin1334** [Robz8/TWLoader#408]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [x]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x] SaltMode9 Bootloader [commit f157dcd542f75287bb080fe77642b8fbdc4fdd4a]
- [x]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4 [11.6]
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

After pressing B to exit from the prompt, the screen should pop back to where you were before pressing it. It should be noted that if the prompt is there for ~<1.5 seconds everything will work normally, but if it stays longer then the screen goes black.

### Actual behaviour

After pressing B to exit from the prompt, the screen stays black. Everything works, sound works, I can work the menus, but the screen stays black until I exit to the home menu. The screen will not go black if you quickly exit the prompt with B (exiting within ~<1.5 seconds will not trigger the black screen).

### Steps to reproduce

0. Boot TWLoader
1. Load ROM
2. Press HOME button, keep on-screen prompt there for at least ~1.5-2 seconds.
3. Exit prompt with B
4. Screen is now black.

### Stack trace and console log
no crash

It should be noted that this is quite similar to #407

**Comment by Robz8** [comment]
Try setting clock speed to NTR for the game you're playing.

**Comment by SirNapkin1334** [comment]
Okay, I'll do that. What's the difference? And do you know why this is caused?

**Comment by SirNapkin1334** [comment]
It worked! Perhaps you could fix the bug if possible, since higher clock speeds are always helpful.

**Comment by Robz8** [comment]
It should be fixed by setting NTR clock speed on sleep mode, then reverting to TWL clock speed when getting out of sleep mode.
idk how to do that, though.
