### ISSUE TITLE
Error! message

### ISSUE THREAD

**Issue by AnGeal5372** [Robz8/TWLoader#410]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [X ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ X]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [ X]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [ X]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [ X]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Should start the game

### Actual behaviour

Rom is loading and stop with written ERROR!

**Comment by Robz8** [comment]
What is the game?

**Comment by AnGeal5372** [comment]
Pokemon all kind

**Comment by Robz8** [comment]
Did you set Mario Kart DS as donor ROM?
If not, check here on how to do it. https://gbatemp.net/threads/twloader-ctr-mode-nds-app.448375/

**Comment by AnGeal5372** [comment]
Still same issue "Error1" with 5 red squares and 4 white/grey squares.

**Comment by Robz8** [comment]
Try formatting your SD card to FAT32 with 32kb cluster size.

**Comment by AnGeal5372** [comment]
I am doomed... still nothing. I was in this format and format again.

**Comment by Robz8** [comment]
Your ROMs might be corrupted, somehow.

**Comment by AnGeal5372** [comment]
MKDS has to be europe or USA format?

**Comment by Robz8** [comment]
If you already tried EUR, then try USA.

**Comment by AnGeal5372** [comment]
Same issue, did it happen to someone else?

**Comment by Robz8** [comment]
Nope. You're the only one with this issue.

**Comment by AnGeal5372** [comment]
Do you think it will have something to do with arm9 / arm11?

**Comment by Robz8** [comment]
No. arm11 doesn't run in TWL_FIRM, aside from it displaying what's on the screen.

**Comment by AnGeal5372** [comment]
ok, i mess up somewhere then I will try to find out tomorrow.

**Comment by ALLZOKU** [comment]
I have the same error as you , when i set only MKDS in donor rom to "on" and the other roms to "off"
