### ISSUE TITLE
LEGO Star Wars - The Complete Saga not loading. Only a white screen.

### ISSUE THREAD

**Issue by bitCoder64** [Robz8/TWLoader#411]
### Your 3DS

Tell us which console do you have:

- [*]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [*]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [*]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [*]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [*]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

The game should launch fine, with a few possible bugs according to the google docs sheet for nds-bootstrap compatibility.

### Actual behaviour

I have turned on console output and waited for the game to load after launching. After the H&S screen there is a white screen and the game never finishes loading.

### Steps to reproduce

1. I downloaded the rom (US version obtained from *removed* after i lost the actual retail cart)
2. Placed it in SD:\roms\nds
3. Booted up my 3ds
4. Launched TWLoader
5. I updated to the latest version of nds-bootstrap (v0.6.1-rev2 at the time of writing this)
6. I launched the rom (1612 - LEGO Star Wars - The Complete Saga UMicronauts.nds)
7. I waited for the H&S screen to show up, then tapped the touch screen to proceed
8. White screen came up and the loading bar never finished

### Stack trace and console log

N/A

EDIT: Eventually, the spinning square pattern freezes and nothing continues to happen. I can still close the app just fine, but the game never finishes loading.

```
```

**Comment by Robz8** [comment]
Try setting Mario Kart DS as donor ROM.
