### ISSUE TITLE
Sonic Rush Adventure (USA or EUR) and NSMB (USA) give me an error "could not read or erase data"

### ISSUE THREAD

**Issue by ALLZOKU** [Robz8/TWLoader#415]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [X ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ X]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [ X] Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version
11.6
Tell us which version do you have:

- [X ]  >= 11.4
- [ ]  < 11.4

### TWLoader version
1st Anniversary (V6.2.0)
Tell us which versions you are using:

- [ X]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Tell us what should happen
Normally the game should work after I put Mario Kart DS into a donor rom but still have this save error

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by Robz8** [comment]
Make sure "Use set donor ROM" is set to On for these games.

**Comment by ALLZOKU** [comment]
Okay , ill try it

**Comment by ALLZOKU** [comment]
Nope , when i set it to "on" in my two other roms , i get a error message while the loading of bootstrap

**Comment by Robz8** [comment]
Your MKDS ROM might be corrupted, then.

**Comment by ALLZOKU** [comment]
I changed the mkds rom , i set donor rom to "on" with the two other rom , i have an error during the loading of bootstrap BUT when i set the two other rom (NSMB & Sonic Rush Adv) i just have a error save who appear in the game
