### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by hiperion14** [Robz8/TWLoader#417]
Help pls when i play super mario 64 show creating save data file and later show a black screen and wen i put a real ds card on my ds another black screen help

**Comment by Robz8** [comment]
Please follow this guide: https://3ds.guide/troubleshooting#dsi--ds-functionality-is-broken-after-completing-the-guide

**Comment by hiperion14** [comment]
thanks I work perfectly but I have another problem what new super mario ds does not work is the blank screen
PS: I have the 2ds and Luma 9.0
