### ISSUE TITLE
metroid prime hunters stack on white screen (when started)

### ISSUE THREAD

**Issue by Ruedzacki** [Robz8/TWLoader#418]
old 3ds
luma3ds - (latest version)
console version is 11.6 - U
metroid prime hunters stack on white screen (when started)
i wait ~20 min.

sorry for bad english.

i really want to play this awesome game on my 3ds..

**Comment by Robz8** [comment]
Only the korean version of MPH works.

**Comment by Ruedzacki** [comment]
korean? but in compatibility list it is written that start in 1-2 minutes (usa version)
ok..
and why only korean version work?

**Comment by Robz8** [comment]
Because USA version was tested on a prior bootstrap version.
And Korean version works, because it uses SDK3.

**Comment by Ruedzacki** [comment]
sorry, but.. will it works in the future? (usa version)
and what's about time? when (according to plan) you can do this?
(ohh.. it's so hard to me to write this.. i hope you can understand what i write)

**Comment by Robz8** [comment]
I'm not sure if I can do this. It's likely @ahezard can, though.
