### ISSUE TITLE
Error After NDS Boot screen.

### ISSUE THREAD

**Issue by DeltAplaS** [Robz8/TWLoader#419]
<!---
###### If you want to create a request, please, delete all text after this message.

Hello,

I am using latest boot9strap and Luma3ds, trying to load Megaman Zero collection (USA) with the latest TWLoader.

The TWLoader opens well and reads all the rom in the SD card however,

when the rom is launched and showing the NDS boot screen, I am getting a screen showing 3 by 3 cubes with loading bar displaying "Error!" on the bottom screen (No white screen nor black screen).

Any advise for a solution will be a great help.

Thank you.

**Comment by DeltAplaS** [comment]
Hello,

I am using latest boot9strap and Luma3ds, trying to load Megaman Zero collection (USA) with the latest TWLoader.

The TWLoader opens well and reads all the rom in the SD card however,

when the rom is launched and showing the NDS boot screen, I am getting a screen showing 3 by 3 cubes with loading bar displaying "Error!" on the bottom screen (No white screen nor black screen).

Any advise for a solution will be a great help.

Thank you.

**Comment by hiperion14** [comment]
what are the error

**Comment by Robz8** [comment]
Is Mario Kart DS set as donor ROM?
If so, if you're running EmuNAND, follow this guide: https://3ds.guide/move-emunand

**Comment by hiperion14** [comment]
one thing happens to me the same but with a game and I gave it to that and it does not work

**Comment by DeltAplaS** [comment]
I am not sure about the donor rom but i will give a try. Plus the error screen has no context. Just says error.

**Comment by DeltAplaS** [comment]
Sorry I am new to this. I do not see emunand file as it is in the instruction you have given Robz8. Any clues?

**Comment by DeltAplaS** [comment]
Well Robz8 it worked. Thank you very much for the cool app.

**Comment by DeltAplaS** [comment]
Well Robz8 it worked. Thank you very much for the cool app.
