### ISSUE TITLE
GB games won't save

### ISSUE THREAD

**Issue by JTT28** [Robz8/TWLoader#422]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [x]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Game should retain save after saving in-game.

### Actual behaviour

Save data is not retained.

### Steps to reproduce

1. Launch GB game through TWLoader.
2. Save in-game.
3. Reset in-game.

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by Robz8** [comment]
Make sure Autosaving is On.
Check by pressing R during the game, then go to settings.

**Comment by JTT28** [comment]
thanks, problem resolved
