### ISSUE TITLE
Weird/Unfamiliar Error Screen

### ISSUE THREAD

**Issue by Superleximus** [Robz8/TWLoader#424]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [x]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [ ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Game should launch.

### Actual behaviour

Game shows weird unfamiliar error screen when launching any game (tested w/ nsmb, latest stable twloader)

### Steps to reproduce

1. Launch a game

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```
![untitled](https://user-images.githubusercontent.com/19824067/34920922-b99532c6-f948-11e7-85fe-bc2bb18050d1.jpg)

**Comment by Robz8** [comment]
Set Mario Kart DS as donor ROM.
Check the first post on GBATemp on how to do that.
