### ISSUE TITLE
TWLoader 6.3.0 crashes when checking for update after 6.3.1 release

### ISSUE THREAD

**Issue by zacchi4k** [Robz8/TWLoader#427]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [X]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [X]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [X]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [X]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [ ]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [X]  Old release

### Expected behaviour

TWLoader shouldn't crash when checking for updates on startup

### Actual behaviour

TWLoader crashes when starting up and checking for updates after 6.3.1 has been released (bringing up the Luma3DS error screen)

### Steps to reproduce

1. Enable WiFi on the 3DS, making sure Internet
2. Open TWLoader 6.3.0
3. Crash

###Crash dump

[crash_dump_00000000.zip](https://github.com/Robz8/TWLoader/files/1661732/crash_dump_00000000.zip)

**Comment by Robz8** [comment]
You'll have to install the TWLoader v6.3.1 CIA to avoid this issue.
