### ISSUE TITLE
Twloader attempts to autoupdate even when auto update is disabled

### ISSUE THREAD

**Issue by meepingsnesroms** [Robz8/TWLoader#428]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [x]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

It shouldnt try to auto update

### Actual behaviour

It trys to auto update nds bootstrap official when set to off

### Steps to reproduce

1. Set all auto update options to off
2. Close twloader
3. Open twloader with wifi on

### Stack trace and console log

This video was taken with both auto update options set to off.

When loading with auto update set to official it takes a while longer so this may be an instance of printing outside the update check and no update occurs.

https://youtu.be/Y8pI63MXGXI

There is also no auto update option available in settings for the unofficial bootstrap even thought it is checked for in main.cpp line 2664.

**Comment by Robz8** [comment]
That's normal.
TWLoader tries to download the official SDK5 bootstrap, but fails because it's not released yet.

**Comment by meepingsnesroms** [comment]
What about no auto update for the unofficial bootstrap?

**Comment by Robz8** [comment]
There should actually be auto-updating unofficial bootstrap.
It's a bug.

**Comment by Robz8** [comment]
Will be fixed in the next version. Thanks for pointing it out!
