### ISSUE TITLE
MK DS Local Multiplayer

### ISSUE THREAD

**Issue by ClassicWolves** [Robz8/TWLoader#430]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
-  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

-  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

-   >= 11.4 ( I currently Run 11.6.0-39U)
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- Latest release (Currently the 6.4.1)
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behavior

The game shouldn't freeze at all, it shouldn't have any issues with Local Multiplayer. 

### Actual behavior

The game frequently and intermittently freezes during local multiplayer. Usually will play perfectly fine after it freezes and has been reset a few times. Will freeze for any type of local multiplayer including Vs and usually freezes right away for Battle Modes. 

1. Game is Quit Suddenly on Vs Mode Multiplayer with Computers Enabled.
2. After The Final Race or sometimes after the 3rd Race, Computers Enabled.
3. If Game is hosted by Rom for Simple or Normal Mode. Freezes Right away after loading into VS Menu to Select the Character.
4. Battle Modes Do not work at all when loading into map always Freezes.

### Steps to reproduce

1. Run Race Mode both as any character. Run Races to finish or quit suddenly and game will free when reentering Vs Mode. CPU any, random tracks.
2. Host a Simple or Normal Game and Run Vs Mode.
3. Run Battle Mode of any kind with CPU on random tracks

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by Robz8** [comment]
That's a bootstrap issue, not a TWLoader issue.
Since we don't know what broke wireless communications, it may not be fixed anytime soon.

**Comment by ClassicWolves** [comment]
Well i do use it frequently would it help if i post some logs?

**Comment by Robz8** [comment]
No, there are no logs generated for bootstrap.
