### ISSUE TITLE
stacks on black screen in every game

### ISSUE THREAD

**Issue by Ruedzacki** [Robz8/TWLoader#432]
1.Old 3DS
2.Luma3DS
3.Latest release
4.>= 11.4

it stacks on black screen in every game. (i tried 3 latest versions)
games, that i tried:
mario cart
castlevania
new super mario bros

**Comment by Barawer** [comment]
try this:
https://3ds.guide/troubleshooting#dsi--ds-functionality-is-broken-after-completing-the-guide

**Comment by Ruedzacki** [comment]
thx, it works
