### ISSUE TITLE
Stuck in white screen booting any game

### ISSUE THREAD

**Issue by Alex25197** [Robz8/TWLoader#436]
### Your 3DS

Tell us which console do you have:

- [X ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [ x]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [ x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [ X]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Boot any game actually in my SD correctly.

### Actual behaviour

Im having a bit of trouble here. Using an O3DS with the latest bootstrap and twloader. Every game I try, boots in a white screen indefinitely. Was trying pokemon soul silver, mario kart(tried it as a donor rom for the other games and nothing), naruto path of the ninja 1, and none of them seem to work. 

Already reinstalled twloader and formatted the SD into 32 bit cluster. Any idea what is happening here? Some releases back, some games were working as Warioware touched but now it doesn't even work. Activating the console output option doesnt show anything, just displays the "booting rom" message and quickly dissappears and shows the infinite white screen.

### Steps to reproduce

1.Start TWLoader
2. Select any game on the list
3.Boot the game
4. White screen appears indefinitely

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by Robz8** [comment]
Try unofficial bootstrap. There's a bug left in the official release.

**Comment by Alex25197** [comment]
Hey, just tried it with the unofficial bootstrap, still no luck. I have to say, this was happening before in an old  version of twloader and the nds-bootstrap, before when I had A9LH.
Any other ideas?

**Comment by Robz8** [comment]
Does Mario Kart itself work?

**Comment by Alex25197** [comment]
Nope, even mario kart doesnt work, it just stays in a white screen :/

**Comment by Robz8** [comment]
What about Super Mario 64 DS?
Also, try turning on loading screen, if it's off.

**Comment by Alex25197** [comment]
Hey, recently tried Super Mario 64 DS too and nothing. I dont know if its important but I only see one Health and safety information screen when it boots a game. It's supposed that it shows two screens of these when I boot a game right?

**Comment by Robz8** [comment]
Yes.
Try updating the bootstraps again.

**Comment by Robz8** [comment]
Oh, try installing the TWLNAND side CIAs again.

**Comment by Alex25197** [comment]
Oh! Thank you very much kind sir, have been with this problem since last year and was driving me nuts! I reinstalled the TWLNand side cias and now the games are working! Thank you very much and keep up the good work with this awesome project!
