### ISSUE TITLE
Open NDS Rom Results in White Screen

### ISSUE THREAD

**Issue by 8380716** [Robz8/TWLoader#437]
Tell us which console do you have:

- [x]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [X]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [X]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [X]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Pokemon Heartgold Version should open and run, potentially with some lag, as long as the rom donor is set to Mario Kart DS. 

### Actual behaviour

Pokemon HeartGold Version loads a white screen. So does Mario Kart DS

### Steps to reproduce

1. Open twloader from home menu screen
2. Tap Pokemon Heartgold icon
3. White screen appears, game does not load

Additional info:
I already checked the FAQ section and that didn't solve the issue. I also looked back at closed issues for this page and going issues that were similar to mine that got solved, but none of these methods seemed to work for me. Any help would be appreciated! Thank you.

**Comment by 8380716** [comment]
Oh yeah, forgot to mention I have the current side cias installed as well.

**Comment by Robz8** [comment]
Format your SD card to FAT32 with 32kb cluster/allocation size.

**Comment by 8380716** [comment]
I believe my SD card is already FAT32, but what is the 32 kb allocation size?

**Comment by Robz8** [comment]
If you're on Windows, go to the format menu, and you'll see allocation sizes.

**Comment by 8380716** [comment]
I should be able to find a similar setting on my Mac when I get time.  If not I'll try to google it.  Thank you!
