### ISSUE TITLE
NDS Bootstrap not found?

### ISSUE THREAD

**Issue by SSQ123** [Robz8/TWLoader#441]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [Y]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [Y]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [Y]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [Y]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Tell us what should happen
Loads NDS bootstrap
### Actual behaviour
Says 'NDS bootstrap not found' and sends me back to home menu
Tell us what happens instead

### Steps to reproduce

1. Download NDS bootstrap
2.Rename to release-bootstrap.nds
3.Choose a game

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by Robz8** [comment]
Make sure you have all the bootstraps from TWLoader.7z.

**Comment by SSQ123** [comment]
I downloaded them when github has TLS support
