### ISSUE TITLE
TWLoader crashes when going through the Welcome to TWLoader Screen

### ISSUE THREAD

**Issue by The-Hacker894** [Robz8/TWLoader#443]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [X]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [X]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [X]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [X]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [X]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

After the _Welcome to TWLoader_ screen I should be taken to the main menu.

### Actual behaviour

After I go through the _Welcome to TWLoader_ screen my 3DS reboots and the FastBoot3DS screen shows. I click _Continue Boot_ and the 3DS crashes.

### Steps to reproduce

1. Update to TWLoader 6.6
2. Open TWLoader and go through the welcome screen

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

[crash_dump_00000014.zip](https://github.com/Robz8/TWLoader/files/1756490/crash_dump_00000014.zip)

**Comment by Robz8** [comment]
Do you have DS ROMs at `sd:/roms/nds`. If so, delete `settings.ini` at `sd:/_nds/twloader`,

**Comment by The-Hacker894** [comment]
Deleting `settings.ini` worked 👌 
Thanks

**Comment by Robz8** [comment]
No problem!
