### ISSUE TITLE
Pokemon Distribution Rom Freeze

### ISSUE THREAD

**Issue by KofiMatson123** [Robz8/TWLoader#446]
I've managed to download one ditribution rom that worked which was for the shiny legendary beasts event in 2011 but if i try any others it freezes on the "Distribution Pending" screen. I got them all from the same site.

**Comment by Jolty95** [comment]
**We don't support piracy.**




###### And that issue is not TWLoader related

**Comment by KofiMatson123** [comment]
Yes you do. Otherwise you wouldnt of made twloader which loads dumped version of games which are pirated.

**Comment by c-schuhmann** [comment]
No, they don't. You can actually dump your own games on your own 3DS with GodMode9. And carrying all your NDS games on a SD Card is slightly easier than carrying 10 catridges in your pocket. Thats the reason why nds-bootstrap and it's frontends (like TWLoader) were created.

**Comment by Robz8** [comment]
DS Download Play currently isn't working for SDK1-4 games.

**Comment by Robz8** [comment]
Try turning off donor ROM for the ones that freeze with "Distribution Pending".

**Comment by KofiMatson123** [comment]
Robz8 at least you helped
