### ISSUE TITLE
Always getting a black screen after starting Mario Kart DS (or any other game)

### ISSUE THREAD

**Issue by Oscarg73** [Robz8/TWLoader#448]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [X]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [X]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [X]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [X]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

After selecting the game, it should work properly.

### Actual behaviour

I'm always getting a endless black screen with which I am forced to force a shutdown, no matter what game.

I installed the latest release of TWLoader following your guide and I have the boostraps updated.

I tried to install the CIAs of "DSi / DS functionality is broken after completing the guide" in the F.A.Q. and the problem persists.

### Steps to reproduce

1.
2.
3.

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by Robz8** [comment]
Are you using EmuNAND?

**Comment by Oscarg73** [comment]
I suppose? I followed this guide to install the CFW Luma3DS long time ago: https://3ds.hacks.guide/

How I can check if I'm using it? I just install the CIAs with the FBI program.

**Comment by Robz8** [comment]
Follow this guide: https://3ds.hacks.guide/move-emunand

**Comment by Oscarg73** [comment]
Since the beginning, the problem was my CFW, that was obsolete.

I followed this tutorial and now I can run Mario Kart perfectly! https://3ds.hacks.guide/a9lh-to-b9s
