### ISSUE TITLE
TWLoader crashes when auto-updating the GUI CIA now

### ISSUE THREAD

**Issue by NinjaBoyLao** [Robz8/TWLoader#45]
Title. It'll go through "updating gui cia" to "downloading bootstrap", and then it just kicks me back to the home menu. editing my settings ini to NOT auto download & install the gui cia lets me boot just fine

**Comment by NinjaBoyLao** [comment]
It's still doing this with auto-update enabled on my o3DS XL. (the only 3ds i have, i forgot to specify)

**Comment by Robz8** [comment]
It'll be fixed in a future release.

**Comment by NinjaBoyLao** [comment]
my bad. I thought it said this was fixed in the last release notes

**Comment by Robz8** [comment]
I mean it always download the latest version, regardless if you are using the latest version.
