### ISSUE TITLE
"fatInitDefault crashed!" when launching DS title from SD

### ISSUE THREAD

**Issue by Nomelas** [Robz8/TWLoader#450]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [x]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [ ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Launching a DS title from sd card should load without errors

### Actual behaviour

Launching a DS title from sd card shows the error "fatInitDefault crashed!" before the bootstrap load screen. The rom still loads anyway so I'm not sure what this impacts (like saves).

Same behavoir or multiple sdk rom versions (sdk5 untested)

Error does not happen when loading from flashcart.

### Steps to reproduce

1. Launch TWLoader
2. Load DS rom
3. Wait for white screens
4. Error occurs
5. bootstrap load screen
6. Game loads normally.

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by Jolty95** [comment]
When the white screen appears, is nds-bootstrap that's loads and not related with TWLoader itself.
I'll wait for Robz8 to answer ;)

**Comment by Nomelas** [comment]
tried both bootstrap versions 0.7.3 and latest unofficial (as of this post)

**Comment by Robz8** [comment]
The message is fake. Ignore it.
