### ISSUE TITLE
Multiplayer, in any way, doesn't work

### ISSUE THREAD

**Issue by GWTRC** [Robz8/TWLoader#453]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [x]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

DS Download and Wireless (both people own the game) Play works, and Wiimmfi (WFC) works

### Actual behaviour

There's a lot of problems with multiplayer. When doing Download Play (I.E. one person is using TWLoader, the other is using the built in Download Play App), the person downloading always crashes. When doing wireless play (I.E. Both people are using TWLoader), the host crashes. When connecting to Wiimmfi (the most popular WFC clone), it gives me a red screen (will edit in picture link later), and when opening DS Download Station, it crashes at "Profiling Wireless Channels."

### Steps to reproduce

1.Try linking another system via Download Play, or connect to Wiimmfi using a patched ROM

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by legoj15** [comment]
For me, trying to create a Download Play room causes a connection error on the host end before the room is even set up

**Comment by Robz8** [comment]
1. Download Play doesn't work, because the code that tells arm7 to do the reads, is in DSi WRAM, and that's inaccessible when trying to use DLP.
2. Wireless Play doesn't work, because the game is probably using a donor ROM.

Both of the above are not the case for the bootstrap that runs SDK5 games.
