### ISSUE TITLE
Pokemon Heart Gold Freezes

### ISSUE THREAD

**Issue by Neheb1** [Robz8/TWLoader#455]
Hello Guys :)

Im using TWLoader 6.6.2. and nds bootstrap on release vers. 0.7.3

my problem is that pokemon heartgold freezes after 10-20 min and i have to restart my 3ds.
is there anything i can do? 
ty for ur answers :)

**Comment by Neheb1** [comment]
i just tried playing again and after some minutes the game froze after i spoke to a trainer. The Music is still playing but the screen froze.

**Comment by Robz8** [comment]
Try AP-patching HeartGold, with a patch from [here](https://gbatemp.net/threads/ap-patch-preservation.477536/).

**Comment by Neheb1** [comment]
thank u i just patched the US Version auf SS but i can't find a german patch, do u have one? 
even better would be a fully AP patched german SS or HG Rom :D 

thank u so much :)

**Comment by Robz8** [comment]
I don't think a german patch exists.
Also, we don't link to retail ROMs here.

**Comment by jhoviktor** [comment]
hello!!!
I've been looking for this for a few months. :) 
so, i have the same problem with my HG, how can i fix my rom with the file "4787 - Pokemon - HeartGold Version (USA).xdelta"?

**Comment by Robz8** [comment]
Use a program called XDelta Patcher.

**Comment by jhoviktor** [comment]
I got it, thank you so much
