### ISSUE TITLE
Set donor ROM failed.

### ISSUE THREAD

**Issue by SmallLuma** [Robz8/TWLoader#457]
I had set MarioKartDS at donor ROM,but SDK4 game not works.
![65c66ade89abf0ddc2be8b850d8f7e11](https://user-images.githubusercontent.com/11296891/37812477-3557ff42-2e9b-11e8-8c9b-5886ed34fbb0.png)
![257bb4127c18ca26242ecb82bfad017c](https://user-images.githubusercontent.com/11296891/37812479-3594e9ac-2e9b-11e8-883f-154063b7708f.png)

**Comment by Robz8** [comment]
I assume the issue is solved, since this is closed?
