### ISSUE TITLE
Game crashes in same point, black screen appears

### ISSUE THREAD

**Issue by PandiWolf** [Robz8/TWLoader#458]
### Your 3DS

Tell us which console do you have:

-  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

-  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
-  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

-   >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

-  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

The game is Ace Attorney Investigations, it´s on the compatibility list and it´s said to work without issues, even there are two of them depending of the game region.

### Actual behaviour

The game is fine, a little of lag is present but it´s playable, the problem appears when you reach a certain point in which a "Evidence" screen should pop up in the inferior screen, but it freezes and then both screens turn black. The only thing you can do is press the home button to close the game
I´ve tried two different roms with different regions each one and both have the same problem exactly at the same point.
It uses Mario Kart as a donor and saves fine, it hasn´t happened to another game before.

### Steps to reproduce

1. Start the game, it doesn´t matter if it's a new start of a saving point before the crash.
2. When you reach the point where they teach you how to present Evidence (the one of the picture below)
![hqdefault](https://user-images.githubusercontent.com/37816396/37946892-48d85e3e-3145-11e8-8aee-6345e305e1e6.jpg)
It should show the following screens:
![captura](https://user-images.githubusercontent.com/37816396/37946907-69ab5e0e-3145-11e8-9516-62959949a576.PNG)
![captura2](https://user-images.githubusercontent.com/37816396/37946908-70c55424-3145-11e8-9b3b-db22d1007f99.PNG)
But before the screens appears completely the game crashes and the screens turn black.

3. The only option after that is closing the game by pushing the Home button.

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
Game crashes
```

**Comment by Robz8** [comment]
I guess to fix it, we'll have to get rid of using donor ROM, and implement save patching for SDK3-4 games, but that's currently not being worked on.
