### ISSUE TITLE
Okamiden (non-USA rom results)

### ISSUE THREAD

**Issue by HRTHXC** [Robz8/TWLoader#460]
Release number: 5605
Title: Okamiden 
Working status: Yellow
Card type: NTR
TID/Game ID: BOOP
Region: EUR
SDK version: 5 TWLSDK
Size: 128MB
Game console: 3DS
Version: 0.7.3
RCS: TWL
USE_ARM7: N/A
MPU_REGION: N/A
MPU_SIZE: N/A
Compatibility colour: Yellow
Compatibility: Playable, but with slow down or freezing on new graphic effects loading in. From a moment to upwind of 15 seconds
Other notes: Mario Kart DS donor rom does not appear to improve the performance of the game
Tested by: immortalmewtwo

Release number: 5238
Title: Okamiden
Working status: Yellow
Card type: NTR
TID/Game ID: BOOJ
Region: JPN
SDK version: 5 TWLSDK
Size: 128MB
Game console: 3DS
Version: 0.7.3
RCS: TWL
USE_ARM7: N/A
MPU_REGION: N/A
MPU_SIZE: N/A
Compatibility colour: Yellow
Compatibility: Playable, but with slow down or freezing on new graphic effects loading in. Anywhere between a moment to upwind of 15 seconds
Other notes: Mario Kart DS donor rom does not appear to improve the performance of the game
Tested by: immortalmewtwo

**Comment by HRTHXC** [comment]
If you need other information please tell me

**Comment by Jolty95** [comment]
Please, add this in [compatibilty list](https://docs.google.com/spreadsheets/d/1M7MxYQzVhb4604esdvo57a7crSvbGzFIdotLW0bm0Co/edit#gid=0) :)
If you don't have access, request there
