### ISSUE TITLE
Auto update never says it's up-to-date

### ISSUE THREAD

**Issue by gingerbeardman** [Robz8/TWLoader#464]
If I have "auto update" switched on, every time I boot TWLoader it tells me there's an update, then it downloads it and quits. I run TWLoader again and the same thing happens. 

I have to actively cancel the update. Now I have auto update switched off because this is so annoying. 

**Expected**  
Should know it's  already updated

**Actual** 
Keeps downloading the same update 

**Versions**
TWLOADER = 6.6.3   
SDK1-4 = 0.7.3  
SDK 5 = 0.7.2

**Comment by Robz8** [comment]
I fixed TWLoader saying there's an update available.
So if you're already on v6.6.3, download that version from GitHub, and just install the GUI CIA.
