### ISSUE TITLE
bowser's inside story already works a little

### ISSUE THREAD

**Issue by pedosjaja** [Robz8/TWLoader#467]
Hello, I just tried mario and luigi bowser's inside story with the most current version of twloader, because with the old versions there is only a red screen that makes the game can not be played. In version 6.6.3 the red screen no longer appears, but with a bit of lag in the nintendo part and when I play it, it does not respond to the buttons, if I give it to the microphone test, a screen comes out black I'm sending this to see if the problem can be solved and make the game playable. By the way, I do not understand how to use this page and I hope you understand ...

google translate xd

**Comment by Robz8** [comment]
Any SD game-related issue goes to the nds-bootstrap repo.
Also, the screen turning black is because donor ROM is being used, so it saves to the SD card, instead of to the DS card slot.
And selecting a save file just freezes on a black screen, due to AP.

**Comment by Jolty95** [comment]
Closing this since is solved 
Next time if you wanna write in Spanish, I will translate to English (or at least do a resume XD)

PS: Nice nickname xD
