### ISSUE TITLE
nintendo 2ds that plays all 3ds games 

### ISSUE THREAD

**Issue by yrgentmessage** [Robz8/TWLoader#469]
i have 2ds that plays all the 3ds games i watched all the videos i can watch and used bootstrap and nothing appears all done off micro sd card i bought the card readerso yeah if u guys wanna download roms try *link removed* and your welcome ok i really need he;lp on this cant wait orginal firmware offline play i just bought the thing so i wouldent use flascart and its urgentmessage i messed up on my name i dont know if the loade because the videos it appears on there also

**Comment by Robz8** [comment]
Don't follow any TWLoader tutorial videos.
Just follow the instructions here: https://gbatemp.net/threads/twloader-ctr-mode-nds-app.448375/
