### ISSUE TITLE
Help With Save Data Issue

### ISSUE THREAD

**Issue by Grendelia** [Robz8/TWLoader#471]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [x]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by Grendelia** [comment]
So everytime i boot up fe12 it says "Could not save data". Works for every other game (even FE11) i have MKDS as a donor. Any help?

**Comment by Grendelia** [comment]
its patched btw. just tried original, doesnt work either

**Comment by Robz8** [comment]
You need an actual DS cart to use as a donor. The cart should have the FLASH save chip, which FE12 uses.

**Comment by Grendelia** [comment]
sadly, my 3ds card slot is broken. every other game works tho.

**Comment by Robz8** [comment]
That's too bad. :(
