### ISSUE TITLE
Doesnt get the Application "FBI"!

### ISSUE THREAD

**Issue by LuigiFan64** [Robz8/TWLoader#472]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ X ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [ ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

I didnt know, what you mean :D Im not a Super Expert in this Content... xD
I can only say, i use a Samsung SDHC Class 4 (4 GB) SD Card. I saw in other Tutorials, they have more Folders then me in their SD Card´s. They have Folders Like "plugins" and this. I only have the Folders "Nintendo 3DS" & "DCIM". Maybe thats the Reason why i doesnt work....? :/

### Console version

Tell us which version do you have:

- [ X ]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [ X ]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

I copied the Files: "_nds" & "3ds" on my SD Card. Then i created a Roms Folder in _nds. After then it should show me the Application "FBI".

### Actual behaviour

But it doesnt show me the Application. There is just nothing.

### Steps to reproduce

1. Copy Files "_nds" & "3ds" on the SD Card.
2. Create the "Roms" Folder in the "_nds" Folder.
3. Copy the Roms into the Roms Folder and start 3DS System.

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by Barawer** [comment]
I dont understand, what does FBI have to do with anything?

**Comment by OmeletHopper** [comment]
Do you mean that FBI was never on the home menu to begin with, or that the CIAs aren't showing up in FBI?

**Comment by Robz8** [comment]
This doesn't seem to be related to TWLoader.
