### ISSUE TITLE
twaloader not showing up

### ISSUE THREAD

**Issue by yrgentmessage** [Robz8/TWLoader#473]
when i create the folders and put the stuff into sd card file slot its not showing up they told me not to watch the videos so the fbi installer not showing up in menu neither is the cia so im stuck and seriouly need help i evan reformatted my 2ds witch lays 3ds games so yeah

**Comment by Jolty95** [comment]
Follow the template you have deleted when creating this issue. 
Also, you have another issue open with the same problem.
Edit the oher one to add the template first
