### ISSUE TITLE
unable to add games off of flashcard

### ISSUE THREAD

**Issue by kurofuneraikou** [Robz8/TWLoader#474]
Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [x]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- x ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

when i click the "add games" icon on twloader, it should let me choose .nds files off of my flashcard

### Actual behaviour

i get a message on the top screen that says "select a game to add to the flashcard game list" and on the bottom of that line of text, it says "initializing
add games
(this text should disappear....
otherwise, trouble!)

the bottom screen is all black 
i've waited several minutes and it doesn't change at all
i have extracted the necessary files that the guide listed, and my flashcard is an m3 ds real if that helps

### Steps to reproduce

1.  literally just click "add games" on the twloader menu, wait a bit, and watch it hang on the screens i've described above

**Comment by Jolty95** [comment]
Did you selected the right FC on TWLoader's settings?

**Comment by Robz8** [comment]
If not, then the "select a game to add to the flashcard game list" screen wouldn't appear.

**Comment by kurofuneraikou** [comment]
![image](https://user-images.githubusercontent.com/38588163/39087860-71720bbc-4575-11e8-949a-00cffab51221.jpg)
Huh, that’s strange. Because these are exactly what my flashcard selection settings are set to. (M3DS Real being in the list in the picture above.)

**Comment by phly95** [comment]
Same issue here, this is what I get when booting into "add games".

![img_20180426_125142979](https://user-images.githubusercontent.com/3526540/39320426-0a878f0e-4952-11e8-8464-8a43c19bc7ce.jpg)
![img_20180426_125157801](https://user-images.githubusercontent.com/3526540/39320427-0a9b9274-4952-11e8-96e7-52a5801452b6.jpg)
![img_20180426_125209983](https://user-images.githubusercontent.com/3526540/39320428-0ab337b2-4952-11e8-8fa6-3b057fd0de63.jpg)

Add Games just boots into the YSmenu and selecting games boots the games instead of adding it to TWloader's game list.

**Comment by Robz8** [comment]
@phly95 You forgot to extract what's in `flashcardsdroot (all)` in `TWLoader.7z`, to the flashcard's SD root.

**Comment by Robz8** [comment]
@phly95 Step 3 in `Rom loading from flashcard/Slot-1` mentions the folder `In TWLoader.7z, extract the files/folders in the "flashcardsdroot (all)" and "flashcardsdroot (flashcardnamehere)" folders to the flashcard's microSD card root. Do not extract the "flashcardsdroot (all)" or "flashcardsdroot (flashcardnamehere)" folders themselves to the microSD card root.`

**Comment by kurofuneraikou** [comment]
Wait, but my issue still exists, though?

Not to sound pushy or anything, but I wouldn’t call this closed yet.

**Comment by Robz8** [comment]
Sorry, no idea how to solve your issue. :(

**Comment by phly95** [comment]
Could you maybe take pictures of the problem you're having so we have an idea?
