### ISSUE TITLE
Solatorobo Doesn't let me use donor rom, save data doesn't work

### ISSUE THREAD

**Issue by ndraconator** [Robz8/TWLoader#476]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [x]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [ ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Tell us what should happen

-be able to press "use donor rom" after pressing select on Solatorobo

### Actual behaviour

Tell us what happens instead

-"use donor rom" doesn't appear as an option

### Steps to reproduce

1. Press Select
2. See No Option
3. Start Game
4. Unable to access save data once game loads
### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by Robz8** [comment]
Solatorobo is compiled with SDK5, so you need a donor *cart*, not a donor ROM.
Put in a DS cart in the slot to use as donor.
