### ISSUE TITLE
Pokemon SoulSilver Unrecoverable Hangs

### ISSUE THREAD

**Issue by W3AXL** [Robz8/TWLoader#477]
Tell us which console do you have:

- [x]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [ ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Game runs fine, with minimal visual glitches according to the nds-bootstrap compatibility table

### Actual behaviour

After a half hour or so, sometimes sooner and sometimes later, the game hangs in an unrecoverable state. Music continues to play with no problems indefinitely, but the game remains frozen on the last rendered frame and no button inputs work. Home button will return to home and power button will turn off the console, however. 

### Steps to reproduce

1. Play the game until it hangs. It almost always happens during an interaction with an NPC, entering menus, or changing between map areas. Seems to happen only after about 15-20 minutes of playing.

### Stack trace and console log

Just enabled logging and will report back.

**Comment by W3AXL** [comment]
Log file provides no additional messages. Game still hanging, music still continuing on with no issues. Very likely an NDS-Bootstrap issue and not a TWLoader issue but any help is appreciated.

**Comment by Robz8** [comment]
Do some sprites get glitched before it freezes?

**Comment by W3AXL** [comment]
One of the first times it happened the top screen became solid red. One other time I can think of, the character sprite did get corrupted. Every other time, however, the screen stays frozen on whatever was last displayed with no change or glitching. Seems to happen more often when fading to black during a map area change or a menu change.

**Comment by Robz8** [comment]
The ROM needs to be AP-patched.
You can get the patch from here: https://gbatemp.net/threads/ap-patch-preservation.477536/

**Comment by W3AXL** [comment]
Applied the patch and still no change. The most recent crash had several graphical glitched. Was able to save the game as soon as they appeared, but trying to enter a building caused the same unrecoverable black screen with perfect music.

**Comment by Robz8** [comment]
Well, we hope to fix this issue soon.
