### ISSUE TITLE
Pokemon Soul Silver Graphics Issue

### ISSUE THREAD

**Issue by donaquill** [Robz8/TWLoader#478]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [X ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [X ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [ ]  >= 11.4
- [X ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [X ]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Tell us what should happen
Game runs good and doesn't have graphical glitches that make the game have a black screen
### Actual behaviour
Has graphical glitches that make the game have a black screen
Tell us what happens instead

### Steps to reproduce

1. Randomly bugs out and sprites get weird
2. If I go into a room or open a menu my game hangs forever with working music
3.

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by Robz8** [comment]
Unfortunately, that's something we currently can't fix. :(
But, whenever you get the graphical glitches, you can save your games. Don't worry, your save will not corrupt.

**Comment by donaquill** [comment]
Okay, thank you for responding.
