### ISSUE TITLE
Cannot get Fire Emblem: New Mystery of the Emblem (translated) to work

### ISSUE THREAD

**Issue by Myetche** [Robz8/TWLoader#481]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [x]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [ ]  >= 11.4
- [x]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

The game plays normally

### Actual behaviour

I briefly see the copyright screen for a split-second, then it cuts to "Unable to save data" and I can't play it

### Steps to reproduce

1. Mario Kart DS is set as donor ROM
2. No game is in the slot
3. System is kept offline and TWloader was updated manually

### Stack trace and console log

```
```

**Comment by Myetche** [comment]
Alright, but is there a specific game I need for it or just anyone?

**Comment by Robz8** [comment]
The cart must contain a FLASH save chip.
Check here: http://www.advanscene.com/

**Comment by Myetche** [comment]
Well, I tried it with my copy of Pokemon Platinum in the slot. It runs now, but very slowly and poorly. I don't suppose there's a way to fix that, is there?

**Comment by Robz8** [comment]
Nope.

**Comment by Myetche** [comment]
Well, thanks anyway.
