### ISSUE TITLE
2ds xl 

### ISSUE THREAD

**Issue by yrgentmessage** [Robz8/TWLoader#482]
it wont let me install anything from the menu so how em i gonna get anything install if wont let me in rolina menu i guess i gave make youtube video and shows you guys stuff not working so yeah 
and my case got closed so i couldent reply

**Comment by Robz8** [comment]
Have you followed http://3ds.hacks.guide/ yet?

**Comment by Jolty95** [comment]
You can write on the other issue despite being closed

**Comment by yrgentmessage** [comment]
send me the link for the cfw stuff and i will install but like i said think its on my sd card because what your guys instruction told me what to by putting on the root of the sd and make folder then copy item into folder with steps i did and follwed and nothing was allowed so yeah i remeber my wii when i hacked it that was flawless this becoming pain my butt.

**Comment by Robz8** [comment]
This is the guide to install CFW.
http://3ds.hacks.guide/
Just click this link above.

**Comment by yrgentmessage** [comment]
ok i dident know this was still up our i would have left the video on for you guys to see it but anyways what i said was i open a new one because i thought got close what i did what the guides said to is create the folder drag the item in those folder then go to roselina menu i evan tryed diffrent comobo bin config and wouldent let me access it so where do i download the cfw at so i can bring up those titles from is this site our not i wasent being mean our nasty i just needed help please let me know if you seen that youtube video i posted

**Comment by Robz8** [comment]
I haven't seen the video, cause it got removed.

**Comment by yrgentmessage** [comment]
i put it back up btw for another 20 minutes our so https://www.youtube.com/watch?v=da9bHuYnPSM

**Comment by Robz8** [comment]
Yeah, I see you can't access rosalina menu. That means that Luma CFW isn't running, even if it's on the SD card.

So again, please follow http://3ds.hacks.guide/ to get CFW working, so that you'll be able to access rosalina menu.
Please understand that it's not possible to get CFW working quickly like saying a magic spell, or some other quick thing, so I strongly advise that you follow the guide to get it working. It may take time, but it'll be worth the time.

**Comment by yrgentmessage** [comment]
thats were im having the trouble at it doesent show werre the cfw is availble for download i mean show torrents on it but i still i u torrent and sometimes the dam thing freezes on some torrents thow

**Comment by Robz8** [comment]
Ohhh.
Try [BitTorrent](http://www.bittorrent.com/).

**Comment by yrgentmessage** [comment]
thank you for helping me and another is were the download for the cfw it just tells you how to install so yeah i read something earlier that showed you had have torrent installed but were is the cfw download i mean i evan tryed a roslina combo.bin configurestion that toke me to this site ssine im new and im sorry if i sounded mean our nasty tords anyone so yeah

**Comment by Robz8** [comment]
The torrents, which the guide has, contain downloads.

**Comment by Robz8** [comment]
No problem.
Also, make sure you aren't skipping any steps.

**Comment by yrgentmessage** [comment]
i wasent i ddi what that guide said i wounder why the cfw one not up there it takes you current releases for it so yeah
