### ISSUE TITLE
trying to load my R4 card in TWLoader in 3dsx format shows black screen.

### ISSUE THREAD

**Issue by xoscarstar123x** [Robz8/TWLoader#490]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [x]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [ ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [x]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

It should load into the Wood kernel from my r4 card.

### Actual behaviour
. it recognizes my card in slot one after i press A the screens go completely black. My status lights like my power and wireless led's stay on.

### Steps to reproduce

1. Im not sure what this means
2.?
3.?

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by Robz8** [comment]
You need CFW to run games/your Slot-1 card in TWLoader.
