### ISSUE TITLE
Castlevania: Dawn of Sorrow (EUR) - permanent white screen

### ISSUE THREAD

**Issue by ChiliSixkiler** [Robz8/TWLoader#494]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [x]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

The game Castlevania: Dawn of Sorrow (EUR) can be played

### Actual behaviour

I see the Game in the TWLoader menu. After starting, Health and Safety is displayed, then a white screen followed by a 'loading' message and a greay loading bar. Once the loading bar is full, TWLoader stays stuck in a permanent white screen.

### Steps to reproduce

1. TWLoader should be correctly installed (I followed the wiki)
2. I start TWLoader and see the game and open it

Note: The exact same ROM works perfectly fine with my brother's o3DS (I copied it from his SD card, we both own the game), no permanent white screen (and no 'loading' message) for him.
Also, Mario Kart DS works on my N3DS, so this seems to be a specific problem with Castlevania.

Thanks in advance!

**Comment by Robz8** [comment]
Try force-using donor ROM for Castlevania.

**Comment by ChiliSixkiler** [comment]
Partially worked! Now I at least get to the title screen, but the sound's completely messed up and my save doesn't load.
I followed plailect's guide, so I'm pretty sure I've got DSP1 installed. 
I tried using both unofficial and release sdk versions and both AMR9 clocking speeds.

**Comment by Robz8** [comment]
Try formatting your SD card to FAT32 with 32kb cluster size.

**Comment by ChiliSixkiler** [comment]
Okay, I finally managed to do it, even used a new 32GB card (had 64GB before), unfortunately nothing changed, the exact same thing happens, distorted sound and the save file can't be loaded.
Do you have any other ideas how to solve this?

**Comment by Robz8** [comment]
Can you try it with latest unofficial bootstrap?

**Comment by ChiliSixkiler** [comment]
Still not working :( The settings menu shows me that I'm using SDK1-4: Unofficial 8ad3163, SDK5: Unofficial 17b9065, I'm on TWLoader Ver. 6.6.4, using MK: DS as donor rom and set it to force-use donor rom.

**Comment by Robz8** [comment]
Try not force-using donor ROM.

**Comment by ChiliSixkiler** [comment]
It works!! I switched donor rom to "off" for Castlevania and now it's finally working. Must have been connected with the cluster size on my new SD card, as I had the same setting with the old one and it wasn't working. 
Anyway, thank you very much for your help and for TWLoader Robz8, I hope this thread might help some other people in the future having the same problem as me.
