### ISSUE TITLE
Black Screen on Launch

### ISSUE THREAD

**Issue by Oshawott5000** [Robz8/TWLoader#495]
Well whenever I am trying to launch nds games on TWloader  on the latest version v6.6.4 the game shows the Safety screen but then the screen turns black. Well that is not exactly why I am typing this issue.
I found this  tutorial by the creator himself : https://3ds.guide/troubleshooting#twl_broken 
But there are magnet links which I tried to download through deluge but did not work for me, I also tried BitTorrent . So what I am asking is Does anyone have direct downloads for the magnet links on the website mentioned above.
Sorry for my Broken English.
Please take my report into concern.
Thank You in advance.

**Comment by Robz8** [comment]
It is illegal to post direct download links here.
Try waiting when trying to download via the magnet links.

**Comment by Robz8** [comment]
The one you're following.

**Comment by Oshawott5000** [comment]
So I followed this tutorial :DSi / DS functionality is broken after completing the guide.
I got the cias through uTorrent. But even after installing the cias my 3ds launches Pokemon SoulSilver but then it goes to the safety screen and then the black screen.
I have a new 3DS xl with firmware 11.6.0-39U and I use TWloader v6.6.4.
Can you please help me Robz8. I always wanted to play ds games off sd card but it just wont work for me.
Thank You for your support.

**Comment by Robz8** [comment]
Are you using EmuNAND?

**Comment by Oshawott5000** [comment]
As I said before I dont know a lot about 3ds hacking, so I dont know which nand I am using. Is there a way to check the nand which I am using.
I am sorry for my foolishness and your inconvenience.
Please help me.

**Comment by Oshawott5000** [comment]
<img width="617" alt="capture" src="https://user-images.githubusercontent.com/39460266/40341739-755d731e-5da4-11e8-8f1d-16c6b363a155.PNG">
this is the photo of the root of my micro  sd card if this help.

**Comment by Robz8** [comment]
Follow this guide, then: https://3ds.hacks.guide/a9lh-to-b9s

**Comment by Oshawott5000** [comment]
Is there an step in the guide which requires the use of L trigger since mine is broken and I am unable to use it. Anyways thank you.

**Comment by Robz8** [comment]
There are no steps that say to use the L trigger button.

**Comment by Oshawott5000** [comment]
Bruh I love you. Thank You for your support I updated to boot9strap and TWloader works for me now.
I am really thankful @Robz8 .
Thank You for helping and supporting me.

**Comment by Oshawott5000** [comment]
I am really thankful, playing ds games on 3ds for free is like a dream come true.

**Comment by Robz8** [comment]
No problem!
