### ISSUE TITLE
Crashing on game selection screen after half a second.

### ISSUE THREAD

**Issue by laicyre** [Robz8/TWLoader#496]
###### Issues about asking for support for piracy will be closed.
-->
### 

Tell us which console do you have:

- [O]  Old 3DS I have

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Luma3DS
and sysnand al9h? Unsure

### Console version

Tell us which version do you have:
=
- [ 11.3]  < 11.4

### TWLoader version
6.4.4
Tell us which versions you are using:

- [ ]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Steps to reproduce

1.Soundhax\lumacfw from 3dshack guide instruction.
[crash_dump_00000009.txt](https://github.com/Robz8/TWLoader/files/2020493/crash_dump_00000009.txt)

2.Install tw loader works fine
3. Adds games
4. starts crashing

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by laicyre** [comment]
Double post sorry, I'm not quite sure how to post the crash dump, so if its posted incorrectly, I can repost it later. I simply changed it to a .txt file so that it would upload.

**Comment by Robz8** [comment]
Are you using a Luma nightly?

**Comment by laicyre** [comment]
9.  0 . 0

**Comment by Robz8** [comment]
Try deleting `settings.ini` at `sd:/_nds/twloader`.

**Comment by laicyre** [comment]
I tried that, did not work unfortunately

**Comment by laicyre** [comment]
Yea, quite a few

**Comment by laicyre** [comment]
Should I try it without them?

**Comment by Robz8** [comment]
Yeah.

**Comment by laicyre** [comment]
That definitely fixes it, the games I had on at the time were phantasy star zero, super mario 64, mr.driller spirits, mkDs, Wild world, mario hoops, and megaman zx

Are any of these known to cause problems?

**Comment by Robz8** [comment]
One of the ROMs might be corrupted.

**Comment by laicyre** [comment]
Thanks for the advice. I'll post which one is giving issues, hopefully its not all of them.

**Comment by laicyre** [comment]
it was megaman zx causing it, I think it may have something to do with the game versions, not completely sure

though as a different issue, these are now popping up alongside certain roms

https://cdn.discordapp.com/attachments/303792545538899968/448005366433841173/JPEG_20180520_231312.jpg

it seems to be a non issue as everything else seems to work as intended

thanks for your help

**Comment by Robz8** [comment]
No problem!
