### ISSUE TITLE
Pokemon Black (Not Loading)

### ISSUE THREAD

**Issue by Oshawott5000** [Robz8/TWLoader#497]
Hello, sorry to bother you again, but is Pokemon Black compatible ?
Every time I start Pokemon Black, it loads but then some sort of error pops up which says :
The save data could not be accessed.
Please turn the power off and reinsert the Game Card.
(The error is displayed by the game not TWloader)
Thank You in advance.
I have twloader vesion 6.6.4.

**Comment by Robz8** [comment]
You need a donor cart with the same save ship as Pokemon Black.
Check here for what carts you own: http://www.advancscene.com/
