### ISSUE TITLE
Saves could not be loaded

### ISSUE THREAD

**Issue by GaanWeWeer** [Robz8/TWLoader#498]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [X ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [X ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [X ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [X ]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [X ]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Tell us what should happen
that i can play the game
### Actual behaviour

Tell us what happens instead
I lauched the game and i get the message "
### Steps to reproduce

1.Copy game to roms/NDS
2.Start game

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
I dont have a crash report
```

**Comment by Robz8** [comment]
If the game you're trying to run is SDK5 (can be checked by pressing SELECT on the game in TWLoader), then you'll need a donor cart.
