### ISSUE TITLE
software closed everything works until dsi loading screen

### ISSUE THREAD

**Issue by faizanp123** [Robz8/TWLoader#506]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ x]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [ x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x ]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Tell us what should happen
I expect it to go pass the dsi screen without saying software closed and let me play
### Actual behaviour
Tell us what happens instead
when I start the app it lets me choose rom and then it loads the dsi screen but then it flashes black and turns off and I don't know what to do. 11.6 is my 3ds software
### Steps to reproduce

1. open twloader
2.open rom
3.get software closed error

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by faizanp123** [comment]
please help me I keep getting software closed screen when trying to play rom.  I tried steps on troubleshooting web but it didn't work

**Comment by Robz8** [comment]
What happens when you launch DS Download Play from the 3DS HOME Menu?

**Comment by faizanp123** [comment]
when I open download play it just kick me out and says software closed

**Comment by Robz8** [comment]
This is definitely not normal.
Are you using A9LH or Boot9Strap?

**Comment by faizanp123** [comment]
boot9strap
I agree I don't know why

**Comment by faizanp123** [comment]
Any suggestions on what I can do to make it work

**Comment by Robz8** [comment]
Try restoring a NAND backup.

**Comment by legoj15** [comment]
Making one now and restoring it will do nothing, since it will likely just copy over what is causing the problem.

**Comment by Robz8** [comment]
@faizanp123 What are your Luma settings?

**Comment by faizanp123** [comment]
Payload type is SIGHAX payload oath is boot.firm and backup payload is yes version 9.0

**Comment by Robz8** [comment]
Welp, I'm out of ideas. :(
You are the only one who reported this issue.
