### ISSUE TITLE
"An exception occurred" on startup

### ISSUE THREAD

**Issue by ChromoTec** [Robz8/TWLoader#507]
### Your 3DS

Tell us which console do you have:

- [x]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

TWLoader should boot into ROM menu

### Actual behaviour

TWLoader boots into ROM menu = for half a second, then gives me "an exception occurred" screen.
### Steps to reproduce

1. Open TWLoader

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
[crash_dump_00000000.zip](https://github.com/Robz8/TWLoader/files/2077590/crash_dump_00000000.zip)
```
### Additional information
I had this same problem yesterday (issue #503) and did what Robz8 said, but now I can't even boot into the menu, even if this is the first time opening it. I have uninstalled and reinstalled TWLoader, but to no avail.

**Comment by Robz8** [comment]
I have no idea how to solve your issue, so use SRLoader for now.
