### ISSUE TITLE
Games not working on TWLoader or DSiMenu++ Bpotstrap 0.9.0

### ISSUE THREAD

**Issue by Probobum** [Robz8/TWLoader#509]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [X ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [X]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [ ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [ ]  >= 11.4
- [X]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [X]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour
The Legendary Starfy should not be corrupting save data.

### Actual behaviour

Starfy corrupts save data (it seems to save fine but upon re-booting the game you get a message stating File 1 and 2 are corrupt)

### Steps to reproduce

1.
2.
3.

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by Robz8** [comment]
Wait for the next version of nds-bootstrap for saves to be read correctly, or try updating/switching to latest unofficial bootstrap.
