### ISSUE TITLE
Hey! I am on 3ds version 11.6.0-39U with Luma 3ds CFW. When I install TWLoader v. 6.7 and try to open the TWLoader app, it instantly results in a crash. Is there anything you can do for me?

### ISSUE THREAD

**Issue by dhruvna** [Robz8/TWLoader#510]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [x]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by dhruvna** [comment]
Expected Behavior:
I thought TWLoader should open so that I can play compatible NDS roms. 

Actual Behavior:
Opening the TWLoader app (after installing the CIAs) results in a crash everytime. 

Steps to Reproduce:
I installed based on the tutorial on the website for "Starting from Scratch"
I then installed CIAs
Opened the app, and it crashed.

Thank you!

**Comment by Robz8** [comment]
That's a known bug. You have to hold Y+A before the ROM menu appears.

**Comment by Robz8** [comment]
Also, you should be using DSiMenu++ instead.
