### ISSUE TITLE
App Volume Detects Wrong for 2DS

### ISSUE THREAD

**Issue by rpalmon** [Robz8/TWLoader#62]
There is a bug where I have the volume up on the 2DS but the application does not make any SFX. 

Also, is there a way I could use my Blue Gateway Card with this? How?

**Comment by GerbilSoft** [comment]
Does the volume indicator in TWLoader show an X on the speaker icon? If so, you'll need to dump the DSP firmware.

Run DspDump from Homebrew Launcher: https://github.com/Cruel/DspDump

Gateway Blue Card is supported using the Ace 3DS+/Gateway Blue Card/R4iLS/R4iTT forwarder pack. (See the first post in the TWLoader thread: https://gbatemp.net/threads/twloader-ctr-mode-nds-app.448375/)

**Comment by Jolty95** [comment]
All is in the Wiki. Please, read it

**Comment by bakawun** [comment]
So i used my DSi XL on 1.4u and 2ds with twloader running to compare the behaviour in audio between the 2.

First up the DSi XL,
There is no audible feedback/sfx sound when pressing the volume up or down buttons to adjust volume.
There is background audio playing.
There are 8 possible positions for the audio to be in:

volume at position 1 of 8 has a  grey icon with 0 waves and 3 dots "..."
volume at position 2 of 8 has a black icon with 0 waves and 3 dots "..." 
volume at position 3 of 8 has a black icon with 0 waves and 3 dots "..."
volume at position 4 of 8 has a black icon with 1 waves and 2 dots ").."
volume at position 5 of 8 has a black icon with 1 waves and 2 dots ").."
volume at position 6 of 8 has a black icon with 2 waves and 1 dots "))."
volume at position 7 of 8 has a black icon with 2 waves and 1 dots "))."
volume at position 8 of 8 has a black icon with 3 waves and 0 dots ")))"

Next twloader
There is no audible feedback/sfx sound when pressing the volume up or down buttons to adjust volume.
There is NO background audio playing.
The slider has no externally visible number of positions but i think its position on the slider conforms to a digital position on the 3ds.

Slider at bottom has a  grey icon with 0 waves and 3 dots "..."
slider slightly moved, about 1mm, has black icon with with 1 wave and 2 dots
about 1/4th along the way the 2nd wave appears,
about 60% along the way the 3rd wave appears.

Depening on the volume level before starting twloader the relative positions on the slider change a bit.

Conclusion:
There is no sfx when adjusting volume
The dsi uses 8 positions for audio, twloader does not accurately simulate this behaviour with the volume slider.

So the volume code needs to be changed so it accurately reflects the 8 stages of volume from the dsi.

**Comment by bakawun** [comment]
I think this ticket can be closed now as several commits where made to modify the volume graphics.
Most imporantly this commit here https://github.com/Robz8/TWLoader/commit/fbcae2bfd19fcb26d296342a89e9945b4698eafa made it more clear when dsp firm is missing.
