### ISSUE TITLE
Load GBA roms

### ISSUE THREAD

**Issue by chronoss09** [Robz8/TWLoader#64]
It's possibl to make a guide for how to launch a GBA rom ?

**Comment by Jolty95** [comment]
I haven't create it because gba roms loading is not very stable right now. But basically you need to put your rom as `runner.gba` and `bios.bin` in `SD:\` 's root

**Comment by chronoss09** [comment]
It doesn't work. I test with 2 rom and i get a freeze....

**Comment by Jolty95** [comment]
GBA rom loading is not very stable right now. Also, most roms doesn't work neither
