### ISSUE TITLE
Forwarder.jar doesn't work on Linux

### ISSUE THREAD

**Issue by Flubbex** [Robz8/TWLoader#68]
Scenario: Terminal -> java -jar Forwarder3DS.jar
Error: Could not find or load main class com.olmectron.forwarder.Forwarder3DS
Issue: Not becoming a Java developer just to figure out how to run a dumb .ini generator.
Solution: Fix the .jar provided in the wiki so I don't have to waste 2 hours of my life studying cryptic Java docs and still not have it run.

**Comment by Jolty95** [comment]
What Java version are you using?
AFAIK Forwarder use **JAVA 8**

**Comment by Flubbex** [comment]
Same error on 7 as well as 8 (OpenJDK). Some difference in how openjdk handles .jar files?

**Comment by Jolty95** [comment]
I can't tell you how openjdk handles then because I think source code of forwarder is not public. I can tell you to install JavaFX because is needed as show [here](https://gbatemp.net/threads/nds-forwarder-cias-for-your-home-menu.426174/)

**Comment by Flubbex** [comment]
Works perfectly fine now, thank you! Might want to add to the wiki that you need JavaFX (OpenJFX on Arch) to make it work.
