### ISSUE TITLE
Boxarts are not downloading

### ISSUE THREAD

**Issue by deadair3210** [Robz8/TWLoader#71]
When the app starts, it checks for and looks to download the boxarts for my roms that are on my flashcard, but everything in the menu is listed as No Info with a black box with a ? mark

**Comment by GerbilSoft** [comment]
If you have flashcard INIs from v2.3.1.or earlier, they don't have the required information for boxart download (the title OD). You'll need to delete the INIs and recreate them using the "Add Games" function.

**Comment by deadair3210** [comment]
I have the ini's created by the latest version of the tool, i can upload one if that would help

**Comment by deadair3210** [comment]
Just regenerated the ini for one of my games, all that is in the ini is NDS_PATH and BNR_TEXT 1 through 3

**Comment by Robz8** [comment]
Don't use Forwarder3-DS to create the .inis.

**Comment by deadair3210** [comment]
![sfdsac](https://cloud.githubusercontent.com/assets/1053504/21991272/81500362-dbd7-11e6-9f0a-914af144889a.PNG)

**Comment by Robz8** [comment]
The instructions are out of date.

**Comment by deadair3210** [comment]
So what should I use?

**Comment by Robz8** [comment]
Use the "Add Games" function, like GerbilSoft said.
If it's not working for your flashcard, then please wait 'til it gets supported.

**Comment by deadair3210** [comment]
Sorry, I guess I'm still half awake and didnt read that all the way. Thanks!

**Comment by deadair3210** [comment]
How do you use the Add Games functionality exactly, I have a R4i 3DS, but when I hit Add Games, it launches YSMenu and then I select a game, and the game launches. If I hit home and restart, and then launch TWLoader the game isnt there

**Comment by Robz8** [comment]
Update the pack for your flashcard.

**Comment by deadair3210** [comment]
Was there an update yesterday? I just set up the card yesterday

**Comment by deadair3210** [comment]
I downloaded the pack for the R4i SDHC as you had told me to use it before on the list in the app, since my card is not mentioned by name

**Comment by Robz8** [comment]
DSTT/R4i-SDHC?

**Comment by deadair3210** [comment]
I have the R4i-3DS, and I downloaded the R4i-SDHC package(DS Game Forwarder pack (DSTT, R4i Gold, R4i-SDHC, SC DSONE).7z) 

Here is a pic of my flashcard
![img_20170116_111318](https://cloud.githubusercontent.com/assets/1053504/21992702/13ba6396-dbdd-11e6-818f-6817ec042a98.jpg)

**Comment by Robz8** [comment]
Is TTfwd.dat 228KB?
If so, then it should work. Make sure you also have TWLoader v2.4.2.

**Comment by deadair3210** [comment]
TTfwd.dat is in fact 228 KB and I do have 2.4.2

Is there anything I can maybe run or do to help figure out what is happening?

**Comment by Robz8** [comment]
Extract what's in the "flashcardroot" folder to the flashcard root.

**Comment by deadair3210** [comment]
![6352](https://cloud.githubusercontent.com/assets/1053504/21993074/9c4bb18c-dbde-11e6-9d4e-da81bd5109bd.PNG)

**Comment by Robz8** [comment]
The "flashcardroot" folder is in the TWLoader 7z file.

**Comment by deadair3210** [comment]
![fgnhgn](https://cloud.githubusercontent.com/assets/1053504/21993228/663a2294-dbdf-11e6-8e0d-4a9eaf0f1d00.PNG)

**Comment by Robz8** [comment]
Correct. Put the "_nds" folder containing "twloader.nds" in the flashcard root.

**Comment by deadair3210** [comment]
Don't know how I missed putting those on the flashcard! Thanks! Working perfectly now. One last question, is there any way to add a entire folder at a time?
