### ISSUE TITLE
TODO: if boxart .png exist, do not re download it

### ISSUE THREAD

**Issue by Jolty95** [Robz8/TWLoader#72]
Just write here if I forget to add it

**Comment by Robz8** [comment]
That's already done.

**Comment by Jolty95** [comment]
I'm still gettings boxarts download when I use my own boxarts

**Comment by Robz8** [comment]
Oh, ok. It currently only checks the boxart by game TID instead of filename for now.

**Comment by Jolty95** [comment]
Are you going to include to search by filename too or just rename my box arts to TID?

**Comment by Robz8** [comment]
We'll see.

**Comment by maorninja** [comment]
Since this has already been implemented, can someone close this?

**Comment by Jolty95** [comment]
It is not implemented yet! It's searching by TID not filename for now https://github.com/Robz8/TWLoader/blob/master/gui/source/download.cpp#L498

**Comment by Jolty95** [comment]
https://github.com/Robz8/TWLoader/pull/122
