### ISSUE TITLE
[maybe a bug] TWLoader crashes if there is no rom in the SD.

### ISSUE THREAD

**Issue by Valeri0p** [Robz8/TWLoader#74]
Hi, sorry for my English, but maybe i founded a bug in the app.
Start TWLoader without any rom in the SD:\roms\nds\ folder make it crash. It first says in the topscreen " No games found! Put .nds...", then it freeze, and after that it send you to the "An error as occured, please restart...".
Put a rom in the folder seem to fix that.
I'm using v2.4.2, with luma 3ds 6.6 on a9lh, I have installed both .cias (twl nand side and ctr side).
Thanks for reading.

**Comment by Robz8** [comment]
This will be fixed in the next version.

**Comment by Valeri0p** [comment]
Perfect 👍 
Excuse for the spam, but you can also read my post on the ['temp](https://gbatemp.net/threads/twloader-ctr-mode-nds-app.448375/page-112#post-7019527) thread?
Thanks :)

**Comment by Margen67** [comment]
Since 3.0 is released can this be closed now?

**Comment by Robz8** [comment]
Yes.
