### ISSUE TITLE
Get banner data from Slot-1 card (NTR/TWL done, CTR also done (text only))

### ISSUE THREAD

**Issue by Robz8** [Robz8/TWLoader#76]
The code is in here:
https://github.com/Steveice10/FBI/blob/master/source/ui/section/task/listtitles.c#L139
But I have no idea what parts of the code to copy over.

**Comment by Robz8** [comment]
@GerbilSoft Do you want to look into this?

**Comment by Jolty95** [comment]
I tried it too but didn't success to read it :(

**Comment by GerbilSoft** [comment]
This is already being done as part of the Slot-1 icon PR. It's not being cached because there isn't much point in doing so.

CTR Slot-1 banners aren't being read yet because they're in a different format (SMDH).
