### ISSUE TITLE
[Request] DS game cheats 

### ISSUE THREAD

**Issue by rpalmon** [Robz8/TWLoader#8]
Do you think it could be possible for you to add DS game cheats?

**Comment by weirdal3333** [comment]
I'd like this too, but only after I can launch a '.nds' file from my internal sd card!
You might be able to use the usrcheat.dat file from ysmenu or the r4i menus.

**Comment by BARNWEY** [comment]
Sorry weirdal3333, that's not the case. YSMenu uses an autoboot function, meaning it bypasses all the menus and immediately starts booting the game.

**Comment by Robz8** [comment]
Cheats are on the todo list.
