### ISSUE TITLE
Unsure which forwarder to use for R4i Gold 3DS/RTS

### ISSUE THREAD

**Issue by Margen67** [Robz8/TWLoader#84]
There's forwarders for R4i-SDHC RTS, and R4i Gold.
But what I have is this: http://www.r4ids.cn/r4ds/r4i-rts1.jpg
So which one do I use?

**Comment by Robz8** [comment]
Use the one that says "R4i-SDHC RTS".

**Comment by Margen67** [comment]
I'm using that pack but I'm having problems.
I've extracted the files to the root of the flashcart SD but when I go to "Add games" it goes to the flashcart menu with no text visible. I can still navigate the menu with the touch screen and dpad. It takes a few seconds for the icon to animate.
When I press A or tap the game I want to make a forwarder for it launches the game.
When I go back to the home menu and relaunch TWLoader I don't see any icons from the flashcart tab.

**Comment by Robz8** [comment]
Download this: https://github.com/Robz8/TWLoader/raw/master/7zfile/sdroot/_nds/twloader/loadflashcard/r4idsn.nds
and put it into "sdmc:/_nds/twloader/loadflashcard/", replacing the existing file.

**Comment by Margen67** [comment]
Still the same.

**Comment by Robz8** [comment]
Check "lastsave.ini" in the flashcard SD, at "sd:/_wfwd/".

**Comment by Margen67** [comment]
`[Save Info]
lastLoaded = fat0:/0434 New Super Mario Bros. (US).nds
`

**Comment by Robz8** [comment]
Did you also extract the "_nds" folder in TWLoader.7z's "flashcardroot" to the flashcard root?

**Comment by Margen67** [comment]
It works now but after creating an ini file I restart and go back to TWLoader and it's not listed.

**Comment by Margen67** [comment]
@Robz8 Would it be possible to manually create .ini files?

**Comment by Robz8** [comment]
If they're manually created, TWLoader won't get the box art for them, unless you know what the game's TID is, and set it to TID in the .ini file.

**Comment by Robz8** [comment]
Are you sure there is no .ini file created at "sdmc:/roms/flashcard/nds/"?

**Comment by Margen67** [comment]
I removed it TWLoader by deleting the title+ticket and deleting the files from the flashcart MicroSD and the 3DS SD and reinstalled everything etc but now TWLoader starts up but instantly crashes with
```
An error has occured, forcing the software to close.

The system will now restart.
(Unsaved data may be lost)
```

**Comment by Robz8** [comment]
Well, wait for the next release, then.

**Comment by Margen67** [comment]
Are there any hourly builds like Luma?

For future reference etc:
11.2 updated SysNAND N3DS with https://github.com/AuroraWright/Luma3DS/commit/ff4517e58337a83a26444905799e532e52d0d36a launched from CTRNAND using https://github.com/AuroraWright/arm9loaderhax/commit/803955521ac22345d500c65c95ea0d368d317d35

Clean TWL_FIRM, no emuNAND on the 3DS's SD card.
It's a clean install since as mentioned before I deleted the files from the 3DS, and flashcart SD card and deleted the titles+tickets with FBI.


If I have any further problems after the new release I will create a new issue.
