### ISSUE TITLE
Daily/hourly/nightly builds

### ISSUE THREAD

**Issue by Margen67** [Robz8/TWLoader#86]
Like ~~[bootstrap](https://labs.projectkaeru.xyz/bootstrap/) and~~ [Luma](https://astronautlevel2.github.io/Luma3DS/)

**Comment by Hakujou** [comment]
Available at my server if you want : https://jenkins.hakujou.fr/job/3DS/job/TWLoader
(The latest builds are broken, not sure of why)

**Comment by Robz8** [comment]
How so?

**Comment by Hakujou** [comment]
It can't build as it's a Linux (case-sensitive) server, as mentioned on #87.

**Comment by Margen67** [comment]
Since both of these issues are solved can this be closed?

**Comment by Hakujou** [comment]
You can as you're the one who created it.

**Comment by Margen67** [comment]
Reopening since @Hakujou's link is dead.

**Comment by Hakujou** [comment]
I removed the project since the project broke too often. I had to fix it almost every day, and the last ~20 builds were also broken.

If it stops to crash every two nightlies I'll re-add it.

**Comment by Jolty95** [comment]
@Hakujou can you try one more time, please? Now TWLoader compile with devkitpro r46 :P

**Comment by Hakujou** [comment]
I'll look into it, but since it uses a different repo which is not a submodule (no idea of why), it'll be a little bit more complicated and might take some time. Please be patient.

**Comment by Margen67** [comment]
@Hakujou

**Comment by Hakujou** [comment]
Last time I checked it was still a mess to build (mainly due to Jekins way of working with Git repos). I'll take a look ASAP, as I've updated a lot of things.

**Comment by Hakujou** [comment]
Still broken : https://jenkins.hakujou.fr/job/3DS/job/TWLoader/1/console

Also, there's a mistake on your compile.bat. It tries to cd to twlnand-side where it probably should be flashcard-side. Still, it doesn't work... I'll need your help with this one.

**Comment by Margen67** [comment]
Solved by https://github.com/Robz8/TWLoader/commit/5494e2d5db2d6d48c7c5af6da62d21871abcc53e ?

**Comment by Hakujou** [comment]
I updated my Jenkins script and libs, it's now working : https://jenkins.hakujou.fr/job/3DS/job/TWLoader/43/

Please consider updating or removing the "compile.bat" file on the repository...

**Comment by Jolty95** [comment]
@Hakujou Imma update the compile.bat in some minutes ;)

Also, as Margen said, I've added an script to travis to push nightlies to our update server too, and, since OP answer is now answered (twice), I think this issue can be closed :)

**Comment by maorninja** [comment]
Hey, um, sorry for the bump, but the Jenkins server is down.

@Hakujou Please fix. If you guys need a server, I can always install Jenkins on mine.

**Comment by Hakujou** [comment]
Don't worry, it's just a little maintenance on my side. Servers will be back in few hours !

**Comment by maorninja** [comment]
Okay.
