### ISSUE TITLE
Wrong name for twlapp-hb.elf on arm9

### ISSUE THREAD

**Issue by Hakujou** [Robz8/TWLoader#87]
Hi,

The makefile generates a "twlapp-hb.elf" file on twlnand-side/arm9 where it probably should generate a "TWLapp-hb.elf". It probably works on Windows as it's not case-sensitive, but compilation is broken on Unix systems.

Build log available at : https://jenkins.hakujou.fr/job/3DS/job/TWLoader/32/console

**Comment by Robz8** [comment]
Will fix it.

**Comment by Robz8** [comment]
And it's fixed.

**Comment by Hakujou** [comment]
Confirmed, no error on build.
