### ISSUE TITLE
After Updating to 3.0, TWLoader Crashes

### ISSUE THREAD

**Issue by rpalmon** [Robz8/TWLoader#89]
So I updated TWLoader to 3.0 but now when it finishes downloading box art and updates bootstrap (unofficial) it crashes.

**Comment by rpalmon** [comment]
Then restarting the system

**Comment by Robz8** [comment]
Did you specify your rom paths?

**Comment by rpalmon** [comment]
I'll check that tomorrow as I dont have my computer on me.

**Comment by Bryguy5849** [comment]
Mine crashes when going through my games and only crashes when it gets to a specific game. Any idea what's causing this?

**Comment by Robz8** [comment]
Try clearing the following folders:
"sdmc:/_nds/twloader/boxart/"
"sdmc:/_nds/twloader/bnricons/"
"sdmc:/_nds/twloader/boxart/flashcard/"
"sdmc:/_nds/twloader/bnricons/flashcard"

**Comment by Bryguy5849** [comment]
That didn't work

**Comment by Robz8** [comment]
Sorry. I can't fix it if I'm not getting the crash.

**Comment by Bryguy5849** [comment]
More specifically I'm in the menu, and it crashes when when I'm going through my nds files

**Comment by Bryguy5849** [comment]
This only started happened after updating? It's your app, you can't just not fix it if it's not working properly. Well you could but that'd be sad haha

**Comment by DarthVitrial** [comment]
I'm having this issue too when it reaches a specific game, only in this version. Is there a way to create a crash dump for diagnostics?

**Comment by Robz8** [comment]
In Luma settings, set Dev features to ErrDisp.

**Comment by Robz8** [comment]
Are you three using O3DS'?

**Comment by Bryguy5849** [comment]
I'm doing a %100 fresh install. I'll update you in a second my friend!

**Comment by Bryguy5849** [comment]
Now I'm just straight crashing at the logo. I'm on o3DS LumaAl9h

**Comment by DarthVitrial** [comment]
Nope, n3DS.
Here's the crash dump from Luma:
https://mega.nz/#!0gsBmI5Q!Tu48seEmk5kyX8SX66vq27iixjNxq-VARvvlW6BSaac

**Comment by Margen67** [comment]
Duplicate of #91

**Comment by hectortillo** [comment]
Rpalmon do you have tried the last update?

**Comment by DarthVitrial** [comment]
It's fixed for me in the newest update.
