### ISSUE TITLE
[Request] Nds light manual changer

### ISSUE THREAD

**Issue by weirdal3333** [Robz8/TWLoader#9]
I want to be able to change the light to a certain color. Can you make it so we can use HTML color codes to change the light? I want it to fade slowly between 3 specific colors for chrismas (Red, Green, and Yellow.)
A homebrew app (another repo) that lets you change this would be awesome too!

**Comment by Robz8** [comment]
Are you referring to the Notification LED light?

**Comment by weirdal3333** [comment]
Yes! It would be really awesome to have an option to change the led so that certain homebrew games had different colors/combinations of colors. You could make a DEFAULT notification color, and then have an option in a game setting (along with the eventual cheat selector) to change THIS GAME'S notification led color.

I also observed that the light stays on after you close the 3ds.

**Comment by bakawun** [comment]
@Robz8 do you intend to implent custom led colors?

**Comment by Jolty95** [comment]
This can be close ;)
