### ISSUE TITLE
o3ds TWloader v3.0 crash after fresh install

### ISSUE THREAD

**Issue by Bryguy5849** [Robz8/TWLoader#90]
At first it auto updated and everything went smoothly and I was able access the app and check all the new features, then it froze and booted me back to the home menu when getting to about the 7th game on my flashcard list. I deleted all twloader folders and directories and tried to clean install v 3.0 and now it just crashes at the logo after a few seconds.

**Comment by Robz8** [comment]
I can't seem to fix this.

**Comment by Bryguy5849** [comment]
Ok,no worries. Any idea what may be causing it? Its got to be some sort of imcompatibility somewhere

**Comment by Bryguy5849** [comment]
Im now trying updating from a clean install of an older version (2.4.2)

**Comment by Margen67** [comment]
Duplicate of #91

**Comment by Bryguy5849** [comment]
Issue solved as of 3.0.1. Thank you!
