### ISSUE TITLE
[HELP!] Crashing in v3.0.

### ISSUE THREAD

**Issue by Robz8** [Robz8/TWLoader#91]
This is strange, because I'm not getting the crash at all.

**Comment by Bryguy5849** [comment]
I can't even use v.3 :( and this is definitely my favorite app right now. I don't what to do or how to troubleshoot, I've tried everything

**Comment by DarthVitrial** [comment]
I posted my crash dump in the other thread, if that helps.

**Comment by maorninja** [comment]
[crash_dump_00000012.zip](https://github.com/Robz8/TWLoader/files/722036/crash_dump_00000012.zip)
[log.zip](https://github.com/Robz8/TWLoader/files/722037/log.zip)

The top one is my crash dump from ERRDISP and my bottom one is my log.ini

BTW, Internet doesn't work.

**Comment by JBoughter** [comment]
I've got 2 crash dumps from 3.0 and my log.
[log.zip](https://github.com/Robz8/TWLoader/files/722067/log.zip)
[arm11.zip](https://github.com/Robz8/TWLoader/files/722064/arm11.zip)

**Comment by mariogamer2** [comment]
[log.zip](https://github.com/Robz8/TWLoader/files/722166/log.zip)
[crash_dump_00000001.zip](https://github.com/Robz8/TWLoader/files/722169/crash_dump_00000001.zip)

It's probably the same file,you probably have to check.

**Comment by mariogamer2** [comment]
Maybe some problem with dkarm r46? don't know.

**Comment by Robz8** [comment]
Please test the new version, and see if it gets rid of the crash.
https://github.com/Robz8/TWLoader/releases/tag/v3.0.1

**Comment by aj-m** [comment]
@Robz8 3.0.1 works on my 11.2.0-35U 2DS with Luma. Previously crashed on 3.0.0, so Works On My Machine.
