### ISSUE TITLE
Can't build gui

### ISSUE THREAD

**Issue by Hakujou** [Robz8/TWLoader#95]
Hi,

Build is broken again with latest builds when it tries to build gui : https://jenkins.hakujou.fr/job/3DS/job/TWLoader/35/console

Any idea to fix that ?

Thanks

**Comment by Margen67** [comment]
Try building with devkitARM r45 #82

**Comment by Hakujou** [comment]
I'm already on r45, the error doesn't seems related to this at all.

**Comment by Jolty95** [comment]
@Margen67 this is not even related with devkitARM

@Hakujou you are right. This [struct](https://github.com/Robz8/TWLoader/blob/master/gui/source/settings.h#L58) need to add `fcromfolder`. I'll create a PR fixing it

**Comment by Hakujou** [comment]
Fixed, thanks !
