### ISSUE TITLE
An error has occurred after using Add Games feature

### ISSUE THREAD

**Issue by LonKeelay** [Robz8/TWLoader#98]
I followed the directions to load roms on my R4 SDHC Dual-Core, and after I finished playing the ROM, I went back and ran TWLoader again, and it crashed after loading the banners, giving the usual  "An error has occurred" message and restarting my 3DS. I use Luma3DS and A9LH.

**Comment by Robz8** [comment]
Try updating TWLoader to v3.0.2.
